// Character set: common Cantonese characters across 20 levels.
// jyutping: array of accepted readings (primary first).
// meanings: array of accepted English answers (primary first).
// New levels are always appended at the end — never reorder or remove an
// existing entry — so ids stay stable for anyone who already has progress.
const characters = [
  // ===== Level 1: numbers & basics =====
  { hanzi: "一", level: 1, jyutping: ["jat1"], meanings: ["one"],
    meaningMnemonic: "一 is a single horizontal stroke — literally one line for the number one.",
    readingMnemonic: "Jat1 sounds like 'yacht' without the 'ch' — picture ONE lonely yacht on the water. Tone 1 is high and flat, like a bored monotone 'jaaat'." },
  { hanzi: "二", level: 1, jyutping: ["ji6"], meanings: ["two"],
    meaningMnemonic: "二 is two horizontal strokes stacked up — two lines for the number two.",
    readingMnemonic: "Ji6 sounds like 'jee' said low and heavy. Tone 6 is low and flat — say 'jee' in the deepest, most bored voice you can for two." },
  { hanzi: "三", level: 1, jyutping: ["saam1"], meanings: ["three"],
    meaningMnemonic: "三 is three horizontal strokes — three lines stacked for the number three.",
    readingMnemonic: "Saam1 sounds like 'sam' (the name). Picture three guys all named Sam standing in a row. Tone 1: high and flat, like calling out 'Saam!' sharply." },
  { hanzi: "人", level: 1, jyutping: ["jan4"], meanings: ["person", "people"],
    meaningMnemonic: "人 looks like a little stick figure of a person walking on two legs.",
    readingMnemonic: "Jan4 sounds like 'yun' as in 'young'. Picture a young PERSON. Tone 4 is low and rising, a relaxed drawn-out 'yuuun'." },
  { hanzi: "大", level: 1, jyutping: ["daai6"], meanings: ["big", "large"],
    meaningMnemonic: "大 looks like a person (人) stretching their arms out wide to show how BIG something is.",
    readingMnemonic: "Daai6 sounds like 'die' said low and heavy — imagine something so BIG it makes you go 'oh, I could die' in a low, flat tone 6 voice." },
  { hanzi: "小", level: 1, jyutping: ["siu2"], meanings: ["small", "little"],
    meaningMnemonic: "小 looks like a tiny thing with two small drops on either side — everything about it is SMALL.",
    readingMnemonic: "Siu2 sounds like 'shew' (as in 'shoo, little fly'). Tone 2 rises like a question: 'siu2?' — small and curious." },
  { hanzi: "中", level: 1, jyutping: ["zung1"], meanings: ["middle", "center"],
    meaningMnemonic: "中 is a box with a line straight through its MIDDLE, like an arrow hitting dead-center.",
    readingMnemonic: "Zung1 sounds like 'jung' as in Carl Jung. Tone 1 high and flat: a dart flying straight and level into the CENTER of the target — 'zung!'" },
  { hanzi: "好", level: 1, jyutping: ["hou2"], meanings: ["good", "well"],
    meaningMnemonic: "好 is a woman (女) next to her child (子) — a mother with her child is a GOOD, wholesome scene.",
    readingMnemonic: "Hou2 sounds like 'how' with a rising tone, like asking 'how good is it?' — and the rising pitch answers: pretty GOOD!" },
  { hanzi: "我", level: 1, jyutping: ["ngo5"], meanings: ["I", "me"],
    meaningMnemonic: "我 is a picture of a hand holding a spear — 'this spear is mine, I am the one holding it.'",
    readingMnemonic: "Ngo5 sounds like 'ngoh' — like the sound you make pointing at your own chest saying 'me? Ngoh!' Tone 5 dips low then rises." },
  { hanzi: "你", level: 1, jyutping: ["nei5"], meanings: ["you"],
    meaningMnemonic: "你 is a person (亻) next to 尔 — pointing at the person standing right there: YOU.",
    readingMnemonic: "Nei5 sounds like 'nay' dipping then rising, like pointing at someone and going 'nei5? Yeah, YOU.'" },

  // ===== Level 2: family & basic adjectives =====
  { hanzi: "四", level: 2, jyutping: ["sei3"], meanings: ["four"],
    meaningMnemonic: "四 is a box with legs splayed inside — four corners for the number four.",
    readingMnemonic: "Sei3 sounds like 'say'. Tone 3 is mid and flat: say 'say' flatly, four times if you like." },
  { hanzi: "五", level: 2, jyutping: ["ng5"], meanings: ["five"],
    meaningMnemonic: "五 looks like an X crossed inside a box — count the five lines that make up the character.",
    readingMnemonic: "Ng5 is just a nasal 'mmm' sound dipping then rising — hum 'ng5' while holding up five fingers." },
  { hanzi: "六", level: 2, jyutping: ["luk6"], meanings: ["six"],
    meaningMnemonic: "六 looks like a little roof over two legs — a house numbered SIX.",
    readingMnemonic: "Luk6 sounds like 'luk' as in 'look'. Tone 6 low and flat: 'luk, there's six of them.'" },
  { hanzi: "女", level: 2, jyutping: ["neoi5"], meanings: ["woman", "female"],
    meaningMnemonic: "女 is a simple sketch of a woman kneeling gracefully — the character for WOMAN.",
    readingMnemonic: "Neoi5 sounds like 'noy' dipping then rising, like saying 'noy' with an eyebrow raised — a WOMAN raising an eyebrow at you." },
  { hanzi: "男", level: 2, jyutping: ["naam4"], meanings: ["man", "male"],
    meaningMnemonic: "男 is a rice field (田) over strength (力) — a MAN out working the field with his strength.",
    readingMnemonic: "Naam4 sounds like 'naam' as in Vietnam. A strong MAN from 'Naam', said low and drawn out for tone 4." },
  { hanzi: "爸", level: 2, jyutping: ["baa1"], meanings: ["dad", "father"],
    meaningMnemonic: "爸 has father (父) on top of a wave-like base — picture DAD as the head of the household.",
    readingMnemonic: "Baa1 is exactly like 'baa' — the very first sound a baby makes for DAD, high and flat." },
  { hanzi: "媽", level: 2, jyutping: ["maa1"], meanings: ["mom", "mother"],
    meaningMnemonic: "媽 has woman (女) next to horse (馬) — MOM, who works as hard and fast as a horse.",
    readingMnemonic: "Maa1 is exactly like 'maa' — the very first sound a baby makes for MOM, high and flat." },
  { hanzi: "老", level: 2, jyutping: ["lou5"], meanings: ["old (people)"],
    meaningMnemonic: "老 looks like a bent-over figure leaning on a cane — an OLD person walking slowly.",
    readingMnemonic: "Lou5 sounds like 'low' dipping then rising — an OLD man's voice, low and creaky." },
  { hanzi: "多", level: 2, jyutping: ["do1"], meanings: ["many", "much"],
    meaningMnemonic: "多 is two evening (夕) symbols stacked — two nights of the same thing means it happens a lot, MANY times.",
    readingMnemonic: "Do1 sounds exactly like the word 'dough' — imagine MANY, MANY balls of dough piled high, said flat and high." },
  { hanzi: "細", level: 2, jyutping: ["sai3"], meanings: ["small (colloquial)", "little"],
    meaningMnemonic: "細 is silk thread (糸) next to a field (田) — even a tiny thread in a huge field looks SMALL.",
    readingMnemonic: "Sai3 sounds like 'sigh' without the 'gh'. Say 'sai' flatly with a little sigh — something so SMALL it's barely worth noticing." },

  // ===== Level 3: more numbers & time =====
  { hanzi: "七", level: 3, jyutping: ["cat1"], meanings: ["seven"],
    meaningMnemonic: "七 looks like a bent number 7 — the number SEVEN, plain and simple.",
    readingMnemonic: "Cat1 sounds exactly like 'cat'. Picture SEVEN cats in a row, said high and flat." },
  { hanzi: "八", level: 3, jyutping: ["baat3"], meanings: ["eight"],
    meaningMnemonic: "八 looks like two strokes splitting apart — EIGHT, a lucky number in Cantonese culture.",
    readingMnemonic: "Baat3 sounds like 'baht' (the Thai currency) said flatly. Imagine paying EIGHT baht for something lucky." },
  { hanzi: "九", level: 3, jyutping: ["gau2"], meanings: ["nine"],
    meaningMnemonic: "九 looks like a hook or a claw reaching up — NINE lives of a cat clawing at you.",
    readingMnemonic: "Gau2 sounds like 'gow' rising, close to the English word 'gow' in 'go'. A rising 'gau2?' as if counting up to NINE." },
  { hanzi: "十", level: 3, jyutping: ["sap6"], meanings: ["ten"],
    meaningMnemonic: "十 is a simple cross — two strokes crossing to make TEN, like a perfect ten out of ten score marked with an X-turned-plus.",
    readingMnemonic: "Sap6 sounds like 'sup' said low and flat, like slurping soup TEN times: 'sap, sap, sap...'" },
  { hanzi: "日", level: 3, jyutping: ["jat6"], meanings: ["day", "sun"],
    meaningMnemonic: "日 is a little window with a line through the middle — a picture of the SUN, and by extension a DAY.",
    readingMnemonic: "Jat6 sounds like 'yut' said low and flat — a long, low 'yut' as the SUN sets low on the horizon at the end of the DAY." },
  { hanzi: "月", level: 3, jyutping: ["jyut6"], meanings: ["month", "moon"],
    meaningMnemonic: "月 is a crescent shape with two strokes inside — a picture of the MOON, and by extension a MONTH (one moon cycle).",
    readingMnemonic: "Jyut6 sounds like 'yuet' said low and flat — round your lips like you're about to whistle at the MOON, then drop your voice low." },
  { hanzi: "年", level: 3, jyutping: ["nin4"], meanings: ["year"],
    meaningMnemonic: "年 looks like a stalk of grain being carried home — a full harvest happens once a YEAR.",
    readingMnemonic: "Nin4 sounds like 'neen' drawn out low, like a long 'nnniiin' — one whole YEAR feels like it drags on forever." },
  { hanzi: "時", level: 3, jyutping: ["si4"], meanings: ["time", "hour"],
    meaningMnemonic: "時 has sun (日) next to a temple/measure (寺) — measuring the sun's position tells you the TIME.",
    readingMnemonic: "Si4 sounds like 'see' drawn out low. You 'see' the clock to check the TIME, low and calm." },
  { hanzi: "天", level: 3, jyutping: ["tin1"], meanings: ["sky", "day"],
    meaningMnemonic: "天 is a big person (大) with a line over their head — the SKY stretches above even the biggest person; also used for 'day'.",
    readingMnemonic: "Tin1 sounds exactly like 'tin'. Picture a TIN roof with the open SKY visible through a hole in it, said high and flat." },
  { hanzi: "今", level: 3, jyutping: ["gam1"], meanings: ["now", "this (time)"],
    meaningMnemonic: "今 looks like a lid closing down tightly on the present moment — right NOW, this instant.",
    readingMnemonic: "Gam1 sounds like 'gum' said high and flat — chew that gum right NOW, this very moment." },

  // ===== Level 4: common verbs =====
  { hanzi: "食", level: 4, jyutping: ["sik6"], meanings: ["eat"],
    meaningMnemonic: "食 looks like a covered dish sitting on a stand — a bowl of food ready to be EATEN.",
    readingMnemonic: "Sik6 sounds like 'sick' said low and flat — you'll feel SICK if you EAT too much, low and heavy tone." },
  { hanzi: "飲", level: 4, jyutping: ["jam2"], meanings: ["drink"],
    meaningMnemonic: "飲 has the food radical (食) next to a person opening their mouth wide (欠) — opening your mouth wide to DRINK.",
    readingMnemonic: "Jam2 sounds like 'yum' rising, as in 'yum, this drink is nice!' — rising tone like a happy question." },
  { hanzi: "去", level: 4, jyutping: ["heoi3"], meanings: ["go"],
    meaningMnemonic: "去 shows a person (土-like shape) stepping out and away from a doorway (厶) — heading out, about to GO.",
    readingMnemonic: "Heoi3 sounds like 'huoy' said flatly, close to calling out 'hoi!' as you GO out the door — mid, flat tone." },
  { hanzi: "嚟", level: 4, jyutping: ["lai4"], meanings: ["come"],
    meaningMnemonic: "嚟 is a mouth (口) shouting the word for COME — this is a spoken Cantonese character, literally built to be said out loud calling someone over.",
    readingMnemonic: "Lai4 sounds like 'lie' said low and drawn out — 'laaaai' — like calling someone from across the room to COME here." },
  { hanzi: "睇", level: 4, jyutping: ["tai2"], meanings: ["look", "watch", "see"],
    meaningMnemonic: "睇 has the eye radical (目) — of course a character with an eye in it means to LOOK or WATCH.",
    readingMnemonic: "Tai2 sounds like 'tie' rising, like asking 'tie2? Can you see the tie I'm wearing?' — rising, questioning tone as you LOOK." },
  { hanzi: "聽", level: 4, jyutping: ["teng1"], meanings: ["listen", "hear"],
    meaningMnemonic: "聽 has the ear radical (耳) tucked inside — packed with ears, so naturally it means to LISTEN.",
    readingMnemonic: "Teng1 sounds like 'tang' as in orange Tang drink, high and flat — LISTEN closely, high and clear." },
  { hanzi: "講", level: 4, jyutping: ["gong2"], meanings: ["speak", "say", "talk"],
    meaningMnemonic: "講 has the speech radical (言) on the left — anything with 言 involves words, here meaning to SPEAK.",
    readingMnemonic: "Gong2 sounds like 'gong' rising, like hitting a gong and asking a question with it — SPEAK up like a rising gong." },
  { hanzi: "做", level: 4, jyutping: ["zou6"], meanings: ["do", "make"],
    meaningMnemonic: "做 has the person radical (亻) next to a character meaning 'made' — a person DOING or MAKING something.",
    readingMnemonic: "Zou6 sounds like 'joe' said low and flat — 'Joe, just DO it,' said in a low, flat, no-nonsense voice." },
  { hanzi: "買", level: 4, jyutping: ["maai5"], meanings: ["buy"],
    meaningMnemonic: "買 has the shell/money radical (貝) at the bottom — money changing hands to BUY something.",
    readingMnemonic: "Maai5 sounds like 'my' dipping then rising — 'is this MY purchase?' dipping down then rising in pitch as you BUY it." },
  { hanzi: "賣", level: 4, jyutping: ["maai6"], meanings: ["sell"],
    meaningMnemonic: "賣 also has the money radical (貝) at the bottom, with 士 and 買-like elements on top — goods stacked up on top of money, ready to SELL.",
    readingMnemonic: "Maai6 sounds just like 買 (maai5) but low and flat instead of dipping-rising — same sound family, but SELLING is the low, flat, final version of buying." },

  // ===== Level 5: places & directions =====
  { hanzi: "屋", level: 5, jyutping: ["uk1"], meanings: ["house"],
    meaningMnemonic: "屋 has the roof radical (尸) over 至 — a roof over your head means a HOUSE.",
    readingMnemonic: "Uk1 sounds like a short, sharp 'uk!' — the sound you'd make bonking your head on the low doorway of a tiny HOUSE, high and flat." },
  { hanzi: "企", level: 5, jyutping: ["kei5"], meanings: ["stand"],
    meaningMnemonic: "企 has a person (人) standing on top of stop (止) — a person planted firmly, STANDING. Combined with 屋 it forms 屋企 (home) — the place where you stand and stay.",
    readingMnemonic: "Kei5 sounds like 'kay' dipping then rising — STAND up straight and say 'kei5!' with confidence." },
  { hanzi: "學", level: 5, jyutping: ["hok6"], meanings: ["study", "learn"],
    meaningMnemonic: "學 shows two hands over a child (子) under a roof — hands guiding a child to STUDY and LEARN.",
    readingMnemonic: "Hok6 sounds like 'hock' said low and flat — hunker down and STUDY, low and serious." },
  { hanzi: "校", level: 5, jyutping: ["haau6"], meanings: ["school (institution)"],
    meaningMnemonic: "校 has the wood radical (木) next to a mixing/comparing element — wooden desks lined up, the SCHOOL building.",
    readingMnemonic: "Haau6 sounds like 'how' said low and flat — 'haau6, that's the SCHOOL,' pointed out in a flat, matter-of-fact tone." },
  { hanzi: "街", level: 5, jyutping: ["gaai1"], meanings: ["street"],
    meaningMnemonic: "街 has the 'walk' radical (彳/亍) on both sides of 圭 — walking paths on both sides, a STREET.",
    readingMnemonic: "Gaai1 sounds like 'guy' said high and flat — a GUY walking down the STREET, high and flat tone." },
  { hanzi: "市", level: 5, jyutping: ["si5"], meanings: ["market", "city"],
    meaningMnemonic: "市 looks like a flag flying over a stall — a flag marking a busy MARKET or CITY square.",
    readingMnemonic: "Si5 sounds like 'see' dipping then rising — 'si5? Do you SEE the MARKET over there?'" },
  { hanzi: "上", level: 5, jyutping: ["soeng5", "soeng6"], meanings: ["up", "above", "to go up"],
    meaningMnemonic: "上 is a short stroke sitting ABOVE a long baseline — clearly marking something that is UP or above.",
    readingMnemonic: "Soeng5 dips then rises — literally rising in pitch as you go UP. As a plain position word it flattens to soeng6, low and flat, like something already sitting up there." },
  { hanzi: "下", level: 5, jyutping: ["haa6"], meanings: ["down", "below"],
    meaningMnemonic: "下 is a short stroke sitting BELOW a long baseline — the mirror image of 上, marking DOWN or below.",
    readingMnemonic: "Haa6 sounds like 'haa' said low and flat — a low sigh 'haaa' as you slump DOWN." },
  { hanzi: "左", level: 5, jyutping: ["zo2"], meanings: ["left"],
    meaningMnemonic: "左 has the 'work' radical (工) under a hand-like stroke — many people naturally work with their LEFT hand guiding tools.",
    readingMnemonic: "Zo2 sounds like 'joe' rising — 'zo2? Is it to the LEFT?' asked with a rising, uncertain tone." },
  { hanzi: "右", level: 5, jyutping: ["jau6"], meanings: ["right"],
    meaningMnemonic: "右 has a mouth (口) under a hand-like stroke — pointing with your hand near your mouth to say 'it's to the RIGHT.'",
    readingMnemonic: "Jau6 sounds like 'yow' said low and flat — pointing firmly and flatly: 'jau6, RIGHT there.'" },

  // ===== Level 6: question words & particles =====
  { hanzi: "邊", level: 6, jyutping: ["bin1"], meanings: ["side", "which", "where"],
    meaningMnemonic: "邊 has the 'walk' radical (辶) leading off to the SIDE — wandering off to one side, asking WHICH way or WHERE.",
    readingMnemonic: "Bin1 sounds exactly like 'bin' (a trash bin), high and flat — 'bin1? Which BIN is it in?'" },
  { hanzi: "個", level: 6, jyutping: ["go3"], meanings: ["measure word (general)", "individual"],
    meaningMnemonic: "個 has the person radical (亻) next to 固 (solid) — a solid, single, countable INDIVIDUAL — the all-purpose measure word.",
    readingMnemonic: "Go3 sounds exactly like 'go', said mid and flat — 'go3' one at a time, counting off each individual item: go, go, go." },
  { hanzi: "乜", level: 6, jyutping: ["mat1"], meanings: ["what (colloquial)"],
    meaningMnemonic: "乜 is a squiggly, confused-looking little shape — it looks like a shrug, which is exactly the reaction to 'WHAT?'",
    readingMnemonic: "Mat1 sounds like 'mat' (a floor mat), high and flat — 'mat1? WHAT mat is this?'" },
  { hanzi: "點", level: 6, jyutping: ["dim2"], meanings: ["point", "dot", "how"],
    meaningMnemonic: "點 has fire/dots (灬) at the bottom — a scatter of DOTS or POINTS; asking 'at what POINT/HOW' something happens.",
    readingMnemonic: "Dim2 sounds exactly like 'dim' (as in dim sum, or a dim light), rising — 'dim2? HOW do we get to dim sum?'" },
  { hanzi: "解", level: 6, jyutping: ["gaai2"], meanings: ["explain", "solve", "loosen"],
    meaningMnemonic: "解 has horn (角), knife (刀) and ox (牛) — using a knife to cut apart a horn from an ox: taking something apart to EXPLAIN or SOLVE it.",
    readingMnemonic: "Gaai2 sounds like 'guy' rising — 'gaai2? Can that GUY EXPLAIN this to me?'" },
  { hanzi: "幾", level: 6, jyutping: ["gei2"], meanings: ["how many", "quite", "several"],
    meaningMnemonic: "幾 looks like a small stack of things with legs — a small pile, prompting the question 'HOW MANY are there?'",
    readingMnemonic: "Gei2 sounds like 'gay' rising — 'gei2? HOW MANY are we talking about?' asked with a curious rising tone." },
  { hanzi: "樣", level: 6, jyutping: ["joeng6"], meanings: ["kind", "manner", "appearance"],
    meaningMnemonic: "樣 has the wood radical (木) next to sheep (羊) — a wooden carving shaped like a sheep shows a particular KIND or APPEARANCE.",
    readingMnemonic: "Joeng6 sounds like 'young' said low and flat — 'that's the KIND of style YOUNG people like,' said low and flat." },
  { hanzi: "咁", level: 6, jyutping: ["gam2"], meanings: ["so", "like this", "like that"],
    meaningMnemonic: "咁 has the mouth radical (口) next to sweet (甘) — a mouth sweetly saying 'it's just LIKE THIS, SO simple.'",
    readingMnemonic: "Gam2 sounds like 'gum' rising — 'gam2? Is it LIKE THIS?' asked with a rising, checking tone." },
  { hanzi: "嘢", level: 6, jyutping: ["je5"], meanings: ["thing"],
    meaningMnemonic: "嘢 has the mouth radical (口) next to also/moreover (野-ish shape) — a spoken Cantonese character used to point vaguely at any THING.",
    readingMnemonic: "Je5 sounds like 'yeah' dipping then rising — pointing at random and going 'je5, this THING here.'" },
  { hanzi: "呢", level: 6, jyutping: ["nei1", "ni1"], meanings: ["this (demonstrative)", "question particle"],
    meaningMnemonic: "呢 has the mouth radical (口) — spoken aloud while pointing at something close by: 'THIS one, right here.'",
    readingMnemonic: "Nei1 sounds just like 你 (nei5, 'you') but higher and flatter — pointing at something near you (nei) and calling it THIS." },

  // ===== Level 7: food =====
  { hanzi: "茶", level: 7, jyutping: ["caa4"], meanings: ["tea"],
    meaningMnemonic: "茶 has the grass/plant radical (艹) on top — TEA is a plant, brewed from leaves.",
    readingMnemonic: "Caa4 sounds exactly like 'cha' (as English speakers already say for TEA), low and drawn out." },
  { hanzi: "飯", level: 7, jyutping: ["faan6"], meanings: ["rice", "meal"],
    meaningMnemonic: "飯 has the food radical (飠) next to 反 — the classic food radical shows this is about a cooked MEAL, specifically RICE.",
    readingMnemonic: "Faan6 sounds like 'faan' (rhymes with 'fun'), low and flat — sit down low and flat for a good RICE MEAL." },
  { hanzi: "麵", level: 7, jyutping: ["min6"], meanings: ["noodles"],
    meaningMnemonic: "麵 has the wheat radical (麥) next to face (面) — NOODLES are made from wheat flour.",
    readingMnemonic: "Min6 sounds like 'min' said low and flat — slurp NOODLES slowly, low and flat: 'miiin.'" },
  { hanzi: "包", level: 7, jyutping: ["baau1"], meanings: ["bread", "bun", "to wrap"],
    meaningMnemonic: "包 looks like something curled up and WRAPPED inside a covering — a BUN wrapped around its filling.",
    readingMnemonic: "Baau1 sounds like 'bow' (as in take a bow), high and flat — a fluffy BUN puffing up high." },
  { hanzi: "蛋", level: 7, jyutping: ["daan2"], meanings: ["egg"],
    meaningMnemonic: "蛋 has the bug/small-creature radical (虫) with a bird-nest-like top — a little creature waiting to hatch from an EGG.",
    readingMnemonic: "Daan2 sounds like 'dan' rising, like the name Dan asking a question — cracking open an EGG with a rising 'dan2?'" },
  { hanzi: "牛", level: 7, jyutping: ["ngau4"], meanings: ["cow", "beef", "ox"],
    meaningMnemonic: "牛 looks like the front view of an ox's head with two horns — a COW or OX.",
    readingMnemonic: "Ngau4 sounds like a low 'now' — imagine a COW mooing 'ngaaaau' low and drawn out." },
  { hanzi: "豬", level: 7, jyutping: ["zyu1"], meanings: ["pig", "pork"],
    meaningMnemonic: "豬 has the pig radical (豕) on the right — plainly, a PIG.",
    readingMnemonic: "Zyu1 sounds like 'joo' high and flat — a little PIG going 'zyu1, zyu1' instead of oink." },
  { hanzi: "雞", level: 7, jyutping: ["gai1"], meanings: ["chicken"],
    meaningMnemonic: "雞 has the bird radical (鳥/隹) on the right — plainly, a CHICKEN.",
    readingMnemonic: "Gai1 sounds like 'guy' high and flat — a CHICKEN going 'gai1, gai1' instead of cluck." },
  { hanzi: "魚", level: 7, jyutping: ["jyu4"], meanings: ["fish"],
    meaningMnemonic: "魚 is a simple picture of a FISH — head, body with fins, and tail at the bottom.",
    readingMnemonic: "Jyu4 sounds like 'yu' (round your lips like whistling), low and drawn out — a slippery FISH sliding low through your hands." },
  { hanzi: "肉", level: 7, jyutping: ["juk6"], meanings: ["meat"],
    meaningMnemonic: "肉 looks like a slab of MEAT with the marbling/grain lines running through it.",
    readingMnemonic: "Juk6 sounds like 'yuk', low and flat — a thick, heavy cut of MEAT landing on the table with a low 'yuk' thud." },

  // ===== Level 8: connectors & misc adjectives =====
  { hanzi: "同", level: 8, jyutping: ["tung4"], meanings: ["same", "with", "and"],
    meaningMnemonic: "同 has a mouth (口) framed inside a box — everyone speaking with ONE SAME voice, together WITH each other.",
    readingMnemonic: "Tung4 sounds like 'tongue' without the 'e', low and drawn out — sharing one big 'tung' (tongue) SAME as everyone else." },
  { hanzi: "但", level: 8, jyutping: ["daan6"], meanings: ["but"],
    meaningMnemonic: "但 has the person radical (亻) next to dawn/morning (旦) — a person who was fine at dawn, BUT then something changed.",
    readingMnemonic: "Daan6 sounds like 'darn' without the 'r', low and flat — 'daan6, BUT that's a shame,' said low and resigned." },
  { hanzi: "因", level: 8, jyutping: ["jan1"], meanings: ["because", "cause", "reason"],
    meaningMnemonic: "因 shows a person (大-like shape) boxed inside a cause — trapped inside the reason WHY, the CAUSE.",
    readingMnemonic: "Jan1 sounds like 'yun' high and flat, similar to 人 (jan4, person) but higher — the REASON a certain PERSON did something." },
  { hanzi: "為", level: 8, jyutping: ["wai6", "wai4"], meanings: ["for", "because of", "to think / regard (as)"],
    meaningMnemonic: "為 shows a hand guiding an elephant — doing hard work FOR a reason, BECAUSE OF a goal.",
    readingMnemonic: "Wai6 sounds like 'why' said low and flat — asking 'wai6, WHY, FOR what reason?' As wai4 (rising-drawn), it shifts to mean 'to think/regard' — as in 以為 (to assume)." },
  { hanzi: "所", level: 8, jyutping: ["so2"], meanings: ["place", "that which"],
    meaningMnemonic: "所 has door (戶) next to axe (斤) — the specific PLACE where the woodcutter keeps his axe by the door.",
    readingMnemonic: "So2 sounds exactly like 'so' rising — 'so2? Is this the PLACE?' asked with a curious rising tone." },
  { hanzi: "以", level: 8, jyutping: ["ji5"], meanings: ["with", "by means of", "in order to"],
    meaningMnemonic: "以 looks like a person leaning on a tool — using a tool BY MEANS OF leaning on it.",
    readingMnemonic: "Ji5 sounds like 'yee' dipping then rising — leaning on something WITH a rising 'ji5' as you push off it." },
  { hanzi: "新", level: 8, jyutping: ["san1"], meanings: ["new"],
    meaningMnemonic: "新 has axe (斤) next to a tree-cutting element — freshly cut wood is NEW.",
    readingMnemonic: "San1 sounds like 'sun', high and flat — a NEW day starts with the SUN rising high and bright." },
  { hanzi: "舊", level: 8, jyutping: ["gau6"], meanings: ["old (things)"],
    meaningMnemonic: "舊 has grass (艹) growing over a bird-like shape — grass has grown over it from disuse, it's OLD.",
    readingMnemonic: "Gau6 sounds like 九 (gau2, nine) but lower and flatter — something so OLD it's been around since you were nine, low and worn out." },
  { hanzi: "快", level: 8, jyutping: ["faai3"], meanings: ["fast", "quick"],
    meaningMnemonic: "快 has the heart radical (忄) next to 夬 (decisive) — a decisive heart reacts FAST.",
    readingMnemonic: "Faai3 sounds like 'fie' (rhymes with 'pie') said flat and quick — say it FAST, in a flash." },
  { hanzi: "慢", level: 8, jyutping: ["maan6"], meanings: ["slow"],
    meaningMnemonic: "慢 has the heart radical (忄) next to a stretched-out shape (曼) — a heart that takes its time, beating SLOWly.",
    readingMnemonic: "Maan6 sounds like 'maan' (rhymes with 'lawn'), low and drawn out — stretch it out SLOWLY: 'maaaaan6.'" },
  { hanzi: "係", level: 8, jyutping: ["hai6"], meanings: ["to be", "yes"],
    meaningMnemonic: "係 has the person radical (亻) next to a hanging thread (系) — a person is connected TO BE what they are, tied to their identity.",
    readingMnemonic: "Hai6 sounds like 'hi' said low and flat — a flat, certain 'hai6' — YES, that IS correct." },

  // ===== Level 9: pronouns, negation & colors =====
  { hanzi: "佢", level: 9, jyutping: ["keoi5"], meanings: ["he", "she", "it", "they (singular)"],
    meaningMnemonic: "佢 has the person radical (亻) next to 巨 (giant) — a giant, mysterious THIRD PERSON you're talking about but who isn't here.",
    readingMnemonic: "Keoi5 sounds like 'kui' dipping then rising — pointing at someone off to the side and going 'keoi5? Who, THEM?'" },
  { hanzi: "哋", level: 9, jyutping: ["dei6"], meanings: ["(plural marker attached to pronouns)"],
    meaningMnemonic: "哋 has the mouth radical (口) next to earth (地) — said aloud after a pronoun to turn ONE person into a whole group standing on the same ground: 我哋 (we), 你哋 (you-all), 佢哋 (they).",
    readingMnemonic: "Dei6 sounds like 'day' said low and flat — a whole group gathered for the DAY, all lumped together." },
  { hanzi: "唔", level: 9, jyutping: ["m4"], meanings: ["not"],
    meaningMnemonic: "唔 has the mouth radical (口) next to 吾 (I/my) — when 'I' open my 'mouth' to disagree, out comes NOT.",
    readingMnemonic: "M4 is just a flat-toned 'mmm' — the disapproving hum you make shaking your head NO." },
  { hanzi: "紅", level: 9, jyutping: ["hung4"], meanings: ["red"],
    meaningMnemonic: "紅 has the silk radical (糹) next to work (工) — silk dyed RED took skilled work to make.",
    readingMnemonic: "Hung4 sounds like 'hung', low and drawn out — imagine a RED lantern hung low outside a shop." },
  { hanzi: "黃", level: 9, jyutping: ["wong4"], meanings: ["yellow"],
    meaningMnemonic: "黃 looks like a field (田) glowing under the sun — ripe crops turning YELLOW.",
    readingMnemonic: "Wong4 sounds like 'wong' (rhymes with 'song'), low and drawn out — a low, warm YELLOW glow." },
  { hanzi: "藍", level: 9, jyutping: ["laam4"], meanings: ["blue"],
    meaningMnemonic: "藍 has the grass radical (艹) on top — indigo plants were crushed to dye cloth BLUE.",
    readingMnemonic: "Laam4 sounds like 'lahm', low and drawn out — a deep BLUE lagoon, calm and low." },
  { hanzi: "綠", level: 9, jyutping: ["luk6"], meanings: ["green"],
    meaningMnemonic: "綠 has the silk radical (糹) next to a record/carve shape — GREEN silk thread, dyed and recorded in the ledger.",
    readingMnemonic: "Luk6 sounds just like 六 (luk6, six) — six GREEN leaves on the branch, low and flat." },
  { hanzi: "黑", level: 9, jyutping: ["hak1"], meanings: ["black"],
    meaningMnemonic: "黑 shows a window with soot/fire marks underneath — smoke stains everything BLACK.",
    readingMnemonic: "Hak1 sounds like 'hock' said high and flat — a sharp 'hak!' as the lights go out, pitch BLACK." },
  { hanzi: "白", level: 9, jyutping: ["baak6"], meanings: ["white"],
    meaningMnemonic: "白 looks like a candle with a bright flame on top — pure, WHITE light.",
    readingMnemonic: "Baak6 sounds like 'bak' said low and flat — a low 'baak' as you stare at a blank WHITE wall." },
  { hanzi: "色", level: 9, jyutping: ["sik1"], meanings: ["color"],
    meaningMnemonic: "色 shows a person bent over a hint of shape below — even a hint of shape carries COLOR.",
    readingMnemonic: "Sik1 sounds like 'sick', high and flat — a paint box so bright with COLOR it makes you dizzy." },

  // ===== Level 10: body parts =====
  { hanzi: "頭", level: 10, jyutping: ["tau4"], meanings: ["head"],
    meaningMnemonic: "頭 has the page/head radical (頁) on the right — anything with 頁 relates to the HEAD.",
    readingMnemonic: "Tau4 sounds like 'tow' said low and drawn out — someone got TOWed by the HEAD, low and slow." },
  { hanzi: "眼", level: 10, jyutping: ["ngaan5"], meanings: ["eye"],
    meaningMnemonic: "眼 has the eye radical (目) next to 艮 — plainly, an EYE.",
    readingMnemonic: "Ngaan5 sounds like 'ngaan' dipping then rising — squint one EYE and go 'ngaan5?' in question." },
  { hanzi: "耳", level: 10, jyutping: ["ji5"], meanings: ["ear"],
    meaningMnemonic: "耳 is a simple picture of an EAR, complete with its curled outer rim.",
    readingMnemonic: "Ji5 sounds like 'yee' dipping then rising — cup your EAR and go 'ji5? What did you say?'" },
  { hanzi: "鼻", level: 10, jyutping: ["bei6"], meanings: ["nose"],
    meaningMnemonic: "鼻 has the self/nose radical (自, originally a picture of a NOSE) on top of 畀 — the original character for NOSE.",
    readingMnemonic: "Bei6 sounds like 'bay' said low and flat — a low, stuffy-NOSE 'bei6' sound." },
  { hanzi: "口", level: 10, jyutping: ["hau2"], meanings: ["mouth"],
    meaningMnemonic: "口 is a simple open square — a wide open MOUTH.",
    readingMnemonic: "Hau2 sounds like 'how' rising — open your MOUTH and go 'hau2?' like you're about to ask something." },
  { hanzi: "手", level: 10, jyutping: ["sau2"], meanings: ["hand"],
    meaningMnemonic: "手 looks like an open palm with fingers spread — a HAND.",
    readingMnemonic: "Sau2 sounds like 'so' rising — hold up your HAND and go 'sau2?' asking for a high five." },
  { hanzi: "腳", level: 10, jyutping: ["goek3"], meanings: ["foot", "leg"],
    meaningMnemonic: "腳 has the flesh radical (月) next to 却 — the fleshy part of the body you stand on, the FOOT/LEG.",
    readingMnemonic: "Goek3 sounds like 'gerk' said flat — stub your toe and yell 'goek3!' clutching your FOOT." },
  { hanzi: "心", level: 10, jyutping: ["sam1"], meanings: ["heart", "mind"],
    meaningMnemonic: "心 is a simple picture of a HEART, complete with its chambers.",
    readingMnemonic: "Sam1 sounds exactly like 'Sam', high and flat — Sam wears his HEART on his sleeve." },
  { hanzi: "開", level: 10, jyutping: ["hoi1"], meanings: ["to open"],
    meaningMnemonic: "開 shows two hands pulling a bolt back from a door — pulling it OPEN.",
    readingMnemonic: "Hoi1 sounds exactly like 'hoy', high and flat — fling the door OPEN and shout 'hoi!'" },
  { hanzi: "水", level: 10, jyutping: ["seoi2"], meanings: ["water"],
    meaningMnemonic: "水 looks like a flowing stream splitting around a rock — WATER in motion.",
    readingMnemonic: "Seoi2 sounds like 'soy' rising — a splash of WATER (not soy sauce!) catches you by surprise." },

  // ===== Level 11: weather & nature =====
  { hanzi: "風", level: 11, jyutping: ["fung1"], meanings: ["wind"],
    meaningMnemonic: "風 has the insect radical (虫) boxed inside — legend said insects were carried on the WIND.",
    readingMnemonic: "Fung1 sounds like 'fung' (rhymes with 'sung'), high and flat — a gust of WIND whistling past." },
  { hanzi: "雨", level: 11, jyutping: ["jyu5"], meanings: ["rain"],
    meaningMnemonic: "雨 looks like drops falling from a cloud — plainly, RAIN.",
    readingMnemonic: "Jyu5 sounds like 'yu' dipping then rising, same shape as 魚 (fish) — RAIN falling like a school of fish from the sky." },
  { hanzi: "雲", level: 11, jyutping: ["wan4"], meanings: ["cloud"],
    meaningMnemonic: "雲 has the rain radical (雨) on top of 云 — water vapor gathered under the rain, a CLOUD.",
    readingMnemonic: "Wan4 sounds like 'wun' (rhymes with 'won'), low and drawn out — a slow, drifting CLOUD." },
  { hanzi: "雪", level: 11, jyutping: ["syut3"], meanings: ["snow"],
    meaningMnemonic: "雪 has the rain radical (雨) on top of a hand sweeping — sweeping SNOW off the frozen rain.",
    readingMnemonic: "Syut3 sounds like 'shoot' said flat — SNOWballs shooting through the air." },
  { hanzi: "熱", level: 11, jyutping: ["jit6"], meanings: ["hot"],
    meaningMnemonic: "熱 has fire (灬) at the bottom — anything with fire underneath is HOT.",
    readingMnemonic: "Jit6 sounds like 'yit' said low and flat — wipe your brow and sigh 'jit6', it's so HOT." },
  { hanzi: "凍", level: 11, jyutping: ["dung3"], meanings: ["cold"],
    meaningMnemonic: "凍 has the ice radical (冫, two strokes like ice crystals) next to east (東) — even the east wind turns COLD in winter.",
    readingMnemonic: "Dung3 sounds like 'doong' said flat — shiver and go 'dung3', it's freezing COLD." },
  { hanzi: "光", level: 11, jyutping: ["gwong1"], meanings: ["light", "bright"],
    meaningMnemonic: "光 shows a flame sitting on top of a person — carrying fire, radiating LIGHT.",
    readingMnemonic: "Gwong1 sounds like 'gwong' (rhymes with 'long'), high and flat — a BRIGHT light shining wide." },
  { hanzi: "暗", level: 11, jyutping: ["am3"], meanings: ["dark"],
    meaningMnemonic: "暗 has the sun radical (日) next to 音 (sound) — when the sun goes quiet and hides, it turns DARK.",
    readingMnemonic: "Am3 sounds like 'um' said flat — feeling your way through a DARK room going 'am... am...'" },
  { hanzi: "落", level: 11, jyutping: ["lok6"], meanings: ["to fall", "to go down"],
    meaningMnemonic: "落 has the grass radical (艹) on top of 洛 — leaves FALLING DOWN off the plant.",
    readingMnemonic: "Lok6 sounds like 'lock' said low and flat — something FALLS and lands with a low 'lok' thud." },

  // ===== Level 12: transport & movement =====
  { hanzi: "車", level: 12, jyutping: ["ce1"], meanings: ["car", "vehicle"],
    meaningMnemonic: "車 is a simple picture of a CART/CAR seen from above, wheels and axle included.",
    readingMnemonic: "Ce1 sounds like 'che' said high and flat — the screech of a CAR's tires, sharp and high." },
  { hanzi: "船", level: 12, jyutping: ["syun4"], meanings: ["boat"],
    meaningMnemonic: "船 has the boat radical (舟) on the left — plainly, a BOAT.",
    readingMnemonic: "Syun4 sounds like 'shwun', low and drawn out — a BOAT rocking slowly on the waves." },
  { hanzi: "站", level: 12, jyutping: ["zaam6"], meanings: ["station", "stop"],
    meaningMnemonic: "站 has the stand radical (立) next to 占 — a place where you STAND and wait, a STATION.",
    readingMnemonic: "Zaam6 sounds like 'jarm' said low and flat — the low, final announcement calling out your STOP." },
  { hanzi: "路", level: 12, jyutping: ["lou6"], meanings: ["road"],
    meaningMnemonic: "路 has the foot radical (足) on the left — you walk with your foot along the ROAD.",
    readingMnemonic: "Lou6 sounds like 老 (lou5, old) but lower and flatter — an old, well-worn ROAD." },
  { hanzi: "行", level: 12, jyutping: ["haang4"], meanings: ["to walk"],
    meaningMnemonic: "行 looks like a crossroads seen from above — a path made for WALKING.",
    readingMnemonic: "Haang4 sounds like 'hung' with an 'a', low and drawn out — the slow, steady pace of someone WALKING." },
  { hanzi: "搭", level: 12, jyutping: ["daap3"], meanings: ["to take (transport)", "to ride"],
    meaningMnemonic: "搭 has the hand radical (扌) next to 荅 — reaching a hand out to grab hold and hop on, to RIDE.",
    readingMnemonic: "Daap3 sounds like 'dap' said flat — hop on board with a quick 'daap!' and TAKE the ride." },
  { hanzi: "到", level: 12, jyutping: ["dou3"], meanings: ["to arrive"],
    meaningMnemonic: "到 has the knife/blade radical (刂) next to 至 (to reach) — reaching your destination right on the point, to ARRIVE.",
    readingMnemonic: "Dou3 sounds like 'doe' said flat — 'dou3!', the flat announcement that you've ARRIVED." },
  { hanzi: "返", level: 12, jyutping: ["faan1"], meanings: ["to return"],
    meaningMnemonic: "返 has the walk radical (辶) next to 反 (reverse) — walking in REVERSE, back the way you came, to RETURN.",
    readingMnemonic: "Faan1 sounds like 'fan' (as in a fan), high and flat — turning back around like a spinning FAN to RETURN." },

  // ===== Level 13: emotions =====
  { hanzi: "愛", level: 13, jyutping: ["ngoi3"], meanings: ["love"],
    meaningMnemonic: "愛 has the heart radical (心) tucked in the middle — right at the center of the character, and at the center of LOVE.",
    readingMnemonic: "Ngoi3 sounds like 'noy' said flat — cooing 'ngoi3' softly, full of LOVE." },
  { hanzi: "鍾", level: 13, jyutping: ["zung1"], meanings: ["(used in 鍾意, to like)"],
    meaningMnemonic: "鍾 has the metal radical (釒) next to 重 (heavy) — a heavy metal bell, historically also a surname, but today mostly known from 鍾意 meaning TO LIKE.",
    readingMnemonic: "Zung1 sounds just like 中 (zung1, middle) — this word hits right in the middle of your heart, meaning you LIKE it." },
  { hanzi: "意", level: 13, jyutping: ["ji3"], meanings: ["meaning", "idea"],
    meaningMnemonic: "意 has the heart radical (心) at the bottom under sound (音) — the feeling behind your words, the MEANING or IDEA.",
    readingMnemonic: "Ji3 sounds like 'yee' said flat — nodding 'ji3, ji3' as you get the IDEA." },
  { hanzi: "怕", level: 13, jyutping: ["paa3"], meanings: ["afraid"],
    meaningMnemonic: "怕 has the heart radical (忄) next to white (白) — your face goes pale/white when you're AFRAID.",
    readingMnemonic: "Paa3 sounds like 'pa' said flat — a short, AFRAID gasp: 'pa!'" },
  { hanzi: "嬲", level: 13, jyutping: ["nau1"], meanings: ["angry"],
    meaningMnemonic: "嬲 is one woman (女) squeezed between two men (男男) — no wonder everyone involved is ANGRY.",
    readingMnemonic: "Nau1 sounds like 'now', high and flat — stomping your foot NOW because you're ANGRY." },
  { hanzi: "喊", level: 13, jyutping: ["haam3"], meanings: ["to cry"],
    meaningMnemonic: "喊 has the mouth radical (口) next to 咸 — opening your mouth wide and wailing, to CRY.",
    readingMnemonic: "Haam3 sounds like 'harm' said flat — 'no harm done', you say, still sniffling from crying." },
  { hanzi: "笑", level: 13, jyutping: ["siu3"], meanings: ["to laugh", "to smile"],
    meaningMnemonic: "笑 has the bamboo radical (⺮) on top — bamboo bending in the wind looks like it's bent double LAUGHING.",
    readingMnemonic: "Siu3 sounds like 'shew' said flat — a light, breezy 'siu3' as you SMILE." },
  { hanzi: "驚", level: 13, jyutping: ["geng1"], meanings: ["scared"],
    meaningMnemonic: "驚 has the horse radical (馬) at the bottom — a horse spooked and rearing up, SCARED.",
    readingMnemonic: "Geng1 sounds like 'gang', high and flat — a whole gang jumping back, SCARED." },

  // ===== Level 14: money & possession =====
  { hanzi: "錢", level: 14, jyutping: ["cin2"], meanings: ["money"],
    meaningMnemonic: "錢 has the metal radical (釒) next to two spears (戔) — coins made of metal, fought over: MONEY.",
    readingMnemonic: "Cin2 sounds like 'chin' rising — rubbing your chin and asking 'cin2? How much MONEY?'" },
  { hanzi: "平", level: 14, jyutping: ["peng4"], meanings: ["cheap"],
    meaningMnemonic: "平 looks like a balance scale sitting level — a fair, level, CHEAP price.",
    readingMnemonic: "Peng4 sounds like 'peng' (rhymes with 'sang'), low and drawn out — a low, CHEAP price tag." },
  { hanzi: "貴", level: 14, jyutping: ["gwai3"], meanings: ["expensive"],
    meaningMnemonic: "貴 has the shell/money radical (貝) at the bottom — piles of money needed for something EXPENSIVE.",
    readingMnemonic: "Gwai3 sounds like 'gwhy' said flat — gasping 'gwai3!' at how EXPENSIVE it is." },
  { hanzi: "件", level: 14, jyutping: ["gin6"], meanings: ["measure word (items, clothes)"],
    meaningMnemonic: "件 has the person radical (亻) next to cow (牛) — a person's belongings counted one by one, the measure word for ITEMS.",
    readingMnemonic: "Gin6 sounds like 'gin' said low and flat — counting out 'gin6, gin6' one ITEM at a time." },
  { hanzi: "塊", level: 14, jyutping: ["faai3"], meanings: ["measure word (chunks, dollars)"],
    meaningMnemonic: "塊 has the earth radical (土) next to 鬼 (ghost) — a solid CHUNK of earth; also the everyday word for a dollar, like saying 'a buck'.",
    readingMnemonic: "Same sound as 快 (faai3, fast) — money changes hands FAST, one CHUNK/dollar at a time." },
  { hanzi: "蚊", level: 14, jyutping: ["man1"], meanings: ["dollar (colloquial)"],
    meaningMnemonic: "蚊 has the insect radical (虫) next to text (文) — literally 'mosquito', borrowed purely for its sound as everyday slang for a DOLLAR.",
    readingMnemonic: "Man1 sounds exactly like 'mun', high and flat — one buzzing mosquito, one DOLLAR." },
  { hanzi: "使", level: 14, jyutping: ["sai2"], meanings: ["to spend", "to use", "to need to"],
    meaningMnemonic: "使 has the person radical (亻) next to an official seal (吏) — a person given the authority to USE resources.",
    readingMnemonic: "Sai2 sounds like 'sigh' rising — sighing 'sai2?' while wondering whether you really NEED TO spend it." },
  { hanzi: "找", level: 14, jyutping: ["zaau2"], meanings: ["to give change"],
    meaningMnemonic: "找 has the hand radical (扌) next to 戈 (spear) — digging a hand into the register to hand back CHANGE.",
    readingMnemonic: "Zaau2 sounds like 'jow' rising — the cashier asks 'zaau2?' while counting out your CHANGE." },
  { hanzi: "有", level: 14, jyutping: ["jau5"], meanings: ["to have", "there is"],
    meaningMnemonic: "有 shows a hand (ナ) holding a piece of meat (月) — if you're holding meat in hand, you HAVE something.",
    readingMnemonic: "Jau5 sounds like 'yow' dipping then rising — holding something up and going 'jau5! I HAVE it!'" },
  { hanzi: "冇", level: 14, jyutping: ["mou5"], meanings: ["to not have", "there isn't"],
    meaningMnemonic: "冇 is 有 (to have) with the middle scooped hollow — literally 'have' with nothing left inside: TO NOT HAVE.",
    readingMnemonic: "Mou5 sounds like 'mo' dipping then rising — patting your empty pockets and going 'mou5... nothing.'" },

  // ===== Level 15: school & work =====
  { hanzi: "工", level: 15, jyutping: ["gung1"], meanings: ["work", "labor"],
    meaningMnemonic: "工 looks like a simple tool, a chisel or a plane — the tool of manual WORK.",
    readingMnemonic: "Gung1 sounds like 'gung' (rhymes with 'sung'), high and flat — the steady clang of WORK, high and repetitive." },
  { hanzi: "課", level: 15, jyutping: ["fo3"], meanings: ["lesson", "class"],
    meaningMnemonic: "課 has the speech radical (言) next to fruit (果) — a spoken LESSON, bearing fruit if you pay attention.",
    readingMnemonic: "Fo3 sounds like 'faw' said flat — the flat drone of a teacher's voice through a LESSON." },
  { hanzi: "考", level: 15, jyutping: ["haau2"], meanings: ["to test", "exam"],
    meaningMnemonic: "考 looks like an old person (老-like top) leaning to examine something closely — to TEST, to EXAMINE.",
    readingMnemonic: "Haau2 sounds like 'how' rising — sweating through an EXAM and asking 'haau2? How did I do?'" },
  { hanzi: "忙", level: 15, jyutping: ["mong4"], meanings: ["busy"],
    meaningMnemonic: "忙 has the heart radical (忄) next to disappear (亡) — when you're BUSY, your heart (free time) seems to disappear.",
    readingMnemonic: "Mong4 sounds like 'mong' (rhymes with 'song'), low and drawn out — sighing 'mong4', so BUSY, so tired." },
  { hanzi: "得", level: 15, jyutping: ["dak1"], meanings: ["to get", "can", "OK"],
    meaningMnemonic: "得 has the walk radical (彳) next to a hand grabbing a shell (貝-like) — walking away having GOTTEN what you came for.",
    readingMnemonic: "Dak1 sounds like 'duck', high and flat — a thumbs-up 'dak1!', meaning OK, you CAN do it." },
  { hanzi: "識", level: 15, jyutping: ["sik1"], meanings: ["to know (a skill, fact, or person)"],
    meaningMnemonic: "識 has the speech radical (言) next to 哉/戠 — you can only speak knowledgeably about what you KNOW.",
    readingMnemonic: "Same sound as 色 (sik1, color) — you KNOW a subject inside and out, in full COLOR detail." },
  { hanzi: "想", level: 15, jyutping: ["soeng2"], meanings: ["to want", "to think"],
    meaningMnemonic: "想 has the heart radical (心) at the bottom under 相 (mutual/look) — looking at something with your heart, you WANT it or THINK about it.",
    readingMnemonic: "Soeng2 sounds like the rising version of 上 (soeng5) — your thoughts rising up, you WANT, you THINK." },
  { hanzi: "讀", level: 15, jyutping: ["duk6"], meanings: ["to read", "to study"],
    meaningMnemonic: "讀 has the speech radical (言) next to 賣-like sell shape — reading words aloud as if selling the story, to READ/STUDY.",
    readingMnemonic: "Duk6 sounds like 'duck' said low and flat — quietly reading, head DUCKed down over a book." },
  { hanzi: "書", level: 15, jyutping: ["syu1"], meanings: ["book"],
    meaningMnemonic: "書 looks like a hand holding a brush over layered pages — writing out the pages of a BOOK.",
    readingMnemonic: "Syu1 sounds like 'shoe', high and flat — a BOOK so old and worn it's falling apart like an old SHOE." },

  // ===== Level 16: numbers & time units =====
  { hanzi: "百", level: 16, jyutping: ["baak3"], meanings: ["hundred"],
    meaningMnemonic: "百 has one (一) on top of white (白) — a HUNDRED blank, white pages stacked up.",
    readingMnemonic: "Same sound as 白 (baak6) but flatter — a HUNDRED white sheets of paper." },
  { hanzi: "千", level: 16, jyutping: ["cin1"], meanings: ["thousand"],
    meaningMnemonic: "千 looks like the character 十 (ten) with an extra stroke — ten tens of tens, a THOUSAND.",
    readingMnemonic: "Same sound as 錢 (cin2, money) but higher and flatter — a THOUSAND dollars." },
  { hanzi: "萬", level: 16, jyutping: ["maan6"], meanings: ["ten thousand"],
    meaningMnemonic: "萬 originally pictured a scorpion — swarming in uncountable numbers, TEN THOUSAND of them.",
    readingMnemonic: "Same sound as 慢 (maan6, slow) — it would take a long, SLOW time to count to TEN THOUSAND." },
  { hanzi: "半", level: 16, jyutping: ["bun3"], meanings: ["half"],
    meaningMnemonic: "半 shows a cow (牛-like) split down the middle by a single stroke — cut right in HALF.",
    readingMnemonic: "Bun3 sounds like 'boon' said flat — split a bun in HALF and share it." },
  { hanzi: "鐘", level: 16, jyutping: ["zung1"], meanings: ["clock", "o'clock"],
    meaningMnemonic: "鐘 has the metal radical (釒) next to 童 (child) — a metal bell that chimes the hour, a CLOCK.",
    readingMnemonic: "Same sound as 中/鍾 (zung1) — right in the middle of the CLOCK face, high and flat." },
  { hanzi: "分", level: 16, jyutping: ["fan1"], meanings: ["minute", "to divide"],
    meaningMnemonic: "分 shows a knife (刀) splitting something into two parts — DIVIDING time into MINUTES.",
    readingMnemonic: "Fan1 sounds like 'fun', high and flat — time flies when you're having FUN, MINUTE by MINUTE." },
  { hanzi: "秒", level: 16, jyutping: ["miu5"], meanings: ["second (time)"],
    meaningMnemonic: "秒 has the grain radical (禾) next to small (少) — the smallest sliver of grain, the smallest unit of time, a SECOND.",
    readingMnemonic: "Miu5 sounds like 'meow' dipping then rising — a cat's SECOND-long meow." },
  { hanzi: "遲", level: 16, jyutping: ["ci4"], meanings: ["late"],
    meaningMnemonic: "遲 has the walk radical (辶) next to 犀 (rhino) — walking as slow as a rhino, always LATE.",
    readingMnemonic: "Ci4 sounds like 'chee', low and drawn out — dragging your feet, arriving LATE." },

  // ===== Level 17: house & objects =====
  { hanzi: "檯", level: 17, jyutping: ["toi2"], meanings: ["table"],
    meaningMnemonic: "檯 has the wood radical (木) next to a platform shape (臺) — a wooden platform to eat and work on, a TABLE.",
    readingMnemonic: "Toi2 sounds like 'toy' rising — toys scattered all over the TABLE." },
  { hanzi: "椅", level: 17, jyutping: ["ji2"], meanings: ["chair"],
    meaningMnemonic: "椅 has the wood radical (木) next to 奇 (strange) — a strangely-shaped piece of wood you sit on, a CHAIR.",
    readingMnemonic: "Ji2 sounds like 'yee' rising — settling into a CHAIR with a satisfied 'ji2.'" },
  { hanzi: "門", level: 17, jyutping: ["mun4"], meanings: ["door"],
    meaningMnemonic: "門 is a simple picture of two DOOR panels swinging on hinges.",
    readingMnemonic: "Mun4 sounds like 'moon', low and drawn out — a round MOON-shaped window cut into the DOOR." },
  { hanzi: "窗", level: 17, jyutping: ["coeng1"], meanings: ["window"],
    meaningMnemonic: "窗 has the roof/cave radical (穴) on top — a hole cut into the wall under the roof, a WINDOW.",
    readingMnemonic: "Coeng1 sounds like 'churng', high and flat — a breeze humming through the open WINDOW." },
  { hanzi: "燈", level: 17, jyutping: ["dang1"], meanings: ["lamp", "light"],
    meaningMnemonic: "燈 has the fire radical (火) next to 登 (to ascend) — fire raised up on a stand, a LAMP.",
    readingMnemonic: "Dang1 sounds like 'dung' (rhymes with 'sung'), high and flat — flick the switch, 'dang1!', the LAMP turns on." },
  { hanzi: "電", level: 17, jyutping: ["din6"], meanings: ["electricity", "electric"],
    meaningMnemonic: "電 has the rain radical (雨) over 电 (lightning) — lightning falling from the rain clouds, raw ELECTRICITY.",
    readingMnemonic: "Din6 sounds like 'din' said low and flat — the low hum and DIN of an ELECTRIC current." },
  { hanzi: "話", level: 17, jyutping: ["waa6"], meanings: ["to say", "word", "speech"],
    meaningMnemonic: "話 has the speech radical (言) next to tongue (舌) — using your tongue to SAY WORDS.",
    readingMnemonic: "Waa6 sounds like 'wah' said low and flat — a flat, matter-of-fact 'waa6' as you SAY something." },
  { hanzi: "機", level: 17, jyutping: ["gei1"], meanings: ["machine"],
    meaningMnemonic: "機 has the wood radical (木) next to 幾 (how many/several) — a wooden contraption built from several moving parts, a MACHINE.",
    readingMnemonic: "Gei1 sounds like 'gay' said high and flat — the high whir of a MACHINE running." },

  // ===== Level 18: health =====
  { hanzi: "病", level: 18, jyutping: ["beng6"], meanings: ["sick", "illness"],
    meaningMnemonic: "病 has the sickness radical (疒, a person lying on a sickbed) wrapped around 丙 — plainly, SICKNESS.",
    readingMnemonic: "Beng6 sounds like 'bang' said low and flat — you got 'bang'ed with an ILLNESS, low and heavy." },
  { hanzi: "瞓", level: 18, jyutping: ["fan3"], meanings: ["to sleep"],
    meaningMnemonic: "瞓 has the eye radical (目) next to 訓 — closing your eyes to SLEEP.",
    readingMnemonic: "Fan3 sounds like 'fun' said flat — dreams are FUN, which is why you SLEEP." },
  { hanzi: "醫", level: 18, jyutping: ["ji1"], meanings: ["medicine", "doctor (root)"],
    meaningMnemonic: "醫 has the wine-jar radical (酉) at the bottom — medicine was once brewed and stored like wine, the root of MEDICINE.",
    readingMnemonic: "Ji1 sounds like 'yee' said high and flat — a nervous 'ji1' as the DOCTOR walks in." },
  { hanzi: "生", level: 18, jyutping: ["sang1"], meanings: ["to be born", "raw"],
    meaningMnemonic: "生 looks like a plant sprouting up out of the ground — freshly BORN, still RAW and new.",
    readingMnemonic: "Sang1 sounds like 'sung' with an 'a', high and flat — a newBORN's first high-pitched cry." },
  { hanzi: "死", level: 18, jyutping: ["sei2"], meanings: ["to die"],
    meaningMnemonic: "死 has bones (歹) next to a collapsed person (匕) — a person collapsed among the bones, TO DIE.",
    readingMnemonic: "Sei2 sounds just like 四 (sei3, four) but rising — unlucky like the number 4, associated with DEATH in Cantonese culture." },
  { hanzi: "痛", level: 18, jyutping: ["tung3"], meanings: ["pain"],
    meaningMnemonic: "痛 has the sickness radical (疒) wrapped around 甬 — sickness that makes itself known through PAIN.",
    readingMnemonic: "Tung3 sounds like 'tongue' without the 'e', said flat — biting your TONGUE, sharp PAIN." },
  { hanzi: "抖", level: 18, jyutping: ["dau2"], meanings: ["to rest"],
    meaningMnemonic: "抖 has the hand radical (扌) next to 斗 (a measuring scoop) — setting your tools down to REST for a moment.",
    readingMnemonic: "Dau2 sounds like 'dow' rising — flopping down with a tired 'dau2', time to REST." },
  { hanzi: "起", level: 18, jyutping: ["hei2"], meanings: ["to rise", "to get up"],
    meaningMnemonic: "起 has the walk radical (走) next to 己 (self) — pushing yourself up to walk, TO GET UP.",
    readingMnemonic: "Hei2 sounds like 'hey' rising — someone shakes you awake going 'hei2! hei2! GET UP!'" },

  // ===== Level 19: politeness & farewells =====
  { hanzi: "該", level: 19, jyutping: ["goi1"], meanings: ["(used in 唔該, please/thank you)"],
    meaningMnemonic: "該 has the speech radical (言) next to 亥 — the polite words that SHOULD be said; today almost always seen in 唔該, please/thank you.",
    readingMnemonic: "Goi1 sounds like 'goy', high and flat — a quick, polite 'goi1!' to get someone's attention politely." },
  { hanzi: "謝", level: 19, jyutping: ["ze6"], meanings: ["(used in 多謝, thanks)"],
    meaningMnemonic: "謝 has the speech radical (言) next to 射 (to shoot) — words shot straight from the heart in THANKS; seen in 多謝, thank you.",
    readingMnemonic: "Ze6 sounds like 'jeh' said low and flat — a warm, sincere 'ze6' of THANKS." },
  { hanzi: "對", level: 19, jyutping: ["deoi3"], meanings: ["correct", "towards"],
    meaningMnemonic: "對 shows two hands holding up a matching pair — getting it exactly right, CORRECT, facing TOWARDS each other.",
    readingMnemonic: "Deoi3 sounds like 'doy' said flat — a firm nod and 'deoi3!' — that's CORRECT." },
  { hanzi: "住", level: 19, jyutping: ["zyu6"], meanings: ["to live", "to stay"],
    meaningMnemonic: "住 has the person radical (亻) next to 主 (master/host) — a person settled as master of their own home, TO LIVE there.",
    readingMnemonic: "Zyu6 sounds like 'jew' said low and flat — settling down low and staying put, TO LIVE somewhere." },
  { hanzi: "早", level: 19, jyutping: ["zou2"], meanings: ["early", "morning"],
    meaningMnemonic: "早 has the sun radical (日) on top of ten (十) — the sun rising at ten past dawn, EARLY MORNING.",
    readingMnemonic: "Zou2 sounds like 'joe' rising — waking up bright and EARLY with a cheerful 'zou2!'" },
  { hanzi: "晚", level: 19, jyutping: ["maan5"], meanings: ["evening", "late"],
    meaningMnemonic: "晚 has the sun radical (日) next to 免 — the sun excusing itself for the day, sinking into EVENING.",
    readingMnemonic: "Maan5 sounds like 慢/萬 (maan6) but rising — the EVENING stretches on slow and long." },
  { hanzi: "再", level: 19, jyutping: ["zoi3"], meanings: ["again"],
    meaningMnemonic: "再 looks like a stack of firewood with one more log placed on top — doing it once more, AGAIN.",
    readingMnemonic: "Zoi3 sounds like 'joy' said flat — the joy of seeing someone AGAIN." },
  { hanzi: "見", level: 19, jyutping: ["gin3"], meanings: ["to see", "to meet"],
    meaningMnemonic: "見 has the eye radical (目) on top of a person (儿) — a person using their eyes, TO SEE or TO MEET someone.",
    readingMnemonic: "Gin3 sounds like 'gin' said flat — catching a glimpse and going 'gin3! I SEE you!'" },

  // ===== Level 20: grammar & connectors =====
  { hanzi: "如", level: 20, jyutping: ["jyu4"], meanings: ["as", "like"],
    meaningMnemonic: "如 has the woman radical (女) next to mouth (口) — doing exactly AS you're told, LIKE a mirror; seen in 如果, if.",
    readingMnemonic: "Same sound as 魚 (jyu4, fish) — swimming ALONG LIKE a fish following the current." },
  { hanzi: "果", level: 20, jyutping: ["gwo2"], meanings: ["fruit", "result"],
    meaningMnemonic: "果 looks like fruit hanging from a tree — the FRUIT, or figuratively the RESULT of something; seen in 如果, if.",
    readingMnemonic: "Gwo2 sounds like 'gwaw' rising — biting into a piece of FRUIT and going 'gwo2? Is this ripe?'" },
  { hanzi: "就", level: 20, jyutping: ["zau6"], meanings: ["then", "just"],
    meaningMnemonic: "就 has 京 (capital) next to 尤 (especially) — heading especially straight to the capital, right THEN, JUST like that.",
    readingMnemonic: "Zau6 sounds like 'joe' said low and flat — 'zau6', THEN and there, no delay." },
  { hanzi: "都", level: 20, jyutping: ["dou1"], meanings: ["also", "all"],
    meaningMnemonic: "都 has the city radical (阝) next to 者 (person) — everyone in the whole city, ALL of them, ALSO included.",
    readingMnemonic: "Dou1 sounds like 'doe', high and flat — pointing around a whole crowd, 'dou1', ALL of them, ALSO." },
  { hanzi: "先", level: 20, jyutping: ["sin1"], meanings: ["first"],
    meaningMnemonic: "先 has a person (儿) walking ahead of 之-like steps — the person walking out FIRST, ahead of everyone.",
    readingMnemonic: "Sin1 sounds like 'seen', high and flat — the FIRST thing you've SEEN today." },
  { hanzi: "至", level: 20, jyutping: ["zi3"], meanings: ["most", "until"],
    meaningMnemonic: "至 looks like an arrow landing at its farthest point — reaching the very extreme, the MOST, UNTIL the end.",
    readingMnemonic: "Zi3 sounds like 'jee' said flat — stretching all the way UNTIL the very tip, the MOST." },
  { hanzi: "定", level: 20, jyutping: ["ding6"], meanings: ["or (in questions)", "fixed"],
    meaningMnemonic: "定 has the roof radical (宀) over 疋 — a household settled and FIXED in place; also used to mean OR when offering a choice.",
    readingMnemonic: "Ding6 sounds like 'ding' said low and flat — a bell going 'ding6', FIXED and certain, OR is it?" },
  { hanzi: "呀", level: 20, jyutping: ["aa3"], meanings: ["(sentence-final particle)"],
    meaningMnemonic: "呀 has the mouth radical (口) next to 牙 (tooth) — a little sound that slips out through your teeth at the end of a sentence for emphasis.",
    readingMnemonic: "Aa3 is just an open 'aa' said flat — the natural sigh that finishes off a sentence." },

  // Gap-fill: 少 is used inside the level-2 word 多少 but was never given its
  // own entry. Appended here (rather than reordering level 2) so it doesn't
  // shift any existing character ids.
  { hanzi: "少", level: 2, jyutping: ["siu2"], meanings: ["few", "little (in amount)"],
    meaningMnemonic: "少 looks like 小 (small) losing a stroke off the bottom — even less than SMALL, just a FEW.",
    readingMnemonic: "A homophone of 小 (siu2) — FEW and SMALL sound identical in Cantonese, said rising." },
];

module.exports = characters;
