// Starter character set: 81 common Cantonese characters across 8 levels.
// jyutping: array of accepted readings (primary first).
// meanings: array of accepted English answers (primary first).
const characters = [
  // ===== Level 1: numbers & basics =====
  { hanzi: "一", level: 1, jyutping: ["jat1"], meanings: ["one"],
    meaningMnemonic: "一 is a single horizontal stroke — literally one line for the number one.",
    readingMnemonic: "Jat1 sounds like 'yacht' without the 'ch' — picture ONE lonely yacht on the water. Tone 1 is high and flat, like a bored monotone 'jaaat'." },
  { hanzi: "二", level: 1, jyutping: ["ji6"], meanings: ["two"],
    meaningMnemonic: "二 is two horizontal strokes stacked up — two lines for the number two.",
    readingMnemonic: "Ji6 sounds like 'jee' said low and heavy. Tone 6 is low and flat — say 'jee' in the deepest, most bored voice you can for two." },
  { hanzi: "三", level: 1, jyutping: ["saam1"], meanings: ["three"],
    meaningMnemonic: "三 is three horizontal strokes — three lines stacked for the number three.",
    readingMnemonic: "Saam1 sounds like 'sam' (the name). Picture three guys all named Sam standing in a row. Tone 1: high and flat, like calling out 'Saam!' sharply." },
  { hanzi: "人", level: 1, jyutping: ["jan4"], meanings: ["person", "people"],
    meaningMnemonic: "人 looks like a little stick figure of a person walking on two legs.",
    readingMnemonic: "Jan4 sounds like 'yun' as in 'young'. Picture a young PERSON. Tone 4 is low and rising, a relaxed drawn-out 'yuuun'." },
  { hanzi: "大", level: 1, jyutping: ["daai6"], meanings: ["big", "large"],
    meaningMnemonic: "大 looks like a person (人) stretching their arms out wide to show how BIG something is.",
    readingMnemonic: "Daai6 sounds like 'die' said low and heavy — imagine something so BIG it makes you go 'oh, I could die' in a low, flat tone 6 voice." },
  { hanzi: "小", level: 1, jyutping: ["siu2"], meanings: ["small", "little"],
    meaningMnemonic: "小 looks like a tiny thing with two small drops on either side — everything about it is SMALL.",
    readingMnemonic: "Siu2 sounds like 'shew' (as in 'shoo, little fly'). Tone 2 rises like a question: 'siu2?' — small and curious." },
  { hanzi: "中", level: 1, jyutping: ["zung1"], meanings: ["middle", "center"],
    meaningMnemonic: "中 is a box with a line straight through its MIDDLE, like an arrow hitting dead-center.",
    readingMnemonic: "Zung1 sounds like 'jung' as in Carl Jung. Tone 1 high and flat: a dart flying straight and level into the CENTER of the target — 'zung!'" },
  { hanzi: "好", level: 1, jyutping: ["hou2"], meanings: ["good", "well"],
    meaningMnemonic: "好 is a woman (女) next to her child (子) — a mother with her child is a GOOD, wholesome scene.",
    readingMnemonic: "Hou2 sounds like 'how' with a rising tone, like asking 'how good is it?' — and the rising pitch answers: pretty GOOD!" },
  { hanzi: "我", level: 1, jyutping: ["ngo5"], meanings: ["I", "me"],
    meaningMnemonic: "我 is a picture of a hand holding a spear — 'this spear is mine, I am the one holding it.'",
    readingMnemonic: "Ngo5 sounds like 'ngoh' — like the sound you make pointing at your own chest saying 'me? Ngoh!' Tone 5 dips low then rises." },
  { hanzi: "你", level: 1, jyutping: ["nei5"], meanings: ["you"],
    meaningMnemonic: "你 is a person (亻) next to 尔 — pointing at the person standing right there: YOU.",
    readingMnemonic: "Nei5 sounds like 'nay' dipping then rising, like pointing at someone and going 'nei5? Yeah, YOU.'" },

  // ===== Level 2: family & basic adjectives =====
  { hanzi: "四", level: 2, jyutping: ["sei3"], meanings: ["four"],
    meaningMnemonic: "四 is a box with legs splayed inside — four corners for the number four.",
    readingMnemonic: "Sei3 sounds like 'say'. Tone 3 is mid and flat: say 'say' flatly, four times if you like." },
  { hanzi: "五", level: 2, jyutping: ["ng5"], meanings: ["five"],
    meaningMnemonic: "五 looks like an X crossed inside a box — count the five lines that make up the character.",
    readingMnemonic: "Ng5 is just a nasal 'mmm' sound dipping then rising — hum 'ng5' while holding up five fingers." },
  { hanzi: "六", level: 2, jyutping: ["luk6"], meanings: ["six"],
    meaningMnemonic: "六 looks like a little roof over two legs — a house numbered SIX.",
    readingMnemonic: "Luk6 sounds like 'luk' as in 'look'. Tone 6 low and flat: 'luk, there's six of them.'" },
  { hanzi: "女", level: 2, jyutping: ["neoi5"], meanings: ["woman", "female"],
    meaningMnemonic: "女 is a simple sketch of a woman kneeling gracefully — the character for WOMAN.",
    readingMnemonic: "Neoi5 sounds like 'noy' dipping then rising, like saying 'noy' with an eyebrow raised — a WOMAN raising an eyebrow at you." },
  { hanzi: "男", level: 2, jyutping: ["naam4"], meanings: ["man", "male"],
    meaningMnemonic: "男 is a rice field (田) over strength (力) — a MAN out working the field with his strength.",
    readingMnemonic: "Naam4 sounds like 'naam' as in Vietnam. A strong MAN from 'Naam', said low and drawn out for tone 4." },
  { hanzi: "爸", level: 2, jyutping: ["baa1"], meanings: ["dad", "father"],
    meaningMnemonic: "爸 has father (父) on top of a wave-like base — picture DAD as the head of the household.",
    readingMnemonic: "Baa1 is exactly like 'baa' — the very first sound a baby makes for DAD, high and flat." },
  { hanzi: "媽", level: 2, jyutping: ["maa1"], meanings: ["mom", "mother"],
    meaningMnemonic: "媽 has woman (女) next to horse (馬) — MOM, who works as hard and fast as a horse.",
    readingMnemonic: "Maa1 is exactly like 'maa' — the very first sound a baby makes for MOM, high and flat." },
  { hanzi: "老", level: 2, jyutping: ["lou5"], meanings: ["old (people)"],
    meaningMnemonic: "老 looks like a bent-over figure leaning on a cane — an OLD person walking slowly.",
    readingMnemonic: "Lou5 sounds like 'low' dipping then rising — an OLD man's voice, low and creaky." },
  { hanzi: "多", level: 2, jyutping: ["do1"], meanings: ["many", "much"],
    meaningMnemonic: "多 is two evening (夕) symbols stacked — two nights of the same thing means it happens a lot, MANY times.",
    readingMnemonic: "Do1 sounds exactly like the word 'dough' — imagine MANY, MANY balls of dough piled high, said flat and high." },
  { hanzi: "細", level: 2, jyutping: ["sai3"], meanings: ["small (colloquial)", "little"],
    meaningMnemonic: "細 is silk thread (糸) next to a field (田) — even a tiny thread in a huge field looks SMALL.",
    readingMnemonic: "Sai3 sounds like 'sigh' without the 'gh'. Say 'sai' flatly with a little sigh — something so SMALL it's barely worth noticing." },

  // ===== Level 3: more numbers & time =====
  { hanzi: "七", level: 3, jyutping: ["cat1"], meanings: ["seven"],
    meaningMnemonic: "七 looks like a bent number 7 — the number SEVEN, plain and simple.",
    readingMnemonic: "Cat1 sounds exactly like 'cat'. Picture SEVEN cats in a row, said high and flat." },
  { hanzi: "八", level: 3, jyutping: ["baat3"], meanings: ["eight"],
    meaningMnemonic: "八 looks like two strokes splitting apart — EIGHT, a lucky number in Cantonese culture.",
    readingMnemonic: "Baat3 sounds like 'baht' (the Thai currency) said flatly. Imagine paying EIGHT baht for something lucky." },
  { hanzi: "九", level: 3, jyutping: ["gau2"], meanings: ["nine"],
    meaningMnemonic: "九 looks like a hook or a claw reaching up — NINE lives of a cat clawing at you.",
    readingMnemonic: "Gau2 sounds like 'gow' rising, close to the English word 'gow' in 'go'. A rising 'gau2?' as if counting up to NINE." },
  { hanzi: "十", level: 3, jyutping: ["sap6"], meanings: ["ten"],
    meaningMnemonic: "十 is a simple cross — two strokes crossing to make TEN, like a perfect ten out of ten score marked with an X-turned-plus.",
    readingMnemonic: "Sap6 sounds like 'sup' said low and flat, like slurping soup TEN times: 'sap, sap, sap...'" },
  { hanzi: "日", level: 3, jyutping: ["jat6"], meanings: ["day", "sun"],
    meaningMnemonic: "日 is a little window with a line through the middle — a picture of the SUN, and by extension a DAY.",
    readingMnemonic: "Jat6 sounds like 'yut' said low and flat — a long, low 'yut' as the SUN sets low on the horizon at the end of the DAY." },
  { hanzi: "月", level: 3, jyutping: ["jyut6"], meanings: ["month", "moon"],
    meaningMnemonic: "月 is a crescent shape with two strokes inside — a picture of the MOON, and by extension a MONTH (one moon cycle).",
    readingMnemonic: "Jyut6 sounds like 'yuet' said low and flat — round your lips like you're about to whistle at the MOON, then drop your voice low." },
  { hanzi: "年", level: 3, jyutping: ["nin4"], meanings: ["year"],
    meaningMnemonic: "年 looks like a stalk of grain being carried home — a full harvest happens once a YEAR.",
    readingMnemonic: "Nin4 sounds like 'neen' drawn out low, like a long 'nnniiin' — one whole YEAR feels like it drags on forever." },
  { hanzi: "時", level: 3, jyutping: ["si4"], meanings: ["time", "hour"],
    meaningMnemonic: "時 has sun (日) next to a temple/measure (寺) — measuring the sun's position tells you the TIME.",
    readingMnemonic: "Si4 sounds like 'see' drawn out low. You 'see' the clock to check the TIME, low and calm." },
  { hanzi: "天", level: 3, jyutping: ["tin1"], meanings: ["sky", "day"],
    meaningMnemonic: "天 is a big person (大) with a line over their head — the SKY stretches above even the biggest person; also used for 'day'.",
    readingMnemonic: "Tin1 sounds exactly like 'tin'. Picture a TIN roof with the open SKY visible through a hole in it, said high and flat." },
  { hanzi: "今", level: 3, jyutping: ["gam1"], meanings: ["now", "this (time)"],
    meaningMnemonic: "今 looks like a lid closing down tightly on the present moment — right NOW, this instant.",
    readingMnemonic: "Gam1 sounds like 'gum' said high and flat — chew that gum right NOW, this very moment." },

  // ===== Level 4: common verbs =====
  { hanzi: "食", level: 4, jyutping: ["sik6"], meanings: ["eat"],
    meaningMnemonic: "食 looks like a covered dish sitting on a stand — a bowl of food ready to be EATEN.",
    readingMnemonic: "Sik6 sounds like 'sick' said low and flat — you'll feel SICK if you EAT too much, low and heavy tone." },
  { hanzi: "飲", level: 4, jyutping: ["jam2"], meanings: ["drink"],
    meaningMnemonic: "飲 has the food radical (食) next to a person opening their mouth wide (欠) — opening your mouth wide to DRINK.",
    readingMnemonic: "Jam2 sounds like 'yum' rising, as in 'yum, this drink is nice!' — rising tone like a happy question." },
  { hanzi: "去", level: 4, jyutping: ["heoi3"], meanings: ["go"],
    meaningMnemonic: "去 shows a person (土-like shape) stepping out and away from a doorway (厶) — heading out, about to GO.",
    readingMnemonic: "Heoi3 sounds like 'huoy' said flatly, close to calling out 'hoi!' as you GO out the door — mid, flat tone." },
  { hanzi: "嚟", level: 4, jyutping: ["lai4"], meanings: ["come"],
    meaningMnemonic: "嚟 is a mouth (口) shouting the word for COME — this is a spoken Cantonese character, literally built to be said out loud calling someone over.",
    readingMnemonic: "Lai4 sounds like 'lie' said low and drawn out — 'laaaai' — like calling someone from across the room to COME here." },
  { hanzi: "睇", level: 4, jyutping: ["tai2"], meanings: ["look", "watch", "see"],
    meaningMnemonic: "睇 has the eye radical (目) — of course a character with an eye in it means to LOOK or WATCH.",
    readingMnemonic: "Tai2 sounds like 'tie' rising, like asking 'tie2? Can you see the tie I'm wearing?' — rising, questioning tone as you LOOK." },
  { hanzi: "聽", level: 4, jyutping: ["teng1"], meanings: ["listen", "hear"],
    meaningMnemonic: "聽 has the ear radical (耳) tucked inside — packed with ears, so naturally it means to LISTEN.",
    readingMnemonic: "Teng1 sounds like 'tang' as in orange Tang drink, high and flat — LISTEN closely, high and clear." },
  { hanzi: "講", level: 4, jyutping: ["gong2"], meanings: ["speak", "say", "talk"],
    meaningMnemonic: "講 has the speech radical (言) on the left — anything with 言 involves words, here meaning to SPEAK.",
    readingMnemonic: "Gong2 sounds like 'gong' rising, like hitting a gong and asking a question with it — SPEAK up like a rising gong." },
  { hanzi: "做", level: 4, jyutping: ["zou6"], meanings: ["do", "make"],
    meaningMnemonic: "做 has the person radical (亻) next to a character meaning 'made' — a person DOING or MAKING something.",
    readingMnemonic: "Zou6 sounds like 'joe' said low and flat — 'Joe, just DO it,' said in a low, flat, no-nonsense voice." },
  { hanzi: "買", level: 4, jyutping: ["maai5"], meanings: ["buy"],
    meaningMnemonic: "買 has the shell/money radical (貝) at the bottom — money changing hands to BUY something.",
    readingMnemonic: "Maai5 sounds like 'my' dipping then rising — 'is this MY purchase?' dipping down then rising in pitch as you BUY it." },
  { hanzi: "賣", level: 4, jyutping: ["maai6"], meanings: ["sell"],
    meaningMnemonic: "賣 also has the money radical (貝) at the bottom, with 士 and 買-like elements on top — goods stacked up on top of money, ready to SELL.",
    readingMnemonic: "Maai6 sounds just like 買 (maai5) but low and flat instead of dipping-rising — same sound family, but SELLING is the low, flat, final version of buying." },

  // ===== Level 5: places & directions =====
  { hanzi: "屋", level: 5, jyutping: ["uk1"], meanings: ["house"],
    meaningMnemonic: "屋 has the roof radical (尸) over 至 — a roof over your head means a HOUSE.",
    readingMnemonic: "Uk1 sounds like a short, sharp 'uk!' — the sound you'd make bonking your head on the low doorway of a tiny HOUSE, high and flat." },
  { hanzi: "企", level: 5, jyutping: ["kei5"], meanings: ["stand"],
    meaningMnemonic: "企 has a person (人) standing on top of stop (止) — a person planted firmly, STANDING. Combined with 屋 it forms 屋企 (home) — the place where you stand and stay.",
    readingMnemonic: "Kei5 sounds like 'kay' dipping then rising — STAND up straight and say 'kei5!' with confidence." },
  { hanzi: "學", level: 5, jyutping: ["hok6"], meanings: ["study", "learn"],
    meaningMnemonic: "學 shows two hands over a child (子) under a roof — hands guiding a child to STUDY and LEARN.",
    readingMnemonic: "Hok6 sounds like 'hock' said low and flat — hunker down and STUDY, low and serious." },
  { hanzi: "校", level: 5, jyutping: ["haau6"], meanings: ["school (institution)"],
    meaningMnemonic: "校 has the wood radical (木) next to a mixing/comparing element — wooden desks lined up, the SCHOOL building.",
    readingMnemonic: "Haau6 sounds like 'how' said low and flat — 'haau6, that's the SCHOOL,' pointed out in a flat, matter-of-fact tone." },
  { hanzi: "街", level: 5, jyutping: ["gaai1"], meanings: ["street"],
    meaningMnemonic: "街 has the 'walk' radical (彳/亍) on both sides of 圭 — walking paths on both sides, a STREET.",
    readingMnemonic: "Gaai1 sounds like 'guy' said high and flat — a GUY walking down the STREET, high and flat tone." },
  { hanzi: "市", level: 5, jyutping: ["si5"], meanings: ["market", "city"],
    meaningMnemonic: "市 looks like a flag flying over a stall — a flag marking a busy MARKET or CITY square.",
    readingMnemonic: "Si5 sounds like 'see' dipping then rising — 'si5? Do you SEE the MARKET over there?'" },
  { hanzi: "上", level: 5, jyutping: ["soeng5", "soeng6"], meanings: ["up", "above", "to go up"],
    meaningMnemonic: "上 is a short stroke sitting ABOVE a long baseline — clearly marking something that is UP or above.",
    readingMnemonic: "Soeng5 dips then rises — literally rising in pitch as you go UP. As a plain position word it flattens to soeng6, low and flat, like something already sitting up there." },
  { hanzi: "下", level: 5, jyutping: ["haa6"], meanings: ["down", "below"],
    meaningMnemonic: "下 is a short stroke sitting BELOW a long baseline — the mirror image of 上, marking DOWN or below.",
    readingMnemonic: "Haa6 sounds like 'haa' said low and flat — a low sigh 'haaa' as you slump DOWN." },
  { hanzi: "左", level: 5, jyutping: ["zo2"], meanings: ["left"],
    meaningMnemonic: "左 has the 'work' radical (工) under a hand-like stroke — many people naturally work with their LEFT hand guiding tools.",
    readingMnemonic: "Zo2 sounds like 'joe' rising — 'zo2? Is it to the LEFT?' asked with a rising, uncertain tone." },
  { hanzi: "右", level: 5, jyutping: ["jau6"], meanings: ["right"],
    meaningMnemonic: "右 has a mouth (口) under a hand-like stroke — pointing with your hand near your mouth to say 'it's to the RIGHT.'",
    readingMnemonic: "Jau6 sounds like 'yow' said low and flat — pointing firmly and flatly: 'jau6, RIGHT there.'" },

  // ===== Level 6: question words & particles =====
  { hanzi: "邊", level: 6, jyutping: ["bin1"], meanings: ["side", "which", "where"],
    meaningMnemonic: "邊 has the 'walk' radical (辶) leading off to the SIDE — wandering off to one side, asking WHICH way or WHERE.",
    readingMnemonic: "Bin1 sounds exactly like 'bin' (a trash bin), high and flat — 'bin1? Which BIN is it in?'" },
  { hanzi: "個", level: 6, jyutping: ["go3"], meanings: ["measure word (general)", "individual"],
    meaningMnemonic: "個 has the person radical (亻) next to 固 (solid) — a solid, single, countable INDIVIDUAL — the all-purpose measure word.",
    readingMnemonic: "Go3 sounds exactly like 'go', said mid and flat — 'go3' one at a time, counting off each individual item: go, go, go." },
  { hanzi: "乜", level: 6, jyutping: ["mat1"], meanings: ["what (colloquial)"],
    meaningMnemonic: "乜 is a squiggly, confused-looking little shape — it looks like a shrug, which is exactly the reaction to 'WHAT?'",
    readingMnemonic: "Mat1 sounds like 'mat' (a floor mat), high and flat — 'mat1? WHAT mat is this?'" },
  { hanzi: "點", level: 6, jyutping: ["dim2"], meanings: ["point", "dot", "how"],
    meaningMnemonic: "點 has fire/dots (灬) at the bottom — a scatter of DOTS or POINTS; asking 'at what POINT/HOW' something happens.",
    readingMnemonic: "Dim2 sounds exactly like 'dim' (as in dim sum, or a dim light), rising — 'dim2? HOW do we get to dim sum?'" },
  { hanzi: "解", level: 6, jyutping: ["gaai2"], meanings: ["explain", "solve", "loosen"],
    meaningMnemonic: "解 has horn (角), knife (刀) and ox (牛) — using a knife to cut apart a horn from an ox: taking something apart to EXPLAIN or SOLVE it.",
    readingMnemonic: "Gaai2 sounds like 'guy' rising — 'gaai2? Can that GUY EXPLAIN this to me?'" },
  { hanzi: "幾", level: 6, jyutping: ["gei2"], meanings: ["how many", "quite", "several"],
    meaningMnemonic: "幾 looks like a small stack of things with legs — a small pile, prompting the question 'HOW MANY are there?'",
    readingMnemonic: "Gei2 sounds like 'gay' rising — 'gei2? HOW MANY are we talking about?' asked with a curious rising tone." },
  { hanzi: "樣", level: 6, jyutping: ["joeng6"], meanings: ["kind", "manner", "appearance"],
    meaningMnemonic: "樣 has the wood radical (木) next to sheep (羊) — a wooden carving shaped like a sheep shows a particular KIND or APPEARANCE.",
    readingMnemonic: "Joeng6 sounds like 'young' said low and flat — 'that's the KIND of style YOUNG people like,' said low and flat." },
  { hanzi: "咁", level: 6, jyutping: ["gam2"], meanings: ["so", "like this", "like that"],
    meaningMnemonic: "咁 has the mouth radical (口) next to sweet (甘) — a mouth sweetly saying 'it's just LIKE THIS, SO simple.'",
    readingMnemonic: "Gam2 sounds like 'gum' rising — 'gam2? Is it LIKE THIS?' asked with a rising, checking tone." },
  { hanzi: "嘢", level: 6, jyutping: ["je5"], meanings: ["thing"],
    meaningMnemonic: "嘢 has the mouth radical (口) next to also/moreover (野-ish shape) — a spoken Cantonese character used to point vaguely at any THING.",
    readingMnemonic: "Je5 sounds like 'yeah' dipping then rising — pointing at random and going 'je5, this THING here.'" },
  { hanzi: "呢", level: 6, jyutping: ["nei1", "ni1"], meanings: ["this (demonstrative)", "question particle"],
    meaningMnemonic: "呢 has the mouth radical (口) — spoken aloud while pointing at something close by: 'THIS one, right here.'",
    readingMnemonic: "Nei1 sounds just like 你 (nei5, 'you') but higher and flatter — pointing at something near you (nei) and calling it THIS." },

  // ===== Level 7: food =====
  { hanzi: "茶", level: 7, jyutping: ["caa4"], meanings: ["tea"],
    meaningMnemonic: "茶 has the grass/plant radical (艹) on top — TEA is a plant, brewed from leaves.",
    readingMnemonic: "Caa4 sounds exactly like 'cha' (as English speakers already say for TEA), low and drawn out." },
  { hanzi: "飯", level: 7, jyutping: ["faan6"], meanings: ["rice", "meal"],
    meaningMnemonic: "飯 has the food radical (飠) next to 反 — the classic food radical shows this is about a cooked MEAL, specifically RICE.",
    readingMnemonic: "Faan6 sounds like 'faan' (rhymes with 'fun'), low and flat — sit down low and flat for a good RICE MEAL." },
  { hanzi: "麵", level: 7, jyutping: ["min6"], meanings: ["noodles"],
    meaningMnemonic: "麵 has the wheat radical (麥) next to face (面) — NOODLES are made from wheat flour.",
    readingMnemonic: "Min6 sounds like 'min' said low and flat — slurp NOODLES slowly, low and flat: 'miiin.'" },
  { hanzi: "包", level: 7, jyutping: ["baau1"], meanings: ["bread", "bun", "to wrap"],
    meaningMnemonic: "包 looks like something curled up and WRAPPED inside a covering — a BUN wrapped around its filling.",
    readingMnemonic: "Baau1 sounds like 'bow' (as in take a bow), high and flat — a fluffy BUN puffing up high." },
  { hanzi: "蛋", level: 7, jyutping: ["daan2"], meanings: ["egg"],
    meaningMnemonic: "蛋 has the bug/small-creature radical (虫) with a bird-nest-like top — a little creature waiting to hatch from an EGG.",
    readingMnemonic: "Daan2 sounds like 'dan' rising, like the name Dan asking a question — cracking open an EGG with a rising 'dan2?'" },
  { hanzi: "牛", level: 7, jyutping: ["ngau4"], meanings: ["cow", "beef", "ox"],
    meaningMnemonic: "牛 looks like the front view of an ox's head with two horns — a COW or OX.",
    readingMnemonic: "Ngau4 sounds like a low 'now' — imagine a COW mooing 'ngaaaau' low and drawn out." },
  { hanzi: "豬", level: 7, jyutping: ["zyu1"], meanings: ["pig", "pork"],
    meaningMnemonic: "豬 has the pig radical (豕) on the right — plainly, a PIG.",
    readingMnemonic: "Zyu1 sounds like 'joo' high and flat — a little PIG going 'zyu1, zyu1' instead of oink." },
  { hanzi: "雞", level: 7, jyutping: ["gai1"], meanings: ["chicken"],
    meaningMnemonic: "雞 has the bird radical (鳥/隹) on the right — plainly, a CHICKEN.",
    readingMnemonic: "Gai1 sounds like 'guy' high and flat — a CHICKEN going 'gai1, gai1' instead of cluck." },
  { hanzi: "魚", level: 7, jyutping: ["jyu4"], meanings: ["fish"],
    meaningMnemonic: "魚 is a simple picture of a FISH — head, body with fins, and tail at the bottom.",
    readingMnemonic: "Jyu4 sounds like 'yu' (round your lips like whistling), low and drawn out — a slippery FISH sliding low through your hands." },
  { hanzi: "肉", level: 7, jyutping: ["juk6"], meanings: ["meat"],
    meaningMnemonic: "肉 looks like a slab of MEAT with the marbling/grain lines running through it.",
    readingMnemonic: "Juk6 sounds like 'yuk', low and flat — a thick, heavy cut of MEAT landing on the table with a low 'yuk' thud." },

  // ===== Level 8: connectors & misc adjectives =====
  { hanzi: "同", level: 8, jyutping: ["tung4"], meanings: ["same", "with", "and"],
    meaningMnemonic: "同 has a mouth (口) framed inside a box — everyone speaking with ONE SAME voice, together WITH each other.",
    readingMnemonic: "Tung4 sounds like 'tongue' without the 'e', low and drawn out — sharing one big 'tung' (tongue) SAME as everyone else." },
  { hanzi: "但", level: 8, jyutping: ["daan6"], meanings: ["but"],
    meaningMnemonic: "但 has the person radical (亻) next to dawn/morning (旦) — a person who was fine at dawn, BUT then something changed.",
    readingMnemonic: "Daan6 sounds like 'darn' without the 'r', low and flat — 'daan6, BUT that's a shame,' said low and resigned." },
  { hanzi: "因", level: 8, jyutping: ["jan1"], meanings: ["because", "cause", "reason"],
    meaningMnemonic: "因 shows a person (大-like shape) boxed inside a cause — trapped inside the reason WHY, the CAUSE.",
    readingMnemonic: "Jan1 sounds like 'yun' high and flat, similar to 人 (jan4, person) but higher — the REASON a certain PERSON did something." },
  { hanzi: "為", level: 8, jyutping: ["wai6", "wai4"], meanings: ["for", "because of", "to think / regard (as)"],
    meaningMnemonic: "為 shows a hand guiding an elephant — doing hard work FOR a reason, BECAUSE OF a goal.",
    readingMnemonic: "Wai6 sounds like 'why' said low and flat — asking 'wai6, WHY, FOR what reason?' As wai4 (rising-drawn), it shifts to mean 'to think/regard' — as in 以為 (to assume)." },
  { hanzi: "所", level: 8, jyutping: ["so2"], meanings: ["place", "that which"],
    meaningMnemonic: "所 has door (戶) next to axe (斤) — the specific PLACE where the woodcutter keeps his axe by the door.",
    readingMnemonic: "So2 sounds exactly like 'so' rising — 'so2? Is this the PLACE?' asked with a curious rising tone." },
  { hanzi: "以", level: 8, jyutping: ["ji5"], meanings: ["with", "by means of", "in order to"],
    meaningMnemonic: "以 looks like a person leaning on a tool — using a tool BY MEANS OF leaning on it.",
    readingMnemonic: "Ji5 sounds like 'yee' dipping then rising — leaning on something WITH a rising 'ji5' as you push off it." },
  { hanzi: "新", level: 8, jyutping: ["san1"], meanings: ["new"],
    meaningMnemonic: "新 has axe (斤) next to a tree-cutting element — freshly cut wood is NEW.",
    readingMnemonic: "San1 sounds like 'sun', high and flat — a NEW day starts with the SUN rising high and bright." },
  { hanzi: "舊", level: 8, jyutping: ["gau6"], meanings: ["old (things)"],
    meaningMnemonic: "舊 has grass (艹) growing over a bird-like shape — grass has grown over it from disuse, it's OLD.",
    readingMnemonic: "Gau6 sounds like 九 (gau2, nine) but lower and flatter — something so OLD it's been around since you were nine, low and worn out." },
  { hanzi: "快", level: 8, jyutping: ["faai3"], meanings: ["fast", "quick"],
    meaningMnemonic: "快 has the heart radical (忄) next to 夬 (decisive) — a decisive heart reacts FAST.",
    readingMnemonic: "Faai3 sounds like 'fie' (rhymes with 'pie') said flat and quick — say it FAST, in a flash." },
  { hanzi: "慢", level: 8, jyutping: ["maan6"], meanings: ["slow"],
    meaningMnemonic: "慢 has the heart radical (忄) next to a stretched-out shape (曼) — a heart that takes its time, beating SLOWly.",
    readingMnemonic: "Maan6 sounds like 'maan' (rhymes with 'lawn'), low and drawn out — stretch it out SLOWLY: 'maaaaan6.'" },
  { hanzi: "係", level: 8, jyutping: ["hai6"], meanings: ["to be", "yes"],
    meaningMnemonic: "係 has the person radical (亻) next to a hanging thread (系) — a person is connected TO BE what they are, tied to their identity.",
    readingMnemonic: "Hai6 sounds like 'hi' said low and flat — a flat, certain 'hai6' — YES, that IS correct." },
];

module.exports = characters;
