// Short natural phrases and sentences built entirely from characters
// introduced in characters.js. `level` is set to the highest level among the
// expression's component characters, so it never appears before you've met
// everything it's made of.
const expressions = [
  { hanzi: "你講乜嘢", level: 6, jyutping: ["nei5 gong2 mat1 je5"], meanings: ["what are you talking about?"],
    meaningMnemonic: "你 (you) + 講 (speak) + 乜嘢 (what) — a real, commonly heard question: WHAT ARE YOU TALKING ABOUT?",
    readingMnemonic: "String the words together in order: nei5, gong2, mat1, je5." },
  { hanzi: "你去邊", level: 6, jyutping: ["nei5 heoi3 bin1"], meanings: ["where are you going?"],
    meaningMnemonic: "你 (you) + 去 (go) + 邊 (which/where) — the short, colloquial way to ask WHERE ARE YOU GOING?",
    readingMnemonic: "String the words together in order: nei5, heoi3, bin1." },
  { hanzi: "幾多個人", level: 6, jyutping: ["gei2 do1 go3 jan4"], meanings: ["how many people?"],
    meaningMnemonic: "幾多 (how many) + 個 (measure word) + 人 (people) = HOW MANY PEOPLE?",
    readingMnemonic: "String the words together in order: gei2, do1, go3, jan4." },
  { hanzi: "呢個幾好", level: 6, jyutping: ["ni1 go3 gei2 hou2"], meanings: ["this one's quite good"],
    meaningMnemonic: "呢個 (this one) + 幾 (quite) + 好 (good) = THIS ONE'S QUITE GOOD.",
    readingMnemonic: "String the words together in order: ni1, go3, gei2, hou2." },
  { hanzi: "你做乜嘢", level: 6, jyutping: ["nei5 zou6 mat1 je5"], meanings: ["what are you doing?"],
    meaningMnemonic: "你 (you) + 做 (do) + 乜嘢 (what) = WHAT ARE YOU DOING?",
    readingMnemonic: "String the words together in order: nei5, zou6, mat1, je5." },
  { hanzi: "你係邊個", level: 8, jyutping: ["nei5 hai6 bin1 go3"], meanings: ["who are you?"],
    meaningMnemonic: "你 (you) + 係 (are) + 邊個 (who) = WHO ARE YOU?",
    readingMnemonic: "String the words together in order: nei5, hai6, bin1, go3." },
  { hanzi: "你係唔係", level: 9, jyutping: ["nei5 hai6 m4 hai6"], meanings: ["is that so?", "are you or aren't you?"],
    meaningMnemonic: "你 (you) + 係 (are) + 唔 (not) + 係 (are) — the classic 'verb-not-verb' question pattern: IS THAT SO?",
    readingMnemonic: "String the words together in order: nei5, hai6, m4, hai6." },
  { hanzi: "好唔好食", level: 9, jyutping: ["hou2 m4 hou2 sik6"], meanings: ["is it tasty or not?"],
    meaningMnemonic: "好 (good) + 唔 (not) + 好食 (tasty) — another 'verb-not-verb' question: IS IT TASTY?",
    readingMnemonic: "String the words together in order: hou2, m4, hou2, sik6." },
  { hanzi: "我唔係好人", level: 9, jyutping: ["ngo5 m4 hai6 hou2 jan4"], meanings: ["I'm not a nice person"],
    meaningMnemonic: "我 (I) + 唔係 (am not) + 好人 (nice person) = a playful (or dramatic) I'M NOT A NICE PERSON.",
    readingMnemonic: "String the words together in order: ngo5, m4, hai6, hou2, jan4." },
  { hanzi: "佢哋去邊", level: 9, jyutping: ["keoi5 dei6 heoi3 bin1"], meanings: ["where are they going?"],
    meaningMnemonic: "佢哋 (they) + 去 (go) + 邊 (where) = WHERE ARE THEY GOING?",
    readingMnemonic: "String the words together in order: keoi5, dei6, heoi3, bin1." },
  { hanzi: "我哋去食飯", level: 9, jyutping: ["ngo5 dei6 heoi3 sik6 faan6"], meanings: ["let's go eat!"],
    meaningMnemonic: "我哋 (we) + 去 (go) + 食飯 (eat) = LET'S GO EAT!",
    readingMnemonic: "String the words together in order: ngo5, dei6, heoi3, sik6, faan6." },
  { hanzi: "佢係我同學", level: 9, jyutping: ["keoi5 hai6 ngo5 tung4 hok6"], meanings: ["he/she is my classmate"],
    meaningMnemonic: "佢 (he/she) + 係 (is) + 我 (my) + 同學 (classmate) = HE/SHE IS MY CLASSMATE.",
    readingMnemonic: "String the words together in order: keoi5, hai6, ngo5, tung4, hok6." },
  { hanzi: "佢好開心", level: 10, jyutping: ["keoi5 hou2 hoi1 sam1"], meanings: ["he/she is very happy"],
    meaningMnemonic: "佢 (he/she) + 好 (very) + 開心 (happy) = HE/SHE IS VERY HAPPY.",
    readingMnemonic: "String the words together in order: keoi5, hou2, hoi1, sam1." },
  { hanzi: "今日好凍", level: 11, jyutping: ["gam1 jat6 hou2 dung3"], meanings: ["it's really cold today"],
    meaningMnemonic: "今日 (today) + 好 (very) + 凍 (cold) = IT'S REALLY COLD TODAY.",
    readingMnemonic: "String the words together in order: gam1, jat6, hou2, dung3." },
  { hanzi: "大風大雨", level: 11, jyutping: ["daai6 fung1 daai6 jyu5"], meanings: ["heavy wind and rain", "stormy"],
    meaningMnemonic: "大風 (strong wind) + 大雨 (heavy rain) — a natural, descriptive way to say STORMY weather.",
    readingMnemonic: "String the words together in order: daai6, fung1, daai6, jyu5." },
  { hanzi: "搭車返學", level: 12, jyutping: ["daap3 ce1 faan1 hok6"], meanings: ["to take transit to school"],
    meaningMnemonic: "搭車 (take a vehicle) + 返學 (go to school) = TO TAKE TRANSIT TO SCHOOL.",
    readingMnemonic: "String the words together in order: daap3, ce1, faan1, hok6." },
  { hanzi: "幾時到站", level: 12, jyutping: ["gei2 si4 dou3 zaam6"], meanings: ["when do we arrive at the station?"],
    meaningMnemonic: "幾時 (when) + 到站 (arrive at the station) = WHEN DO WE ARRIVE AT THE STATION?",
    readingMnemonic: "String the words together in order: gei2, si4, dou3, zaam6." },
  { hanzi: "一心一意", level: 13, jyutping: ["jat1 sam1 jat1 ji3"], meanings: ["wholeheartedly"],
    meaningMnemonic: "A genuine four-character set phrase: 一心 (one heart) + 一意 (one mind/intention) — pouring everything into it, WHOLEHEARTEDLY.",
    readingMnemonic: "String the words together in order: jat1, sam1, jat1, ji3." },
  { hanzi: "唔好喊", level: 13, jyutping: ["m4 hou2 haam3"], meanings: ["don't cry"],
    meaningMnemonic: "唔好 (don't) + 喊 (cry) = DON'T CRY — comforting someone.",
    readingMnemonic: "String the words together in order: m4, hou2, haam3." },
  { hanzi: "呢件幾多錢", level: 14, jyutping: ["ni1 gin6 gei2 do1 cin2"], meanings: ["how much is this item?"],
    meaningMnemonic: "呢件 (this item) + 幾多錢 (how much money) = HOW MUCH IS THIS ITEM? — the essential shopping question.",
    readingMnemonic: "String the words together in order: ni1, gin6, gei2, do1, cin2." },
  { hanzi: "你有冇錢", level: 14, jyutping: ["nei5 jau5 mou5 cin2"], meanings: ["do you have money?"],
    meaningMnemonic: "你 (you) + 有冇 (have-or-not) + 錢 (money) — another 'verb-not-verb' question: DO YOU HAVE MONEY?",
    readingMnemonic: "String the words together in order: nei5, jau5, mou5, cin2." },
  { hanzi: "佢有冇去", level: 14, jyutping: ["keoi5 jau5 mou5 heoi3"], meanings: ["did he/she go or not?"],
    meaningMnemonic: "佢 (he/she) + 有冇 (have-or-not) + 去 (go) = DID HE/SHE GO OR NOT?",
    readingMnemonic: "String the words together in order: keoi5, jau5, mou5, heoi3." },
  { hanzi: "你想食乜嘢", level: 15, jyutping: ["nei5 soeng2 sik6 mat1 je5"], meanings: ["what do you want to eat?"],
    meaningMnemonic: "你 (you) + 想食 (want to eat) + 乜嘢 (what) = WHAT DO YOU WANT TO EAT?",
    readingMnemonic: "String the words together in order: nei5, soeng2, sik6, mat1, je5." },
  { hanzi: "我想瞓", level: 18, jyutping: ["ngo5 soeng2 fan3"], meanings: ["I want to sleep"],
    meaningMnemonic: "我 (I) + 想 (want) + 瞓 (sleep) = I WANT TO SLEEP.",
    readingMnemonic: "String the words together in order: ngo5, soeng2, fan3." },
  { hanzi: "早瞓早起", level: 19, jyutping: ["zou2 fan3 zou2 hei2"], meanings: ["sleep early, rise early"],
    meaningMnemonic: "早瞓 (sleep early) + 早起 (rise early) — a simple constructed phrase for good habits, built entirely from words you already know.",
    readingMnemonic: "String the words together in order: zou2, fan3, zou2, hei2." },
  { hanzi: "聽日見", level: 19, jyutping: ["teng1 jat6 gin3"], meanings: ["see you tomorrow!"],
    meaningMnemonic: "聽日 (tomorrow) + 見 (see) = SEE YOU TOMORROW!",
    readingMnemonic: "String the words together in order: teng1, jat6, gin3." },
  { hanzi: "你一定得", level: 20, jyutping: ["nei5 jat1 ding6 dak1"], meanings: ["you can definitely do it!"],
    meaningMnemonic: "你 (you) + 一定 (definitely) + 得 (can/OK) = a common cheer of encouragement: YOU CAN DEFINITELY DO IT!",
    readingMnemonic: "String the words together in order: nei5, jat1, ding6, dak1." },
  { hanzi: "定係你去定係我去", level: 20, jyutping: ["ding6 hai6 nei5 heoi3 ding6 hai6 ngo5 heoi3"], meanings: ["is it you going or me going?"],
    meaningMnemonic: "定係...定係... (or...or...) is the classic Cantonese pattern for offering a choice between two options.",
    readingMnemonic: "String the words together in order: ding6, hai6, nei5, heoi3, ding6, hai6, ngo5, heoi3." },
  { hanzi: "你都想去", level: 20, jyutping: ["nei5 dou1 soeng2 heoi3"], meanings: ["you want to go too"],
    meaningMnemonic: "你 (you) + 都 (also) + 想去 (want to go) = YOU WANT TO GO TOO.",
    readingMnemonic: "String the words together in order: nei5, dou1, soeng2, heoi3." },
];

module.exports = expressions;
