// Short natural phrases and sentences built entirely from characters
// introduced in characters.js. `level` is set to the highest level among the
// expression's component characters, so it never appears before you've met
// everything it's made of.
const expressions = [
  { hanzi: "你講乜嘢", level: 6, jyutping: ["nei5 gong2 mat1 je5"], meanings: ["what are you talking about?"],
    meaningMnemonic: "你 (you) + 講 (speak) + 乜嘢 (what) — a real, commonly heard question: WHAT ARE YOU TALKING ABOUT?",
    readingMnemonic: "String the words together in order: nei5, gong2, mat1, je5." },
  { hanzi: "你去邊", level: 6, jyutping: ["nei5 heoi3 bin1"], meanings: ["where are you going?"],
    meaningMnemonic: "你 (you) + 去 (go) + 邊 (which/where) — the short, colloquial way to ask WHERE ARE YOU GOING?",
    readingMnemonic: "String the words together in order: nei5, heoi3, bin1." },
  { hanzi: "幾多個人", level: 6, jyutping: ["gei2 do1 go3 jan4"], meanings: ["how many people?"],
    meaningMnemonic: "幾多 (how many) + 個 (measure word) + 人 (people) = HOW MANY PEOPLE?",
    readingMnemonic: "String the words together in order: gei2, do1, go3, jan4." },
  { hanzi: "呢個幾好", level: 6, jyutping: ["ni1 go3 gei2 hou2"], meanings: ["this one's quite good"],
    meaningMnemonic: "呢個 (this one) + 幾 (quite) + 好 (good) = THIS ONE'S QUITE GOOD.",
    readingMnemonic: "String the words together in order: ni1, go3, gei2, hou2." },
  { hanzi: "你做乜嘢", level: 6, jyutping: ["nei5 zou6 mat1 je5"], meanings: ["what are you doing?"],
    meaningMnemonic: "你 (you) + 做 (do) + 乜嘢 (what) = WHAT ARE YOU DOING?",
    readingMnemonic: "String the words together in order: nei5, zou6, mat1, je5." },
  { hanzi: "你係邊個", level: 8, jyutping: ["nei5 hai6 bin1 go3"], meanings: ["who are you?"],
    meaningMnemonic: "你 (you) + 係 (are) + 邊個 (who) = WHO ARE YOU?",
    readingMnemonic: "String the words together in order: nei5, hai6, bin1, go3." },
  { hanzi: "你係唔係", level: 9, jyutping: ["nei5 hai6 m4 hai6"], meanings: ["is that so?", "are you or aren't you?"],
    meaningMnemonic: "你 (you) + 係 (are) + 唔 (not) + 係 (are) — the classic 'verb-not-verb' question pattern: IS THAT SO?",
    readingMnemonic: "String the words together in order: nei5, hai6, m4, hai6." },
  { hanzi: "好唔好食", level: 9, jyutping: ["hou2 m4 hou2 sik6"], meanings: ["is it tasty or not?"],
    meaningMnemonic: "好 (good) + 唔 (not) + 好食 (tasty) — another 'verb-not-verb' question: IS IT TASTY?",
    readingMnemonic: "String the words together in order: hou2, m4, hou2, sik6." },
  { hanzi: "我唔係好人", level: 9, jyutping: ["ngo5 m4 hai6 hou2 jan4"], meanings: ["I'm not a nice person"],
    meaningMnemonic: "我 (I) + 唔係 (am not) + 好人 (nice person) = a playful (or dramatic) I'M NOT A NICE PERSON.",
    readingMnemonic: "String the words together in order: ngo5, m4, hai6, hou2, jan4." },
  { hanzi: "佢哋去邊", level: 9, jyutping: ["keoi5 dei6 heoi3 bin1"], meanings: ["where are they going?"],
    meaningMnemonic: "佢哋 (they) + 去 (go) + 邊 (where) = WHERE ARE THEY GOING?",
    readingMnemonic: "String the words together in order: keoi5, dei6, heoi3, bin1." },
  { hanzi: "我哋去食飯", level: 9, jyutping: ["ngo5 dei6 heoi3 sik6 faan6"], meanings: ["let's go eat!"],
    meaningMnemonic: "我哋 (we) + 去 (go) + 食飯 (eat) = LET'S GO EAT!",
    readingMnemonic: "String the words together in order: ngo5, dei6, heoi3, sik6, faan6." },
  { hanzi: "佢係我同學", level: 9, jyutping: ["keoi5 hai6 ngo5 tung4 hok6"], meanings: ["he/she is my classmate"],
    meaningMnemonic: "佢 (he/she) + 係 (is) + 我 (my) + 同學 (classmate) = HE/SHE IS MY CLASSMATE.",
    readingMnemonic: "String the words together in order: keoi5, hai6, ngo5, tung4, hok6." },
  { hanzi: "佢好開心", level: 10, jyutping: ["keoi5 hou2 hoi1 sam1"], meanings: ["he/she is very happy"],
    meaningMnemonic: "佢 (he/she) + 好 (very) + 開心 (happy) = HE/SHE IS VERY HAPPY.",
    readingMnemonic: "String the words together in order: keoi5, hou2, hoi1, sam1." },
  { hanzi: "今日好凍", level: 11, jyutping: ["gam1 jat6 hou2 dung3"], meanings: ["it's really cold today"],
    meaningMnemonic: "今日 (today) + 好 (very) + 凍 (cold) = IT'S REALLY COLD TODAY.",
    readingMnemonic: "String the words together in order: gam1, jat6, hou2, dung3." },
  { hanzi: "大風大雨", level: 11, jyutping: ["daai6 fung1 daai6 jyu5"], meanings: ["heavy wind and rain", "stormy"],
    meaningMnemonic: "大風 (strong wind) + 大雨 (heavy rain) — a natural, descriptive way to say STORMY weather.",
    readingMnemonic: "String the words together in order: daai6, fung1, daai6, jyu5." },
  { hanzi: "搭車返學", level: 12, jyutping: ["daap3 ce1 faan1 hok6"], meanings: ["to take transit to school"],
    meaningMnemonic: "搭車 (take a vehicle) + 返學 (go to school) = TO TAKE TRANSIT TO SCHOOL.",
    readingMnemonic: "String the words together in order: daap3, ce1, faan1, hok6." },
  { hanzi: "幾時到站", level: 12, jyutping: ["gei2 si4 dou3 zaam6"], meanings: ["when do we arrive at the station?"],
    meaningMnemonic: "幾時 (when) + 到站 (arrive at the station) = WHEN DO WE ARRIVE AT THE STATION?",
    readingMnemonic: "String the words together in order: gei2, si4, dou3, zaam6." },
  { hanzi: "一心一意", level: 13, jyutping: ["jat1 sam1 jat1 ji3"], meanings: ["wholeheartedly"],
    meaningMnemonic: "A genuine four-character set phrase: 一心 (one heart) + 一意 (one mind/intention) — pouring everything into it, WHOLEHEARTEDLY.",
    readingMnemonic: "String the words together in order: jat1, sam1, jat1, ji3." },
  { hanzi: "唔好喊", level: 13, jyutping: ["m4 hou2 haam3"], meanings: ["don't cry"],
    meaningMnemonic: "唔好 (don't) + 喊 (cry) = DON'T CRY — comforting someone.",
    readingMnemonic: "String the words together in order: m4, hou2, haam3." },
  { hanzi: "呢件幾多錢", level: 14, jyutping: ["ni1 gin6 gei2 do1 cin2"], meanings: ["how much is this item?"],
    meaningMnemonic: "呢件 (this item) + 幾多錢 (how much money) = HOW MUCH IS THIS ITEM? — the essential shopping question.",
    readingMnemonic: "String the words together in order: ni1, gin6, gei2, do1, cin2." },
  { hanzi: "你有冇錢", level: 14, jyutping: ["nei5 jau5 mou5 cin2"], meanings: ["do you have money?"],
    meaningMnemonic: "你 (you) + 有冇 (have-or-not) + 錢 (money) — another 'verb-not-verb' question: DO YOU HAVE MONEY?",
    readingMnemonic: "String the words together in order: nei5, jau5, mou5, cin2." },
  { hanzi: "佢有冇去", level: 14, jyutping: ["keoi5 jau5 mou5 heoi3"], meanings: ["did he/she go or not?"],
    meaningMnemonic: "佢 (he/she) + 有冇 (have-or-not) + 去 (go) = DID HE/SHE GO OR NOT?",
    readingMnemonic: "String the words together in order: keoi5, jau5, mou5, heoi3." },
  { hanzi: "你想食乜嘢", level: 15, jyutping: ["nei5 soeng2 sik6 mat1 je5"], meanings: ["what do you want to eat?"],
    meaningMnemonic: "你 (you) + 想食 (want to eat) + 乜嘢 (what) = WHAT DO YOU WANT TO EAT?",
    readingMnemonic: "String the words together in order: nei5, soeng2, sik6, mat1, je5." },
  { hanzi: "我想瞓", level: 18, jyutping: ["ngo5 soeng2 fan3"], meanings: ["I want to sleep"],
    meaningMnemonic: "我 (I) + 想 (want) + 瞓 (sleep) = I WANT TO SLEEP.",
    readingMnemonic: "String the words together in order: ngo5, soeng2, fan3." },
  { hanzi: "早瞓早起", level: 19, jyutping: ["zou2 fan3 zou2 hei2"], meanings: ["sleep early, rise early"],
    meaningMnemonic: "早瞓 (sleep early) + 早起 (rise early) — a simple constructed phrase for good habits, built entirely from words you already know.",
    readingMnemonic: "String the words together in order: zou2, fan3, zou2, hei2." },
  { hanzi: "聽日見", level: 19, jyutping: ["teng1 jat6 gin3"], meanings: ["see you tomorrow!"],
    meaningMnemonic: "聽日 (tomorrow) + 見 (see) = SEE YOU TOMORROW!",
    readingMnemonic: "String the words together in order: teng1, jat6, gin3." },
  { hanzi: "你一定得", level: 20, jyutping: ["nei5 jat1 ding6 dak1"], meanings: ["you can definitely do it!"],
    meaningMnemonic: "你 (you) + 一定 (definitely) + 得 (can/OK) = a common cheer of encouragement: YOU CAN DEFINITELY DO IT!",
    readingMnemonic: "String the words together in order: nei5, jat1, ding6, dak1." },
  { hanzi: "定係你去定係我去", level: 20, jyutping: ["ding6 hai6 nei5 heoi3 ding6 hai6 ngo5 heoi3"], meanings: ["is it you going or me going?"],
    meaningMnemonic: "定係...定係... (or...or...) is the classic Cantonese pattern for offering a choice between two options.",
    readingMnemonic: "String the words together in order: ding6, hai6, nei5, heoi3, ding6, hai6, ngo5, heoi3." },
  { hanzi: "你都想去", level: 20, jyutping: ["nei5 dou1 soeng2 heoi3"], meanings: ["you want to go too"],
    meaningMnemonic: "你 (you) + 都 (also) + 想去 (want to go) = YOU WANT TO GO TOO.",
    readingMnemonic: "String the words together in order: nei5, dou1, soeng2, heoi3." },

  // ===== Second pass: extra expressions appended at the end (never
  // reordered) so existing ids and progress stay stable. =====

  { hanzi: "我食好多", level: 4, jyutping: ["ngo5 sik6 hou2 do1"], meanings: ["I eat a lot"],
    meaningMnemonic: "我 (I) + 食 (eat) + 好多 (a lot) = I EAT A LOT.",
    readingMnemonic: "String the words together in order: ngo5, sik6, hou2, do1." },
  { hanzi: "我諗你好", level: 4, jyutping: ["ngo5 nam2 nei5 hou2"], meanings: ["I think you're nice"],
    meaningMnemonic: "我 (I) + 諗 (think) + 你好 (you're good) = I THINK YOU'RE NICE.",
    readingMnemonic: "String the words together in order: ngo5, nam2, nei5, hou2." },
  { hanzi: "你係好朋友", level: 8, jyutping: ["nei5 hai6 hou2 pang4 jau5"], meanings: ["you are a good friend"],
    meaningMnemonic: "你 (you) + 係 (to be) + 好朋友 (good friend) = YOU ARE A GOOD FRIEND.",
    readingMnemonic: "String the words together in order: nei5, hai6, hou2, pang4, jau5." },
  { hanzi: "我哋係老友", level: 9, jyutping: ["ngo5 dei6 hai6 lou5 jau5"], meanings: ["we are old friends"],
    meaningMnemonic: "我哋 (we) + 係 (to be) + 老友 (old friend) = WE ARE OLD FRIENDS.",
    readingMnemonic: "String the words together in order: ngo5, dei6, hai6, lou5, jau5." },
  { hanzi: "我唔鍾意", level: 13, jyutping: ["ngo5 m4 zung1 ji3"], meanings: ["I don't like it"],
    meaningMnemonic: "我 (I) + 唔 (not) + 鍾意 (to like) = I DON'T LIKE IT.",
    readingMnemonic: "String the words together in order: ngo5, m4, zung1, ji3." },
  { hanzi: "今日好熱", level: 11, jyutping: ["gam1 jat6 hou2 jit6"], meanings: ["today is very hot"],
    meaningMnemonic: "今日 (today) + 好 (very) + 熱 (hot) = TODAY IS VERY HOT.",
    readingMnemonic: "String the words together in order: gam1, jat6, hou2, jit6." },
  { hanzi: "聽日落雨", level: 11, jyutping: ["teng1 jat6 lok6 jyu5"], meanings: ["it will rain tomorrow"],
    meaningMnemonic: "聽日 (tomorrow) + 落雨 (to rain) = IT WILL RAIN TOMORROW.",
    readingMnemonic: "String the words together in order: teng1, jat6, lok6, jyu5." },
  { hanzi: "我哋一齊食飯", level: 19, jyutping: ["ngo5 dei6 jat1 cai4 sik6 faan6"], meanings: ["let's eat together"],
    meaningMnemonic: "我哋 (we) + 一齊 (together) + 食飯 (eat) = LET'S EAT TOGETHER.",
    readingMnemonic: "String the words together in order: ngo5, dei6, jat1, cai4, sik6, faan6." },
  { hanzi: "你屋企有幾多人", level: 14, jyutping: ["nei5 uk1 kei5 jau5 gei2 do1 jan4"], meanings: ["how many people are in your family?"],
    meaningMnemonic: "你屋企 (your home) + 有 (have) + 幾多人 (how many people) = HOW MANY PEOPLE ARE IN YOUR FAMILY?",
    readingMnemonic: "String the words together in order: nei5, uk1, kei5, jau5, gei2, do1, jan4." },
  { hanzi: "我想去街市買嘢", level: 15, jyutping: ["ngo5 soeng2 heoi3 gaai1 si5 maai5 je5"], meanings: ["I want to go to the market to buy something"],
    meaningMnemonic: "我想去 (I want to go) + 街市 (market) + 買嘢 (buy something) = I WANT TO GO TO THE MARKET TO BUY SOMETHING.",
    readingMnemonic: "String the words together in order: ngo5, soeng2, heoi3, gaai1, si5, maai5, je5." },
  { hanzi: "你識唔識做", level: 15, jyutping: ["nei5 sik1 m4 sik1 zou6"], meanings: ["do you know how to do it?"],
    meaningMnemonic: "你識唔識 (do you know how to) + 做 (do) = DO YOU KNOW HOW TO DO IT?",
    readingMnemonic: "String the words together in order: nei5, sik1, m4, sik1, zou6." },
  { hanzi: "呢個幾多錢", level: 14, jyutping: ["nei1 go3 gei2 do1 cin2"], meanings: ["how much is this?"],
    meaningMnemonic: "呢個 (this one) + 幾多錢 (how much money) = HOW MUCH IS THIS?",
    readingMnemonic: "String the words together in order: nei1, go3, gei2, do1, cin2." },
  { hanzi: "你有冇朋友", level: 14, jyutping: ["nei5 jau5 mou5 pang4 jau5"], meanings: ["do you have friends?"],
    meaningMnemonic: "你 (you) + 有冇 (have or not) + 朋友 (friends) = DO YOU HAVE FRIENDS?",
    readingMnemonic: "String the words together in order: nei5, jau5, mou5, pang4, jau5." },
  { hanzi: "我唔想食藥", level: 18, jyutping: ["ngo5 m4 soeng2 sik6 joek6"], meanings: ["I don't want to take medicine"],
    meaningMnemonic: "我唔想 (I don't want to) + 食藥 (take medicine) = I DON'T WANT TO TAKE MEDICINE.",
    readingMnemonic: "String the words together in order: ngo5, m4, soeng2, sik6, joek6." },
  { hanzi: "佢生病住院", level: 19, jyutping: ["keoi5 sang1 beng6 zyu6 jyun2"], meanings: ["he/she is sick and in hospital"],
    meaningMnemonic: "佢 (he/she) + 生病 (fall sick) + 住院 (stay in hospital) = HE/SHE IS SICK AND IN HOSPITAL.",
    readingMnemonic: "String the words together in order: keoi5, sang1, beng6, zyu6, jyun2." },
  { hanzi: "你幾時返屋企", level: 12, jyutping: ["nei5 gei2 si4 faan1 uk1 kei5"], meanings: ["when are you going home?"],
    meaningMnemonic: "你 (you) + 幾時 (when) + 返屋企 (return home) = WHEN ARE YOU GOING HOME?",
    readingMnemonic: "String the words together in order: nei5, gei2, si4, faan1, uk1, kei5." },
  { hanzi: "我聽日返學", level: 12, jyutping: ["ngo5 teng1 jat6 faan1 hok6"], meanings: ["I'm going to school tomorrow"],
    meaningMnemonic: "我 (I) + 聽日 (tomorrow) + 返學 (go to school) = I'M GOING TO SCHOOL TOMORROW.",
    readingMnemonic: "String the words together in order: ngo5, teng1, jat6, faan1, hok6." },
  { hanzi: "我想學嘢", level: 15, jyutping: ["ngo5 soeng2 hok6 je5"], meanings: ["I want to learn things"],
    meaningMnemonic: "我想 (I want) + 學 (learn) + 嘢 (things) = I WANT TO LEARN THINGS.",
    readingMnemonic: "String the words together in order: ngo5, soeng2, hok6, je5." },
  { hanzi: "你講得好快", level: 15, jyutping: ["nei5 gong2 dak1 hou2 faai3"], meanings: ["you speak very fast"],
    meaningMnemonic: "你講得 (the way you speak) + 好快 (very fast) = YOU SPEAK VERY FAST.",
    readingMnemonic: "String the words together in order: nei5, gong2, dak1, hou2, faai3." },
  { hanzi: "佢行得好慢", level: 15, jyutping: ["keoi5 haang4 dak1 hou2 maan6"], meanings: ["he/she walks very slowly"],
    meaningMnemonic: "佢行得 (the way he/she walks) + 好慢 (very slow) = HE/SHE WALKS VERY SLOWLY.",
    readingMnemonic: "String the words together in order: keoi5, haang4, dak1, hou2, maan6." },
  { hanzi: "你想飲茶定係飲湯", level: 20, jyutping: ["nei5 soeng2 jam2 caa4 ding6 hai6 jam2 tong1"], meanings: ["do you want tea or soup?"],
    meaningMnemonic: "你想飲茶 (you want to drink tea) + 定係 (or) + 飲湯 (drink soup) = DO YOU WANT TEA OR SOUP?",
    readingMnemonic: "String the words together in order: nei5, soeng2, jam2, caa4, ding6, hai6, jam2, tong1." },
  { hanzi: "我今日好忙", level: 15, jyutping: ["ngo5 gam1 jat6 hou2 mong4"], meanings: ["I'm very busy today"],
    meaningMnemonic: "我今日 (I today) + 好忙 (very busy) = I'M VERY BUSY TODAY.",
    readingMnemonic: "String the words together in order: ngo5, gam1, jat6, hou2, mong4." },
  { hanzi: "呢個房幾多錢", level: 14, jyutping: ["nei1 go3 fong2 gei2 do1 cin2"], meanings: ["how much is this room?"],
    meaningMnemonic: "呢個房 (this room) + 幾多錢 (how much money) = HOW MUCH IS THIS ROOM?",
    readingMnemonic: "String the words together in order: nei1, go3, fong2, gei2, do1, cin2." },
  { hanzi: "我今日返工", level: 15, jyutping: ["ngo5 gam1 jat6 faan1 gung1"], meanings: ["I'm working today"],
    meaningMnemonic: "我今日 (I today) + 返工 (go to work) = I'M WORKING TODAY.",
    readingMnemonic: "String the words together in order: ngo5, gam1, jat6, faan1, gung1." },
  { hanzi: "佢好鍾意笑", level: 13, jyutping: ["keoi5 hou2 zung1 ji3 siu3"], meanings: ["he/she really likes to laugh"],
    meaningMnemonic: "佢 (he/she) + 好鍾意 (really likes) + 笑 (to laugh) = HE/SHE REALLY LIKES TO LAUGH.",
    readingMnemonic: "String the words together in order: keoi5, hou2, zung1, ji3, siu3." },
  { hanzi: "我哋一齊去街市", level: 19, jyutping: ["ngo5 dei6 jat1 cai4 heoi3 gaai1 si5"], meanings: ["let's go to the market together"],
    meaningMnemonic: "我哋一齊 (we together) + 去街市 (go to the market) = LET'S GO TO THE MARKET TOGETHER.",
    readingMnemonic: "String the words together in order: ngo5, dei6, jat1, cai4, heoi3, gaai1, si5." },
  { hanzi: "佢冇錢買嘢食", level: 14, jyutping: ["keoi5 mou5 cin2 maai5 je5 sik6"], meanings: ["he/she has no money to buy food"],
    meaningMnemonic: "佢冇錢 (he/she has no money) + 買嘢食 (buy something to eat) = HE/SHE HAS NO MONEY TO BUY FOOD.",
    readingMnemonic: "String the words together in order: keoi5, mou5, cin2, maai5, je5, sik6." },
  { hanzi: "我想同你講嘢", level: 15, jyutping: ["ngo5 soeng2 tung4 nei5 gong2 je5"], meanings: ["I want to talk to you about something"],
    meaningMnemonic: "我想同你 (I want, with you) + 講嘢 (talk about something) = I WANT TO TALK TO YOU ABOUT SOMETHING.",
    readingMnemonic: "String the words together in order: ngo5, soeng2, tung4, nei5, gong2, je5." },
  { hanzi: "你有冇睇電視", level: 17, jyutping: ["nei5 jau5 mou5 tai2 din6 si6"], meanings: ["have you watched TV?"],
    meaningMnemonic: "你有冇 (have you or not) + 睇電視 (watch TV) = HAVE YOU WATCHED TV?",
    readingMnemonic: "String the words together in order: nei5, jau5, mou5, tai2, din6, si6." },
  { hanzi: "佢今朝冇食朝", level: 14, jyutping: ["keoi5 gam1 ziu1 mou5 sik6 ziu1"], meanings: ["he/she didn't have breakfast this morning"],
    meaningMnemonic: "佢今朝 (he/she this morning) + 冇食朝 (didn't have breakfast) = HE/SHE DIDN'T HAVE BREAKFAST THIS MORNING.",
    readingMnemonic: "String the words together in order: keoi5, gam1, ziu1, mou5, sik6, ziu1." },
  { hanzi: "我好想瞓", level: 18, jyutping: ["ngo5 hou2 soeng2 fan3"], meanings: ["I really want to sleep"],
    meaningMnemonic: "我 (I) + 好想 (really want) + 瞓 (sleep) = I REALLY WANT TO SLEEP.",
    readingMnemonic: "String the words together in order: ngo5, hou2, soeng2, fan3." },
  { hanzi: "你識唔識搭車", level: 15, jyutping: ["nei5 sik1 m4 sik1 daap3 ce1"], meanings: ["do you know how to take the bus/train?"],
    meaningMnemonic: "你識唔識 (do you know how to) + 搭車 (take a vehicle) = DO YOU KNOW HOW TO TAKE THE BUS/TRAIN?",
    readingMnemonic: "String the words together in order: nei5, sik1, m4, sik1, daap3, ce1." },
  { hanzi: "佢屋企有電話", level: 17, jyutping: ["keoi5 uk1 kei5 jau5 din6 waa6"], meanings: ["he/she has a phone at home"],
    meaningMnemonic: "佢屋企 (his/her home) + 有 (has) + 電話 (phone) = HE/SHE HAS A PHONE AT HOME.",
    readingMnemonic: "String the words together in order: keoi5, uk1, kei5, jau5, din6, waa6." },
  { hanzi: "你點解唔開心", level: 10, jyutping: ["nei5 dim2 gaai2 m4 hoi1 sam1"], meanings: ["why aren't you happy?"],
    meaningMnemonic: "你 (you) + 點解 (why) + 唔開心 (not happy) = WHY AREN'T YOU HAPPY?",
    readingMnemonic: "String the words together in order: nei5, dim2, gaai2, m4, hoi1, sam1." },
  { hanzi: "我哋幾時再見", level: 19, jyutping: ["ngo5 dei6 gei2 si4 zoi3 gin3"], meanings: ["when will we meet again?"],
    meaningMnemonic: "我哋 (we) + 幾時 (when) + 再見 (meet again) = WHEN WILL WE MEET AGAIN?",
    readingMnemonic: "String the words together in order: ngo5, dei6, gei2, si4, zoi3, gin3." },
  { hanzi: "你講嘢好好笑", level: 13, jyutping: ["nei5 gong2 je5 hou2 hou2 siu3"], meanings: ["what you say is very funny"],
    meaningMnemonic: "你講嘢 (what you say) + 好好笑 (very funny) = WHAT YOU SAY IS VERY FUNNY.",
    readingMnemonic: "String the words together in order: nei5, gong2, je5, hou2, hou2, siu3." },
  { hanzi: "我個心口好痛", level: 18, jyutping: ["ngo5 go3 sam1 hau2 hou2 tung3"], meanings: ["my chest hurts a lot"],
    meaningMnemonic: "我個心口 (my chest) + 好痛 (hurts a lot) = MY CHEST HURTS A LOT.",
    readingMnemonic: "String the words together in order: ngo5, go3, sam1, hau2, hou2, tung3." },
  { hanzi: "佢好憎食藥", level: 18, jyutping: ["keoi5 hou2 zang1 sik6 joek6"], meanings: ["he/she really hates taking medicine"],
    meaningMnemonic: "佢好憎 (he/she really hates) + 食藥 (taking medicine) = HE/SHE REALLY HATES TAKING MEDICINE.",
    readingMnemonic: "String the words together in order: keoi5, hou2, zang1, sik6, joek6." },
  { hanzi: "你有冇銀包", level: 14, jyutping: ["nei5 jau5 mou5 ngan4 baau1"], meanings: ["do you have a wallet?"],
    meaningMnemonic: "你有冇 (have you or not) + 銀包 (wallet) = DO YOU HAVE A WALLET?",
    readingMnemonic: "String the words together in order: nei5, jau5, mou5, ngan4, baau1." },
  { hanzi: "呢個銀包幾多錢", level: 14, jyutping: ["nei1 go3 ngan4 baau1 gei2 do1 cin2"], meanings: ["how much is this wallet?"],
    meaningMnemonic: "呢個銀包 (this wallet) + 幾多錢 (how much money) = HOW MUCH IS THIS WALLET?",
    readingMnemonic: "String the words together in order: nei1, go3, ngan4, baau1, gei2, do1, cin2." },
  { hanzi: "我想搭飛機去", level: 17, jyutping: ["ngo5 soeng2 daap3 fei1 gei1 heoi3"], meanings: ["I want to fly there"],
    meaningMnemonic: "我想搭 (I want to ride) + 飛機 (airplane) + 去 (go) = I WANT TO FLY THERE.",
    readingMnemonic: "String the words together in order: ngo5, soeng2, daap3, fei1, gei1, heoi3." },
  { hanzi: "你今晚做乜嘢", level: 19, jyutping: ["nei5 gam1 maan5 zou6 mat1 je5"], meanings: ["what are you doing tonight?"],
    meaningMnemonic: "你 (you) + 今晚 (tonight) + 做乜嘢 (doing what) = WHAT ARE YOU DOING TONIGHT?",
    readingMnemonic: "String the words together in order: nei5, gam1, maan5, zou6, mat1, je5." },
  { hanzi: "我哋見面食飯", level: 19, jyutping: ["ngo5 dei6 gin3 min6 sik6 faan6"], meanings: ["let's meet up and eat"],
    meaningMnemonic: "我哋 (we) + 見面 (meet) + 食飯 (eat) = LET'S MEET UP AND EAT.",
    readingMnemonic: "String the words together in order: ngo5, dei6, gin3, min6, sik6, faan6." },
  { hanzi: "你屋企好大", level: 5, jyutping: ["nei5 uk1 kei5 hou2 daai6"], meanings: ["your home is very big"],
    meaningMnemonic: "你屋企 (your home) + 好大 (very big) = YOUR HOME IS VERY BIG.",
    readingMnemonic: "String the words together in order: nei5, uk1, kei5, hou2, daai6." },
  { hanzi: "我個房好細", level: 6, jyutping: ["ngo5 go3 fong2 hou2 sai3"], meanings: ["my room is very small"],
    meaningMnemonic: "我個房 (my room) + 好細 (very small) = MY ROOM IS VERY SMALL.",
    readingMnemonic: "String the words together in order: ngo5, go3, fong2, hou2, sai3." },
  { hanzi: "你想住邊個房", level: 19, jyutping: ["nei5 soeng2 zyu6 bin1 go3 fong2"], meanings: ["which room do you want to stay in?"],
    meaningMnemonic: "你想住 (you want to stay in) + 邊個房 (which room) = WHICH ROOM DO YOU WANT TO STAY IN?",
    readingMnemonic: "String the words together in order: nei5, soeng2, zyu6, bin1, go3, fong2." },
];

module.exports = expressions;
