// Vocabulary built from the characters in characters.js. Each word's
// component characters are derived automatically at seed time by splitting
// its `hanzi` string, so there's no id bookkeeping to maintain here — just
// add words using characters that exist somewhere in characters.js.
const vocabulary = [
  // ===== Level 1 =====
  { hanzi: "你好", level: 1, jyutping: ["nei5 hou2"], meanings: ["hello"],
    meaningMnemonic: "你 (you) + 好 (good) = wishing the person in front of you well — HELLO.",
    readingMnemonic: "Just say nei5 (你) then hou2 (好) back to back: nei5 hou2." },
  { hanzi: "大人", level: 1, jyutping: ["daai6 jan4"], meanings: ["adult"],
    meaningMnemonic: "大 (big) + 人 (person) = a big person, an ADULT.",
    readingMnemonic: "Just say daai6 (大) then jan4 (人) back to back: daai6 jan4." },
  { hanzi: "好人", level: 1, jyutping: ["hou2 jan4"], meanings: ["good person", "nice person"],
    meaningMnemonic: "好 (good) + 人 (person) = a GOOD PERSON.",
    readingMnemonic: "Just say hou2 (好) then jan4 (人) back to back: hou2 jan4." },

  // ===== Level 2 =====
  { hanzi: "女人", level: 2, jyutping: ["neoi5 jan4"], meanings: ["woman"],
    meaningMnemonic: "女 (female) + 人 (person) = a WOMAN.",
    readingMnemonic: "Just say neoi5 (女) then jan4 (人) back to back: neoi5 jan4." },
  { hanzi: "男人", level: 2, jyutping: ["naam4 jan4"], meanings: ["man"],
    meaningMnemonic: "男 (male) + 人 (person) = a MAN.",
    readingMnemonic: "Just say naam4 (男) then jan4 (人) back to back: naam4 jan4." },
  { hanzi: "老人", level: 2, jyutping: ["lou5 jan4"], meanings: ["elderly person"],
    meaningMnemonic: "老 (old) + 人 (person) = an ELDERLY PERSON.",
    readingMnemonic: "Just say lou5 (老) then jan4 (人) back to back: lou5 jan4." },
  { hanzi: "爸爸", level: 2, jyutping: ["baa1 baa1"], meanings: ["dad", "father"],
    meaningMnemonic: "爸 doubled up is the everyday, affectionate way to say DAD.",
    readingMnemonic: "Just say baa1 (爸) twice: baa1 baa1." },
  { hanzi: "媽媽", level: 2, jyutping: ["maa1 maa1"], meanings: ["mom", "mother"],
    meaningMnemonic: "媽 doubled up is the everyday, affectionate way to say MOM.",
    readingMnemonic: "Just say maa1 (媽) twice: maa1 maa1." },
  { hanzi: "多少", level: 2, jyutping: ["do1 siu2"], meanings: ["how much", "how many"],
    meaningMnemonic: "多 (many) + 少 uses the 小-sound 'siu2' here meaning few — putting 'many' and 'few' together asks HOW MUCH / HOW MANY.",
    readingMnemonic: "Just say do1 (多) then siu2 back to back: do1 siu2." },
  { hanzi: "老細", level: 2, jyutping: ["lou5 sai3"], meanings: ["boss"],
    meaningMnemonic: "老 (old, i.e. senior) + 細 (small) — literally 'old-small', the everyday Cantonese slang for your BOSS.",
    readingMnemonic: "Just say lou5 (老) then sai3 (細) back to back: lou5 sai3." },

  // ===== Level 3 =====
  { hanzi: "今日", level: 3, jyutping: ["gam1 jat6"], meanings: ["today"],
    meaningMnemonic: "今 (now) + 日 (day) = this very day, TODAY.",
    readingMnemonic: "Just say gam1 (今) then jat6 (日) back to back: gam1 jat6." },
  { hanzi: "今年", level: 3, jyutping: ["gam1 nin4"], meanings: ["this year"],
    meaningMnemonic: "今 (now) + 年 (year) = THIS YEAR.",
    readingMnemonic: "Just say gam1 (今) then nin4 (年) back to back: gam1 nin4." },
  { hanzi: "日日", level: 3, jyutping: ["jat6 jat6"], meanings: ["every day"],
    meaningMnemonic: "日 doubled up means EVERY DAY, day after day.",
    readingMnemonic: "Just say jat6 (日) twice: jat6 jat6." },
  { hanzi: "年年", level: 3, jyutping: ["nin4 nin4"], meanings: ["every year"],
    meaningMnemonic: "年 doubled up means EVERY YEAR, year after year.",
    readingMnemonic: "Just say nin4 (年) twice: nin4 nin4." },
  { hanzi: "十年", level: 3, jyutping: ["sap6 nin4"], meanings: ["decade"],
    meaningMnemonic: "十 (ten) + 年 (year) = ten years, a DECADE.",
    readingMnemonic: "Just say sap6 (十) then nin4 (年) back to back: sap6 nin4." },
  { hanzi: "時時", level: 3, jyutping: ["si4 si4"], meanings: ["often", "always"],
    meaningMnemonic: "時 doubled up means at all TIMES — OFTEN, ALWAYS.",
    readingMnemonic: "Just say si4 (時) twice: si4 si4." },

  // ===== Level 4 =====
  { hanzi: "好食", level: 4, jyutping: ["hou2 sik6"], meanings: ["delicious", "tasty"],
    meaningMnemonic: "好 (good) + 食 (eat) = good to eat, DELICIOUS.",
    readingMnemonic: "Just say hou2 (好) then sik6 (食) back to back: hou2 sik6." },
  { hanzi: "好睇", level: 4, jyutping: ["hou2 tai2"], meanings: ["good-looking"],
    meaningMnemonic: "好 (good) + 睇 (look) = good to look at, GOOD-LOOKING.",
    readingMnemonic: "Just say hou2 (好) then tai2 (睇) back to back: hou2 tai2." },
  { hanzi: "好聽", level: 4, jyutping: ["hou2 teng1"], meanings: ["nice-sounding", "pleasant to hear"],
    meaningMnemonic: "好 (good) + 聽 (listen) = good to listen to, NICE-SOUNDING.",
    readingMnemonic: "Just say hou2 (好) then teng1 (聽) back to back: hou2 teng1." },
  { hanzi: "買賣", level: 4, jyutping: ["maai5 maai6"], meanings: ["buying and selling", "business", "trade"],
    meaningMnemonic: "買 (buy) + 賣 (sell) = BUYING AND SELLING, i.e. BUSINESS.",
    readingMnemonic: "Just say maai5 (買, rising) then maai6 (賣, low) back to back: maai5 maai6." },
  { hanzi: "做人", level: 4, jyutping: ["zou6 jan4"], meanings: ["to conduct oneself", "to be a person"],
    meaningMnemonic: "做 (do/make) + 人 (person) = how you MAKE yourself into a PERSON, i.e. how you conduct yourself in life.",
    readingMnemonic: "Just say zou6 (做) then jan4 (人) back to back: zou6 jan4." },
  { hanzi: "去年", level: 4, jyutping: ["heoi3 nin4"], meanings: ["last year"],
    meaningMnemonic: "去 (go, i.e. past) + 年 (year) = the year that has GONE, LAST YEAR.",
    readingMnemonic: "Just say heoi3 (去) then nin4 (年) back to back: heoi3 nin4." },
  { hanzi: "十四", level: 4, jyutping: ["sap6 sei3"], meanings: ["fourteen"],
    meaningMnemonic: "十 (ten) + 四 (four) = FOURTEEN.",
    readingMnemonic: "Just say sap6 (十) then sei3 (四) back to back: sap6 sei3." },
  { hanzi: "二十", level: 4, jyutping: ["ji6 sap6"], meanings: ["twenty"],
    meaningMnemonic: "二 (two) + 十 (ten) = two tens, TWENTY.",
    readingMnemonic: "Just say ji6 (二) then sap6 (十) back to back: ji6 sap6." },
  { hanzi: "三十", level: 4, jyutping: ["saam1 sap6"], meanings: ["thirty"],
    meaningMnemonic: "三 (three) + 十 (ten) = three tens, THIRTY.",
    readingMnemonic: "Just say saam1 (三) then sap6 (十) back to back: saam1 sap6." },
  { hanzi: "六十", level: 4, jyutping: ["luk6 sap6"], meanings: ["sixty"],
    meaningMnemonic: "六 (six) + 十 (ten) = six tens, SIXTY.",
    readingMnemonic: "Just say luk6 (六) then sap6 (十) back to back: luk6 sap6." },

  // ===== Level 5 =====
  { hanzi: "屋企", level: 5, jyutping: ["uk1 kei5"], meanings: ["home"],
    meaningMnemonic: "屋 (house) + 企 (stand) = the house where you stand and stay, HOME.",
    readingMnemonic: "Just say uk1 (屋) then kei5 (企) back to back: uk1 kei5." },
  { hanzi: "學校", level: 5, jyutping: ["hok6 haau6"], meanings: ["school"],
    meaningMnemonic: "學 (study) + 校 (school building) = the SCHOOL.",
    readingMnemonic: "Just say hok6 (學) then haau6 (校) back to back: hok6 haau6." },
  { hanzi: "街市", level: 5, jyutping: ["gaai1 si5"], meanings: ["wet market"],
    meaningMnemonic: "街 (street) + 市 (market) = the street MARKET, a WET MARKET.",
    readingMnemonic: "Just say gaai1 (街) then si5 (市) back to back: gaai1 si5." },
  { hanzi: "左右", level: 5, jyutping: ["zo2 jau6"], meanings: ["left and right", "approximately"],
    meaningMnemonic: "左 (left) + 右 (right) = LEFT AND RIGHT; also used loosely to mean 'give or take, APPROXIMATELY.'",
    readingMnemonic: "Just say zo2 (左) then jau6 (右) back to back: zo2 jau6." },
  { hanzi: "上下", level: 5, jyutping: ["soeng6 haa6"], meanings: ["up and down", "approximately"],
    meaningMnemonic: "上 (up) + 下 (down) = UP AND DOWN; like 左右, also used to mean 'more or less, APPROXIMATELY.'",
    readingMnemonic: "Here 上 flattens to soeng6 (not the rising soeng5) since it's paired as a set phrase — say soeng6 haa6." },
  { hanzi: "上嚟", level: 5, jyutping: ["soeng5 lai4"], meanings: ["come up"],
    meaningMnemonic: "上 (up) + 嚟 (come) = COME UP (towards the speaker).",
    readingMnemonic: "Just say soeng5 (上, rising) then lai4 (嚟) back to back: soeng5 lai4." },
  { hanzi: "大學", level: 5, jyutping: ["daai6 hok6"], meanings: ["university"],
    meaningMnemonic: "大 (big) + 學 (study) = 'big study' — UNIVERSITY.",
    readingMnemonic: "Just say daai6 (大) then hok6 (學) back to back: daai6 hok6." },
  { hanzi: "中學", level: 5, jyutping: ["zung1 hok6"], meanings: ["secondary school", "middle school"],
    meaningMnemonic: "中 (middle) + 學 (study) = 'middle study' — SECONDARY SCHOOL.",
    readingMnemonic: "Just say zung1 (中) then hok6 (學) back to back: zung1 hok6." },
  { hanzi: "小學", level: 5, jyutping: ["siu2 hok6"], meanings: ["primary school", "elementary school"],
    meaningMnemonic: "小 (small) + 學 (study) = 'small study' — PRIMARY SCHOOL.",
    readingMnemonic: "Just say siu2 (小) then hok6 (學) back to back: siu2 hok6." },
  { hanzi: "上街", level: 5, jyutping: ["soeng5 gaai1"], meanings: ["go out", "go out onto the street"],
    meaningMnemonic: "上 (go up/onto) + 街 (street) = heading out onto the STREET, i.e. to GO OUT.",
    readingMnemonic: "Just say soeng5 (上, rising) then gaai1 (街) back to back: soeng5 gaai1." },

  // ===== Level 6 =====
  { hanzi: "邊個", level: 6, jyutping: ["bin1 go3"], meanings: ["who"],
    meaningMnemonic: "邊 (which) + 個 (individual) = 'which one' — WHO.",
    readingMnemonic: "Just say bin1 (邊) then go3 (個) back to back: bin1 go3." },
  { hanzi: "乜嘢", level: 6, jyutping: ["mat1 je5"], meanings: ["what"],
    meaningMnemonic: "乜 (what) + 嘢 (thing) = 'what thing' — WHAT.",
    readingMnemonic: "Just say mat1 (乜) then je5 (嘢) back to back: mat1 je5." },
  { hanzi: "點解", level: 6, jyutping: ["dim2 gaai2"], meanings: ["why"],
    meaningMnemonic: "點 (how) + 解 (explain) = 'how to explain it' — WHY.",
    readingMnemonic: "Just say dim2 (點) then gaai2 (解) back to back: dim2 gaai2." },
  { hanzi: "點樣", level: 6, jyutping: ["dim2 joeng6"], meanings: ["how", "what way"],
    meaningMnemonic: "點 (how) + 樣 (manner) = 'what manner' — HOW, WHAT WAY.",
    readingMnemonic: "Just say dim2 (點) then joeng6 (樣) back to back: dim2 joeng6." },
  { hanzi: "幾多", level: 6, jyutping: ["gei2 do1"], meanings: ["how much", "how many"],
    meaningMnemonic: "幾 (how many) + 多 (much) = HOW MUCH, HOW MANY.",
    readingMnemonic: "Just say gei2 (幾) then do1 (多) back to back: gei2 do1." },
  { hanzi: "咁樣", level: 6, jyutping: ["gam2 joeng6"], meanings: ["like that", "in that way"],
    meaningMnemonic: "咁 (so/like this) + 樣 (manner) = 'in this/that manner' — LIKE THAT.",
    readingMnemonic: "Just say gam2 (咁) then joeng6 (樣) back to back: gam2 joeng6." },
  { hanzi: "呢個", level: 6, jyutping: ["nei1 go3"], meanings: ["this one"],
    meaningMnemonic: "呢 (this) + 個 (individual) = THIS ONE.",
    readingMnemonic: "Just say nei1 (呢) then go3 (個) back to back: nei1 go3." },
  { hanzi: "個個", level: 6, jyutping: ["go3 go3"], meanings: ["everyone", "every one"],
    meaningMnemonic: "個 doubled up means every single individual — EVERYONE.",
    readingMnemonic: "Just say go3 (個) twice: go3 go3." },
  { hanzi: "幾個", level: 6, jyutping: ["gei2 go3"], meanings: ["a few", "several"],
    meaningMnemonic: "幾 (several) + 個 (individual) = A FEW, SEVERAL.",
    readingMnemonic: "Just say gei2 (幾) then go3 (個) back to back: gei2 go3." },
  { hanzi: "幾時", level: 6, jyutping: ["gei2 si4"], meanings: ["when"],
    meaningMnemonic: "幾 (how many/what) + 時 (time) = 'what time' — WHEN.",
    readingMnemonic: "Just say gei2 (幾) then si4 (時) back to back: gei2 si4." },

  // ===== Level 7 =====
  { hanzi: "食飯", level: 7, jyutping: ["sik6 faan6"], meanings: ["to eat", "to have a meal"],
    meaningMnemonic: "食 (eat) + 飯 (rice/meal) = TO EAT / HAVE A MEAL — the most common way to say 'eat' in Cantonese.",
    readingMnemonic: "Just say sik6 (食) then faan6 (飯) back to back: sik6 faan6." },
  { hanzi: "飲茶", level: 7, jyutping: ["jam2 caa4"], meanings: ["to drink tea", "yum cha"],
    meaningMnemonic: "飲 (drink) + 茶 (tea) = TO DRINK TEA — also the name for the whole dim sum outing, YUM CHA.",
    readingMnemonic: "Just say jam2 (飲) then caa4 (茶) back to back: jam2 caa4." },
  { hanzi: "牛肉", level: 7, jyutping: ["ngau4 juk6"], meanings: ["beef"],
    meaningMnemonic: "牛 (cow) + 肉 (meat) = BEEF.",
    readingMnemonic: "Just say ngau4 (牛) then juk6 (肉) back to back: ngau4 juk6." },
  { hanzi: "豬肉", level: 7, jyutping: ["zyu1 juk6"], meanings: ["pork"],
    meaningMnemonic: "豬 (pig) + 肉 (meat) = PORK.",
    readingMnemonic: "Just say zyu1 (豬) then juk6 (肉) back to back: zyu1 juk6." },
  { hanzi: "雞肉", level: 7, jyutping: ["gai1 juk6"], meanings: ["chicken meat"],
    meaningMnemonic: "雞 (chicken) + 肉 (meat) = CHICKEN MEAT.",
    readingMnemonic: "Just say gai1 (雞) then juk6 (肉) back to back: gai1 juk6." },
  { hanzi: "魚肉", level: 7, jyutping: ["jyu4 juk6"], meanings: ["fish meat", "fillet"],
    meaningMnemonic: "魚 (fish) + 肉 (meat) = FISH MEAT, FILLET.",
    readingMnemonic: "Just say jyu4 (魚) then juk6 (肉) back to back: jyu4 juk6." },
  { hanzi: "麵包", level: 7, jyutping: ["min6 baau1"], meanings: ["bread"],
    meaningMnemonic: "麵 (wheat/noodles) + 包 (bun) = BREAD.",
    readingMnemonic: "Just say min6 (麵) then baau1 (包) back to back: min6 baau1." },

  // ===== Level 8 =====
  { hanzi: "因為", level: 8, jyutping: ["jan1 wai6"], meanings: ["because"],
    meaningMnemonic: "因 (because/cause) + 為 (for/because of) = BECAUSE.",
    readingMnemonic: "Just say jan1 (因) then wai6 (為) back to back: jan1 wai6." },
  { hanzi: "所以", level: 8, jyutping: ["so2 ji5"], meanings: ["therefore", "so"],
    meaningMnemonic: "所 (that which) + 以 (by means of) = 'that being the means' — THEREFORE, SO.",
    readingMnemonic: "Just say so2 (所) then ji5 (以) back to back: so2 ji5." },
  { hanzi: "但係", level: 8, jyutping: ["daan6 hai6"], meanings: ["but"],
    meaningMnemonic: "但 (but) + 係 (to be) = BUT.",
    readingMnemonic: "Just say daan6 (但) then hai6 (係) back to back: daan6 hai6." },
  { hanzi: "新年", level: 8, jyutping: ["san1 nin4"], meanings: ["New Year"],
    meaningMnemonic: "新 (new) + 年 (year) = NEW YEAR.",
    readingMnemonic: "Just say san1 (新) then nin4 (年) back to back: san1 nin4." },
  { hanzi: "舊年", level: 8, jyutping: ["gau6 nin4"], meanings: ["last year"],
    meaningMnemonic: "舊 (old) + 年 (year) = the old year, LAST YEAR (the everyday colloquial word, alongside 去年).",
    readingMnemonic: "Just say gau6 (舊) then nin4 (年) back to back: gau6 nin4." },
  { hanzi: "快慢", level: 8, jyutping: ["faai3 maan6"], meanings: ["speed", "pace"],
    meaningMnemonic: "快 (fast) + 慢 (slow) = 'fast-slow' — SPEED, PACE.",
    readingMnemonic: "Just say faai3 (快) then maan6 (慢) back to back: faai3 maan6." },
  { hanzi: "新屋", level: 8, jyutping: ["san1 uk1"], meanings: ["new house"],
    meaningMnemonic: "新 (new) + 屋 (house) = NEW HOUSE.",
    readingMnemonic: "Just say san1 (新) then uk1 (屋) back to back: san1 uk1." },
  { hanzi: "舊屋", level: 8, jyutping: ["gau6 uk1"], meanings: ["old house"],
    meaningMnemonic: "舊 (old) + 屋 (house) = OLD HOUSE.",
    readingMnemonic: "Just say gau6 (舊) then uk1 (屋) back to back: gau6 uk1." },
  { hanzi: "同學", level: 8, jyutping: ["tung4 hok6"], meanings: ["classmate"],
    meaningMnemonic: "同 (same/with) + 學 (study) = someone who studies WITH you, a CLASSMATE.",
    readingMnemonic: "Just say tung4 (同) then hok6 (學) back to back: tung4 hok6." },
  { hanzi: "以為", level: 8, jyutping: ["ji5 wai4"], meanings: ["to think (mistakenly)", "to assume"],
    meaningMnemonic: "以 (by means of) + 為 — here 為 shifts to its wai4 reading meaning 'to regard as' — together, TO ASSUME (often wrongly).",
    readingMnemonic: "Note 為 changes reading here: not wai6 but wai4. Say ji5 (以) then wai4: ji5 wai4." },

  // ===== Level 9 =====
  { hanzi: "佢哋", level: 9, jyutping: ["keoi5 dei6"], meanings: ["they", "them"],
    meaningMnemonic: "佢 (he/she/it) + 哋 (plural marker) = THEY, THEM.",
    readingMnemonic: "Just say keoi5 (佢) then dei6 (哋) back to back: keoi5 dei6." },
  { hanzi: "我哋", level: 9, jyutping: ["ngo5 dei6"], meanings: ["we", "us"],
    meaningMnemonic: "我 (I) + 哋 (plural marker) = WE, US.",
    readingMnemonic: "Just say ngo5 (我) then dei6 (哋) back to back: ngo5 dei6." },
  { hanzi: "你哋", level: 9, jyutping: ["nei5 dei6"], meanings: ["you all", "you (plural)"],
    meaningMnemonic: "你 (you) + 哋 (plural marker) = YOU ALL.",
    readingMnemonic: "Just say nei5 (你) then dei6 (哋) back to back: nei5 dei6." },
  { hanzi: "紅色", level: 9, jyutping: ["hung4 sik1"], meanings: ["red"],
    meaningMnemonic: "紅 (red) + 色 (color) = the color RED.",
    readingMnemonic: "Just say hung4 (紅) then sik1 (色) back to back: hung4 sik1." },
  { hanzi: "黃色", level: 9, jyutping: ["wong4 sik1"], meanings: ["yellow"],
    meaningMnemonic: "黃 (yellow) + 色 (color) = the color YELLOW.",
    readingMnemonic: "Just say wong4 (黃) then sik1 (色) back to back: wong4 sik1." },
  { hanzi: "藍色", level: 9, jyutping: ["laam4 sik1"], meanings: ["blue"],
    meaningMnemonic: "藍 (blue) + 色 (color) = the color BLUE.",
    readingMnemonic: "Just say laam4 (藍) then sik1 (色) back to back: laam4 sik1." },
  { hanzi: "黑色", level: 9, jyutping: ["hak1 sik1"], meanings: ["black"],
    meaningMnemonic: "黑 (black) + 色 (color) = the color BLACK.",
    readingMnemonic: "Just say hak1 (黑) then sik1 (色) back to back: hak1 sik1." },
  { hanzi: "白色", level: 9, jyutping: ["baak6 sik1"], meanings: ["white"],
    meaningMnemonic: "白 (white) + 色 (color) = the color WHITE.",
    readingMnemonic: "Just say baak6 (白) then sik1 (色) back to back: baak6 sik1." },

  // ===== Level 10 =====
  { hanzi: "開心", level: 10, jyutping: ["hoi1 sam1"], meanings: ["happy"],
    meaningMnemonic: "開 (open) + 心 (heart) = an OPEN HEART — HAPPY.",
    readingMnemonic: "Just say hoi1 (開) then sam1 (心) back to back: hoi1 sam1." },
  { hanzi: "心水", level: 10, jyutping: ["sam1 seoi2"], meanings: ["one's preference", "taste"],
    meaningMnemonic: "心 (heart) + 水 (water) = the flow of your HEART — your personal PREFERENCE or TASTE.",
    readingMnemonic: "Just say sam1 (心) then seoi2 (水) back to back: sam1 seoi2." },
  { hanzi: "開口", level: 10, jyutping: ["hoi1 hau2"], meanings: ["to open one's mouth", "to speak up"],
    meaningMnemonic: "開 (open) + 口 (mouth) = TO OPEN ONE'S MOUTH, i.e. to speak up.",
    readingMnemonic: "Just say hoi1 (開) then hau2 (口) back to back: hoi1 hau2." },

  // ===== Level 11 =====
  { hanzi: "落雨", level: 11, jyutping: ["lok6 jyu5"], meanings: ["to rain"],
    meaningMnemonic: "落 (to fall) + 雨 (rain) = RAIN falling — TO RAIN.",
    readingMnemonic: "Just say lok6 (落) then jyu5 (雨) back to back: lok6 jyu5." },
  { hanzi: "落雪", level: 11, jyutping: ["lok6 syut3"], meanings: ["to snow"],
    meaningMnemonic: "落 (to fall) + 雪 (snow) = SNOW falling — TO SNOW.",
    readingMnemonic: "Just say lok6 (落) then syut3 (雪) back to back: lok6 syut3." },
  { hanzi: "好熱", level: 11, jyutping: ["hou2 jit6"], meanings: ["so hot", "very hot"],
    meaningMnemonic: "好 (very) + 熱 (hot) = SO HOT.",
    readingMnemonic: "Just say hou2 (好) then jit6 (熱) back to back: hou2 jit6." },
  { hanzi: "好凍", level: 11, jyutping: ["hou2 dung3"], meanings: ["so cold", "very cold"],
    meaningMnemonic: "好 (very) + 凍 (cold) = SO COLD.",
    readingMnemonic: "Just say hou2 (好) then dung3 (凍) back to back: hou2 dung3." },
  { hanzi: "風水", level: 11, jyutping: ["fung1 seoi2"], meanings: ["feng shui"],
    meaningMnemonic: "風 (wind) + 水 (water) = FENG SHUI, the art of arranging spaces in harmony with wind and water.",
    readingMnemonic: "Just say fung1 (風) then seoi2 (水) back to back: fung1 seoi2." },
  { hanzi: "白雲", level: 11, jyutping: ["baak6 wan4"], meanings: ["white cloud"],
    meaningMnemonic: "白 (white) + 雲 (cloud) = WHITE CLOUD.",
    readingMnemonic: "Just say baak6 (白) then wan4 (雲) back to back: baak6 wan4." },
  { hanzi: "大風", level: 11, jyutping: ["daai6 fung1"], meanings: ["strong wind", "windy"],
    meaningMnemonic: "大 (big) + 風 (wind) = a BIG WIND — WINDY.",
    readingMnemonic: "Just say daai6 (大) then fung1 (風) back to back: daai6 fung1." },
  { hanzi: "落街", level: 11, jyutping: ["lok6 gaai1"], meanings: ["to go out", "to go downstairs"],
    meaningMnemonic: "落 (to go down) + 街 (street) = heading DOWN to the STREET — TO GO OUT.",
    readingMnemonic: "Just say lok6 (落) then gaai1 (街) back to back: lok6 gaai1." },

  // ===== Level 12 =====
  { hanzi: "搭車", level: 12, jyutping: ["daap3 ce1"], meanings: ["to take a vehicle"],
    meaningMnemonic: "搭 (to take/ride) + 車 (vehicle) = TO TAKE A VEHICLE.",
    readingMnemonic: "Just say daap3 (搭) then ce1 (車) back to back: daap3 ce1." },
  { hanzi: "搭船", level: 12, jyutping: ["daap3 syun4"], meanings: ["to take a boat"],
    meaningMnemonic: "搭 (to take/ride) + 船 (boat) = TO TAKE A BOAT.",
    readingMnemonic: "Just say daap3 (搭) then syun4 (船) back to back: daap3 syun4." },
  { hanzi: "行路", level: 12, jyutping: ["haang4 lou6"], meanings: ["to walk", "to go on foot"],
    meaningMnemonic: "行 (to walk) + 路 (road) = walking the ROAD — TO WALK.",
    readingMnemonic: "Just say haang4 (行) then lou6 (路) back to back: haang4 lou6." },
  { hanzi: "返屋企", level: 12, jyutping: ["faan1 uk1 kei5"], meanings: ["to go home", "to return home"],
    meaningMnemonic: "返 (to return) + 屋企 (home) = TO GO HOME.",
    readingMnemonic: "Just say faan1 (返) then uk1 kei5 (屋企) back to back: faan1 uk1 kei5." },
  { hanzi: "返學", level: 12, jyutping: ["faan1 hok6"], meanings: ["to go to school"],
    meaningMnemonic: "返 (to return) + 學 (study) = heading back to STUDY — TO GO TO SCHOOL.",
    readingMnemonic: "Just say faan1 (返) then hok6 (學) back to back: faan1 hok6." },
  { hanzi: "車站", level: 12, jyutping: ["ce1 zaam6"], meanings: ["vehicle station", "stop"],
    meaningMnemonic: "車 (vehicle) + 站 (station) = VEHICLE STATION, STOP.",
    readingMnemonic: "Just say ce1 (車) then zaam6 (站) back to back: ce1 zaam6." },
  { hanzi: "到站", level: 12, jyutping: ["dou3 zaam6"], meanings: ["to arrive at the station"],
    meaningMnemonic: "到 (to arrive) + 站 (station) = TO ARRIVE AT THE STATION.",
    readingMnemonic: "Just say dou3 (到) then zaam6 (站) back to back: dou3 zaam6." },
  { hanzi: "上車", level: 12, jyutping: ["soeng5 ce1"], meanings: ["to get on a vehicle"],
    meaningMnemonic: "上 (up, onto) + 車 (vehicle) = TO GET ON A VEHICLE.",
    readingMnemonic: "Just say soeng5 (上) then ce1 (車) back to back: soeng5 ce1." },

  // ===== Level 13 =====
  { hanzi: "鍾意", level: 13, jyutping: ["zung1 ji3"], meanings: ["to like"],
    meaningMnemonic: "鍾 (to like, in this word) + 意 (meaning/idea) = TO LIKE.",
    readingMnemonic: "Just say zung1 (鍾) then ji3 (意) back to back: zung1 ji3." },
  { hanzi: "唔鍾意", level: 13, jyutping: ["m4 zung1 ji3"], meanings: ["to dislike"],
    meaningMnemonic: "唔 (not) + 鍾意 (to like) = TO DISLIKE.",
    readingMnemonic: "Just say m4 (唔) then zung1 ji3 (鍾意) back to back: m4 zung1 ji3." },
  { hanzi: "唔怕", level: 13, jyutping: ["m4 paa3"], meanings: ["no fear", "don't worry"],
    meaningMnemonic: "唔 (not) + 怕 (afraid) = NO FEAR, DON'T WORRY.",
    readingMnemonic: "Just say m4 (唔) then paa3 (怕) back to back: m4 paa3." },
  { hanzi: "好笑", level: 13, jyutping: ["hou2 siu3"], meanings: ["funny"],
    meaningMnemonic: "好 (good) + 笑 (to laugh) = good for a laugh — FUNNY.",
    readingMnemonic: "Just say hou2 (好) then siu3 (笑) back to back: hou2 siu3." },
  { hanzi: "好驚", level: 13, jyutping: ["hou2 geng1"], meanings: ["very scared"],
    meaningMnemonic: "好 (very) + 驚 (scared) = VERY SCARED.",
    readingMnemonic: "Just say hou2 (好) then geng1 (驚) back to back: hou2 geng1." },
  { hanzi: "愛心", level: 13, jyutping: ["ngoi3 sam1"], meanings: ["loving heart", "compassion"],
    meaningMnemonic: "愛 (love) + 心 (heart) = LOVING HEART, COMPASSION.",
    readingMnemonic: "Just say ngoi3 (愛) then sam1 (心) back to back: ngoi3 sam1." },
  { hanzi: "大笑", level: 13, jyutping: ["daai6 siu3"], meanings: ["to laugh loudly"],
    meaningMnemonic: "大 (big) + 笑 (to laugh) = a BIG laugh — TO LAUGH LOUDLY.",
    readingMnemonic: "Just say daai6 (大) then siu3 (笑) back to back: daai6 siu3." },

  // ===== Level 14 =====
  { hanzi: "幾多錢", level: 14, jyutping: ["gei2 do1 cin2"], meanings: ["how much money"],
    meaningMnemonic: "幾多 (how much) + 錢 (money) = HOW MUCH MONEY — the classic haggling question.",
    readingMnemonic: "Just say gei2 do1 (幾多) then cin2 (錢) back to back: gei2 do1 cin2." },
  { hanzi: "平嘢", level: 14, jyutping: ["peng4 je5"], meanings: ["cheap thing", "bargain"],
    meaningMnemonic: "平 (cheap) + 嘢 (thing) = a CHEAP THING, a BARGAIN.",
    readingMnemonic: "Just say peng4 (平) then je5 (嘢) back to back: peng4 je5." },
  { hanzi: "貴唔貴", level: 14, jyutping: ["gwai3 m4 gwai3"], meanings: ["is it expensive?"],
    meaningMnemonic: "貴 (expensive) + 唔 (not) + 貴 (expensive) = the classic 'verb-not-verb' yes/no question: IS IT EXPENSIVE?",
    readingMnemonic: "Just say gwai3 (貴) then m4 (唔) then gwai3 (貴) again: gwai3 m4 gwai3." },
  { hanzi: "使錢", level: 14, jyutping: ["sai2 cin2"], meanings: ["to spend money"],
    meaningMnemonic: "使 (to spend) + 錢 (money) = TO SPEND MONEY.",
    readingMnemonic: "Just say sai2 (使) then cin2 (錢) back to back: sai2 cin2." },
  { hanzi: "找錢", level: 14, jyutping: ["zaau2 cin2"], meanings: ["to give change"],
    meaningMnemonic: "找 (to give change) + 錢 (money) = TO GIVE CHANGE.",
    readingMnemonic: "Just say zaau2 (找) then cin2 (錢) back to back: zaau2 cin2." },
  { hanzi: "一蚊", level: 14, jyutping: ["jat1 man1"], meanings: ["one dollar"],
    meaningMnemonic: "一 (one) + 蚊 (dollar) = ONE DOLLAR.",
    readingMnemonic: "Just say jat1 (一) then man1 (蚊) back to back: jat1 man1." },
  { hanzi: "十蚊", level: 14, jyutping: ["sap6 man1"], meanings: ["ten dollars"],
    meaningMnemonic: "十 (ten) + 蚊 (dollar) = TEN DOLLARS.",
    readingMnemonic: "Just say sap6 (十) then man1 (蚊) back to back: sap6 man1." },
  { hanzi: "唔使", level: 14, jyutping: ["m4 sai2"], meanings: ["no need to", "you're welcome"],
    meaningMnemonic: "唔 (not) + 使 (need to) = NO NEED TO; also used as a casual 'YOU'RE WELCOME.'",
    readingMnemonic: "Just say m4 (唔) then sai2 (使) back to back: m4 sai2." },
  { hanzi: "有錢", level: 14, jyutping: ["jau5 cin2"], meanings: ["to have money", "rich"],
    meaningMnemonic: "有 (to have) + 錢 (money) = TO HAVE MONEY, RICH.",
    readingMnemonic: "Just say jau5 (有) then cin2 (錢) back to back: jau5 cin2." },
  { hanzi: "冇錢", level: 14, jyutping: ["mou5 cin2"], meanings: ["broke", "no money"],
    meaningMnemonic: "冇 (to not have) + 錢 (money) = BROKE, NO MONEY.",
    readingMnemonic: "Just say mou5 (冇) then cin2 (錢) back to back: mou5 cin2." },

  // ===== Level 15 =====
  { hanzi: "做工", level: 15, jyutping: ["zou6 gung1"], meanings: ["to work"],
    meaningMnemonic: "做 (to do) + 工 (work) = TO WORK.",
    readingMnemonic: "Just say zou6 (做) then gung1 (工) back to back: zou6 gung1." },
  { hanzi: "上課", level: 15, jyutping: ["soeng5 fo3"], meanings: ["to attend class"],
    meaningMnemonic: "上 (to go up/attend) + 課 (class) = TO ATTEND CLASS.",
    readingMnemonic: "Just say soeng5 (上) then fo3 (課) back to back: soeng5 fo3." },
  { hanzi: "好忙", level: 15, jyutping: ["hou2 mong4"], meanings: ["very busy"],
    meaningMnemonic: "好 (very) + 忙 (busy) = VERY BUSY.",
    readingMnemonic: "Just say hou2 (好) then mong4 (忙) back to back: hou2 mong4." },
  { hanzi: "識講", level: 15, jyutping: ["sik1 gong2"], meanings: ["to know how to speak (a language)"],
    meaningMnemonic: "識 (to know) + 講 (to speak) = TO KNOW HOW TO SPEAK (a language).",
    readingMnemonic: "Just say sik1 (識) then gong2 (講) back to back: sik1 gong2." },
  { hanzi: "想食", level: 15, jyutping: ["soeng2 sik6"], meanings: ["to want to eat"],
    meaningMnemonic: "想 (to want) + 食 (to eat) = TO WANT TO EAT.",
    readingMnemonic: "Just say soeng2 (想) then sik6 (食) back to back: soeng2 sik6." },
  { hanzi: "想去", level: 15, jyutping: ["soeng2 heoi3"], meanings: ["to want to go"],
    meaningMnemonic: "想 (to want) + 去 (to go) = TO WANT TO GO.",
    readingMnemonic: "Just say soeng2 (想) then heoi3 (去) back to back: soeng2 heoi3." },
  { hanzi: "讀書", level: 15, jyutping: ["duk6 syu1"], meanings: ["to study", "to read books"],
    meaningMnemonic: "讀 (to read/study) + 書 (book) = TO STUDY, TO READ BOOKS.",
    readingMnemonic: "Just say duk6 (讀) then syu1 (書) back to back: duk6 syu1." },
  { hanzi: "睇書", level: 15, jyutping: ["tai2 syu1"], meanings: ["to read a book"],
    meaningMnemonic: "睇 (to look) + 書 (book) = TO READ A BOOK.",
    readingMnemonic: "Just say tai2 (睇) then syu1 (書) back to back: tai2 syu1." },

  // ===== Level 16 =====
  { hanzi: "一百", level: 16, jyutping: ["jat1 baak3"], meanings: ["one hundred"],
    meaningMnemonic: "一 (one) + 百 (hundred) = ONE HUNDRED.",
    readingMnemonic: "Just say jat1 (一) then baak3 (百) back to back: jat1 baak3." },
  { hanzi: "一千", level: 16, jyutping: ["jat1 cin1"], meanings: ["one thousand"],
    meaningMnemonic: "一 (one) + 千 (thousand) = ONE THOUSAND.",
    readingMnemonic: "Just say jat1 (一) then cin1 (千) back to back: jat1 cin1." },
  { hanzi: "一萬", level: 16, jyutping: ["jat1 maan6"], meanings: ["ten thousand"],
    meaningMnemonic: "一 (one) + 萬 (ten thousand) = TEN THOUSAND.",
    readingMnemonic: "Just say jat1 (一) then maan6 (萬) back to back: jat1 maan6." },
  { hanzi: "半年", level: 16, jyutping: ["bun3 nin4"], meanings: ["half a year"],
    meaningMnemonic: "半 (half) + 年 (year) = HALF A YEAR.",
    readingMnemonic: "Just say bun3 (半) then nin4 (年) back to back: bun3 nin4." },
  { hanzi: "三點鐘", level: 16, jyutping: ["saam1 dim2 zung1"], meanings: ["three o'clock"],
    meaningMnemonic: "三 (three) + 點 (point/dot, i.e. o'clock) + 鐘 (clock) = THREE O'CLOCK.",
    readingMnemonic: "Just say saam1 (三) then dim2 (點) then zung1 (鐘): saam1 dim2 zung1." },
  { hanzi: "幾多分鐘", level: 16, jyutping: ["gei2 do1 fan1 zung1"], meanings: ["how many minutes"],
    meaningMnemonic: "幾多 (how many) + 分鐘 (minutes) = HOW MANY MINUTES.",
    readingMnemonic: "Just say gei2 do1 (幾多) then fan1 zung1 (分鐘): gei2 do1 fan1 zung1." },
  { hanzi: "唔好遲", level: 16, jyutping: ["m4 hou2 ci4"], meanings: ["don't be late"],
    meaningMnemonic: "唔好 (don't) + 遲 (late) = DON'T BE LATE.",
    readingMnemonic: "Just say m4 hou2 (唔好) then ci4 (遲) back to back: m4 hou2 ci4." },
  { hanzi: "遲到", level: 16, jyutping: ["ci4 dou3"], meanings: ["to be late", "to arrive late"],
    meaningMnemonic: "遲 (late) + 到 (to arrive) = TO ARRIVE LATE.",
    readingMnemonic: "Just say ci4 (遲) then dou3 (到) back to back: ci4 dou3." },

  // ===== Level 17 =====
  { hanzi: "電話", level: 17, jyutping: ["din6 waa6"], meanings: ["telephone"],
    meaningMnemonic: "電 (electric) + 話 (speech) = ELECTRIC SPEECH — TELEPHONE.",
    readingMnemonic: "Just say din6 (電) then waa6 (話) back to back: din6 waa6." },
  { hanzi: "電燈", level: 17, jyutping: ["din6 dang1"], meanings: ["electric lamp"],
    meaningMnemonic: "電 (electric) + 燈 (lamp) = ELECTRIC LAMP.",
    readingMnemonic: "Just say din6 (電) then dang1 (燈) back to back: din6 dang1." },
  { hanzi: "開燈", level: 17, jyutping: ["hoi1 dang1"], meanings: ["to turn on the light"],
    meaningMnemonic: "開 (to open) + 燈 (lamp) = TO TURN ON THE LIGHT.",
    readingMnemonic: "Just say hoi1 (開) then dang1 (燈) back to back: hoi1 dang1." },
  { hanzi: "開門", level: 17, jyutping: ["hoi1 mun4"], meanings: ["to open the door"],
    meaningMnemonic: "開 (to open) + 門 (door) = TO OPEN THE DOOR.",
    readingMnemonic: "Just say hoi1 (開) then mun4 (門) back to back: hoi1 mun4." },
  { hanzi: "開窗", level: 17, jyutping: ["hoi1 coeng1"], meanings: ["to open the window"],
    meaningMnemonic: "開 (to open) + 窗 (window) = TO OPEN THE WINDOW.",
    readingMnemonic: "Just say hoi1 (開) then coeng1 (窗) back to back: hoi1 coeng1." },
  { hanzi: "檯燈", level: 17, jyutping: ["toi2 dang1"], meanings: ["desk lamp"],
    meaningMnemonic: "檯 (table) + 燈 (lamp) = DESK LAMP.",
    readingMnemonic: "Just say toi2 (檯) then dang1 (燈) back to back: toi2 dang1." },
  { hanzi: "手機", level: 17, jyutping: ["sau2 gei1"], meanings: ["mobile phone"],
    meaningMnemonic: "手 (hand) + 機 (machine) = a hand-held MACHINE — MOBILE PHONE.",
    readingMnemonic: "Just say sau2 (手) then gei1 (機) back to back: sau2 gei1." },
  { hanzi: "講電話", level: 17, jyutping: ["gong2 din6 waa6"], meanings: ["to talk on the phone"],
    meaningMnemonic: "講 (to speak) + 電話 (telephone) = TO TALK ON THE PHONE.",
    readingMnemonic: "Just say gong2 (講) then din6 waa6 (電話): gong2 din6 waa6." },

  // ===== Level 18 =====
  { hanzi: "醫生", level: 18, jyutping: ["ji1 sang1"], meanings: ["doctor"],
    meaningMnemonic: "醫 (medicine) + 生 (person who does it, as in 學生/student) = DOCTOR.",
    readingMnemonic: "Just say ji1 (醫) then sang1 (生) back to back: ji1 sang1." },
  { hanzi: "睇醫生", level: 18, jyutping: ["tai2 ji1 sang1"], meanings: ["to see a doctor"],
    meaningMnemonic: "睇 (to see) + 醫生 (doctor) = TO SEE A DOCTOR.",
    readingMnemonic: "Just say tai2 (睇) then ji1 sang1 (醫生): tai2 ji1 sang1." },
  { hanzi: "病人", level: 18, jyutping: ["beng6 jan4"], meanings: ["patient"],
    meaningMnemonic: "病 (sick) + 人 (person) = a sick person — PATIENT.",
    readingMnemonic: "Just say beng6 (病) then jan4 (人) back to back: beng6 jan4." },
  { hanzi: "好痛", level: 18, jyutping: ["hou2 tung3"], meanings: ["very painful"],
    meaningMnemonic: "好 (very) + 痛 (pain) = VERY PAINFUL.",
    readingMnemonic: "Just say hou2 (好) then tung3 (痛) back to back: hou2 tung3." },
  { hanzi: "生病", level: 18, jyutping: ["sang1 beng6"], meanings: ["to fall ill"],
    meaningMnemonic: "生 (to develop/come about) + 病 (illness) = for illness to develop — TO FALL ILL.",
    readingMnemonic: "Just say sang1 (生) then beng6 (病) back to back: sang1 beng6." },
  { hanzi: "大病", level: 18, jyutping: ["daai6 beng6"], meanings: ["serious illness"],
    meaningMnemonic: "大 (big) + 病 (illness) = a BIG illness — SERIOUS ILLNESS.",
    readingMnemonic: "Just say daai6 (大) then beng6 (病) back to back: daai6 beng6." },
  { hanzi: "抖一抖", level: 18, jyutping: ["dau2 jat1 dau2"], meanings: ["to rest for a bit"],
    meaningMnemonic: "抖 (to rest) + 一 (one) + 抖 (to rest) again — this reduplication pattern (verb-one-verb) softens it to TO REST FOR A BIT.",
    readingMnemonic: "Just say dau2 (抖) then jat1 (一) then dau2 (抖) again: dau2 jat1 dau2." },

  // ===== Level 19 =====
  { hanzi: "唔該", level: 19, jyutping: ["m4 goi1"], meanings: ["please", "thank you", "excuse me"],
    meaningMnemonic: "唔 (not) + 該 (should) here softens into everyday PLEASE / THANK YOU / EXCUSE ME — the single most useful phrase in Cantonese.",
    readingMnemonic: "Just say m4 (唔) then goi1 (該) back to back: m4 goi1." },
  { hanzi: "多謝", level: 19, jyutping: ["do1 ze6"], meanings: ["thank you"],
    meaningMnemonic: "多 (much) + 謝 (thanks) = MUCH THANKS — THANK YOU (used especially for gifts or compliments).",
    readingMnemonic: "Just say do1 (多) then ze6 (謝) back to back: do1 ze6." },
  { hanzi: "對唔住", level: 19, jyutping: ["deoi3 m4 zyu6"], meanings: ["sorry"],
    meaningMnemonic: "對 (correct) + 唔 (not) + 住 (to hold steady) = unable to hold yourself CORRECTLY — SORRY.",
    readingMnemonic: "Just say deoi3 (對) then m4 (唔) then zyu6 (住): deoi3 m4 zyu6." },
  { hanzi: "再見", level: 19, jyutping: ["zoi3 gin3"], meanings: ["goodbye"],
    meaningMnemonic: "再 (again) + 見 (to see) = SEE YOU AGAIN — GOODBYE.",
    readingMnemonic: "Just say zoi3 (再) then gin3 (見) back to back: zoi3 gin3." },
  { hanzi: "一早", level: 19, jyutping: ["jat1 zou2"], meanings: ["early on", "well in advance"],
    meaningMnemonic: "一 (one/very) + 早 (early) = EARLY ON, WELL IN ADVANCE.",
    readingMnemonic: "Just say jat1 (一) then zou2 (早) back to back: jat1 zou2." },
  { hanzi: "遲早", level: 19, jyutping: ["ci4 zou2"], meanings: ["sooner or later"],
    meaningMnemonic: "遲 (late) + 早 (early) = LATE-OR-EARLY — SOONER OR LATER.",
    readingMnemonic: "Just say ci4 (遲) then zou2 (早) back to back: ci4 zou2." },
  { hanzi: "聽日", level: 19, jyutping: ["teng1 jat6"], meanings: ["tomorrow"],
    meaningMnemonic: "聽 (normally 'listen') + 日 (day) — in this fixed word the pair together simply mean TOMORROW, the next day you'll hear about.",
    readingMnemonic: "Just say teng1 (聽) then jat6 (日) back to back: teng1 jat6." },

  // ===== Level 20 =====
  { hanzi: "如果", level: 20, jyutping: ["jyu4 gwo2"], meanings: ["if"],
    meaningMnemonic: "如 (as, like) + 果 (result) = 'as the result would be' — IF.",
    readingMnemonic: "Just say jyu4 (如) then gwo2 (果) back to back: jyu4 gwo2." },
  { hanzi: "就係", level: 20, jyutping: ["zau6 hai6"], meanings: ["that's exactly it", "precisely"],
    meaningMnemonic: "就 (just, then) + 係 (to be) = THAT'S EXACTLY IT, PRECISELY.",
    readingMnemonic: "Just say zau6 (就) then hai6 (係) back to back: zau6 hai6." },
  { hanzi: "都係", level: 20, jyutping: ["dou1 hai6"], meanings: ["also is", "still is"],
    meaningMnemonic: "都 (also) + 係 (to be) = ALSO IS, STILL IS.",
    readingMnemonic: "Just say dou1 (都) then hai6 (係) back to back: dou1 hai6." },
  { hanzi: "都好", level: 20, jyutping: ["dou1 hou2"], meanings: ["either is fine", "also good"],
    meaningMnemonic: "都 (also/either) + 好 (good) = EITHER IS FINE, ALSO GOOD.",
    readingMnemonic: "Just say dou1 (都) then hou2 (好) back to back: dou1 hou2." },
  { hanzi: "先至", level: 20, jyutping: ["sin1 zi3"], meanings: ["only then"],
    meaningMnemonic: "先 (first) + 至 (until) = 'first, until' — ONLY THEN.",
    readingMnemonic: "Just say sin1 (先) then zi3 (至) back to back: sin1 zi3." },
  { hanzi: "定係", level: 20, jyutping: ["ding6 hai6"], meanings: ["or (in a question)"],
    meaningMnemonic: "定 (or) + 係 (to be) = OR — used to offer a choice, e.g. 'A定係B' (A or B?).",
    readingMnemonic: "Just say ding6 (定) then hai6 (係) back to back: ding6 hai6." },
  { hanzi: "係呀", level: 20, jyutping: ["hai6 aa3"], meanings: ["yes!"],
    meaningMnemonic: "係 (to be, yes) + 呀 (particle) = an emphatic YES!",
    readingMnemonic: "Just say hai6 (係) then aa3 (呀) back to back: hai6 aa3." },
  { hanzi: "一定", level: 20, jyutping: ["jat1 ding6"], meanings: ["definitely"],
    meaningMnemonic: "一 (one) + 定 (fixed) = fixed as one single certain outcome — DEFINITELY.",
    readingMnemonic: "Just say jat1 (一) then ding6 (定) back to back: jat1 ding6." },
];

module.exports = vocabulary;
