// Starter vocabulary set: 80 words across 8 levels, built from the 81
// characters in characters.js. characterIds line up with the 1-based
// insertion order of characters.js (1 = 一 ... 81 = 係).
const vocabulary = [
  // ===== Level 1 =====
  { hanzi: "一", level: 1, jyutping: ["jat1"], meanings: ["one"], characterIds: [1],
    meaningMnemonic: "Same as the character: a single line, ONE.",
    readingMnemonic: "Read exactly like the character 一 (jat1)." },
  { hanzi: "二", level: 1, jyutping: ["ji6"], meanings: ["two"], characterIds: [2],
    meaningMnemonic: "Same as the character: two lines, TWO.",
    readingMnemonic: "Read exactly like the character 二 (ji6)." },
  { hanzi: "三", level: 1, jyutping: ["saam1"], meanings: ["three"], characterIds: [3],
    meaningMnemonic: "Same as the character: three lines, THREE.",
    readingMnemonic: "Read exactly like the character 三 (saam1)." },
  { hanzi: "人", level: 1, jyutping: ["jan4"], meanings: ["person"], characterIds: [4],
    meaningMnemonic: "Standing alone, 人 is simply the word for a PERSON.",
    readingMnemonic: "Read exactly like the character 人 (jan4)." },
  { hanzi: "大", level: 1, jyutping: ["daai6"], meanings: ["big"], characterIds: [5],
    meaningMnemonic: "Standing alone, 大 is simply the word BIG.",
    readingMnemonic: "Read exactly like the character 大 (daai6)." },
  { hanzi: "小", level: 1, jyutping: ["siu2"], meanings: ["small"], characterIds: [6],
    meaningMnemonic: "Standing alone, 小 is simply the word SMALL.",
    readingMnemonic: "Read exactly like the character 小 (siu2)." },
  { hanzi: "好", level: 1, jyutping: ["hou2"], meanings: ["good"], characterIds: [8],
    meaningMnemonic: "Standing alone, 好 is simply the word GOOD.",
    readingMnemonic: "Read exactly like the character 好 (hou2)." },
  { hanzi: "你好", level: 1, jyutping: ["nei5 hou2"], meanings: ["hello"], characterIds: [10, 8],
    meaningMnemonic: "你 (you) + 好 (good) = wishing the person in front of you well — HELLO.",
    readingMnemonic: "Just say nei5 (你) then hou2 (好) back to back: nei5 hou2." },
  { hanzi: "大人", level: 1, jyutping: ["daai6 jan4"], meanings: ["adult"], characterIds: [5, 4],
    meaningMnemonic: "大 (big) + 人 (person) = a big person, an ADULT.",
    readingMnemonic: "Just say daai6 (大) then jan4 (人) back to back: daai6 jan4." },
  { hanzi: "好人", level: 1, jyutping: ["hou2 jan4"], meanings: ["good person", "nice person"], characterIds: [8, 4],
    meaningMnemonic: "好 (good) + 人 (person) = a GOOD PERSON.",
    readingMnemonic: "Just say hou2 (好) then jan4 (人) back to back: hou2 jan4." },

  // ===== Level 2 =====
  { hanzi: "四", level: 2, jyutping: ["sei3"], meanings: ["four"], characterIds: [11],
    meaningMnemonic: "Standing alone, 四 is simply the word FOUR.",
    readingMnemonic: "Read exactly like the character 四 (sei3)." },
  { hanzi: "五", level: 2, jyutping: ["ng5"], meanings: ["five"], characterIds: [12],
    meaningMnemonic: "Standing alone, 五 is simply the word FIVE.",
    readingMnemonic: "Read exactly like the character 五 (ng5)." },
  { hanzi: "六", level: 2, jyutping: ["luk6"], meanings: ["six"], characterIds: [13],
    meaningMnemonic: "Standing alone, 六 is simply the word SIX.",
    readingMnemonic: "Read exactly like the character 六 (luk6)." },
  { hanzi: "女人", level: 2, jyutping: ["neoi5 jan4"], meanings: ["woman"], characterIds: [14, 4],
    meaningMnemonic: "女 (female) + 人 (person) = a WOMAN.",
    readingMnemonic: "Just say neoi5 (女) then jan4 (人) back to back: neoi5 jan4." },
  { hanzi: "男人", level: 2, jyutping: ["naam4 jan4"], meanings: ["man"], characterIds: [15, 4],
    meaningMnemonic: "男 (male) + 人 (person) = a MAN.",
    readingMnemonic: "Just say naam4 (男) then jan4 (人) back to back: naam4 jan4." },
  { hanzi: "老人", level: 2, jyutping: ["lou5 jan4"], meanings: ["elderly person"], characterIds: [18, 4],
    meaningMnemonic: "老 (old) + 人 (person) = an ELDERLY PERSON.",
    readingMnemonic: "Just say lou5 (老) then jan4 (人) back to back: lou5 jan4." },
  { hanzi: "爸爸", level: 2, jyutping: ["baa1 baa1"], meanings: ["dad", "father"], characterIds: [16, 16],
    meaningMnemonic: "爸 doubled up is the everyday, affectionate way to say DAD.",
    readingMnemonic: "Just say baa1 (爸) twice: baa1 baa1." },
  { hanzi: "媽媽", level: 2, jyutping: ["maa1 maa1"], meanings: ["mom", "mother"], characterIds: [17, 17],
    meaningMnemonic: "媽 doubled up is the everyday, affectionate way to say MOM.",
    readingMnemonic: "Just say maa1 (媽) twice: maa1 maa1." },
  { hanzi: "多少", level: 2, jyutping: ["do1 siu2"], meanings: ["how much", "how many"], characterIds: [19, 6],
    meaningMnemonic: "多 (many) + 少 uses the 小-sound 'siu2' here meaning few — putting 'many' and 'few' together asks HOW MUCH / HOW MANY.",
    readingMnemonic: "Just say do1 (多) then siu2 back to back: do1 siu2." },
  { hanzi: "老細", level: 2, jyutping: ["lou5 sai3"], meanings: ["boss"], characterIds: [18, 20],
    meaningMnemonic: "老 (old, i.e. senior) + 細 (small) — literally 'old-small', the everyday Cantonese slang for your BOSS.",
    readingMnemonic: "Just say lou5 (老) then sai3 (細) back to back: lou5 sai3." },

  // ===== Level 3 =====
  { hanzi: "七", level: 3, jyutping: ["cat1"], meanings: ["seven"], characterIds: [21],
    meaningMnemonic: "Standing alone, 七 is simply the word SEVEN.",
    readingMnemonic: "Read exactly like the character 七 (cat1)." },
  { hanzi: "八", level: 3, jyutping: ["baat3"], meanings: ["eight"], characterIds: [22],
    meaningMnemonic: "Standing alone, 八 is simply the word EIGHT.",
    readingMnemonic: "Read exactly like the character 八 (baat3)." },
  { hanzi: "九", level: 3, jyutping: ["gau2"], meanings: ["nine"], characterIds: [23],
    meaningMnemonic: "Standing alone, 九 is simply the word NINE.",
    readingMnemonic: "Read exactly like the character 九 (gau2)." },
  { hanzi: "十", level: 3, jyutping: ["sap6"], meanings: ["ten"], characterIds: [24],
    meaningMnemonic: "Standing alone, 十 is simply the word TEN.",
    readingMnemonic: "Read exactly like the character 十 (sap6)." },
  { hanzi: "今日", level: 3, jyutping: ["gam1 jat6"], meanings: ["today"], characterIds: [30, 25],
    meaningMnemonic: "今 (now) + 日 (day) = this very day, TODAY.",
    readingMnemonic: "Just say gam1 (今) then jat6 (日) back to back: gam1 jat6." },
  { hanzi: "今年", level: 3, jyutping: ["gam1 nin4"], meanings: ["this year"], characterIds: [30, 27],
    meaningMnemonic: "今 (now) + 年 (year) = THIS YEAR.",
    readingMnemonic: "Just say gam1 (今) then nin4 (年) back to back: gam1 nin4." },
  { hanzi: "日日", level: 3, jyutping: ["jat6 jat6"], meanings: ["every day"], characterIds: [25, 25],
    meaningMnemonic: "日 doubled up means EVERY DAY, day after day.",
    readingMnemonic: "Just say jat6 (日) twice: jat6 jat6." },
  { hanzi: "年年", level: 3, jyutping: ["nin4 nin4"], meanings: ["every year"], characterIds: [27, 27],
    meaningMnemonic: "年 doubled up means EVERY YEAR, year after year.",
    readingMnemonic: "Just say nin4 (年) twice: nin4 nin4." },
  { hanzi: "十年", level: 3, jyutping: ["sap6 nin4"], meanings: ["decade"], characterIds: [24, 27],
    meaningMnemonic: "十 (ten) + 年 (year) = ten years, a DECADE.",
    readingMnemonic: "Just say sap6 (十) then nin4 (年) back to back: sap6 nin4." },
  { hanzi: "時時", level: 3, jyutping: ["si4 si4"], meanings: ["often", "always"], characterIds: [28, 28],
    meaningMnemonic: "時 doubled up means at all TIMES — OFTEN, ALWAYS.",
    readingMnemonic: "Just say si4 (時) twice: si4 si4." },

  // ===== Level 4 =====
  { hanzi: "好食", level: 4, jyutping: ["hou2 sik6"], meanings: ["delicious", "tasty"], characterIds: [8, 31],
    meaningMnemonic: "好 (good) + 食 (eat) = good to eat, DELICIOUS.",
    readingMnemonic: "Just say hou2 (好) then sik6 (食) back to back: hou2 sik6." },
  { hanzi: "好睇", level: 4, jyutping: ["hou2 tai2"], meanings: ["good-looking"], characterIds: [8, 35],
    meaningMnemonic: "好 (good) + 睇 (look) = good to look at, GOOD-LOOKING.",
    readingMnemonic: "Just say hou2 (好) then tai2 (睇) back to back: hou2 tai2." },
  { hanzi: "好聽", level: 4, jyutping: ["hou2 teng1"], meanings: ["nice-sounding", "pleasant to hear"], characterIds: [8, 36],
    meaningMnemonic: "好 (good) + 聽 (listen) = good to listen to, NICE-SOUNDING.",
    readingMnemonic: "Just say hou2 (好) then teng1 (聽) back to back: hou2 teng1." },
  { hanzi: "買賣", level: 4, jyutping: ["maai5 maai6"], meanings: ["buying and selling", "business", "trade"], characterIds: [39, 40],
    meaningMnemonic: "買 (buy) + 賣 (sell) = BUYING AND SELLING, i.e. BUSINESS.",
    readingMnemonic: "Just say maai5 (買, rising) then maai6 (賣, low) back to back: maai5 maai6." },
  { hanzi: "做人", level: 4, jyutping: ["zou6 jan4"], meanings: ["to conduct oneself", "to be a person"], characterIds: [38, 4],
    meaningMnemonic: "做 (do/make) + 人 (person) = how you MAKE yourself into a PERSON, i.e. how you conduct yourself in life.",
    readingMnemonic: "Just say zou6 (做) then jan4 (人) back to back: zou6 jan4." },
  { hanzi: "去年", level: 4, jyutping: ["heoi3 nin4"], meanings: ["last year"], characterIds: [33, 27],
    meaningMnemonic: "去 (go, i.e. past) + 年 (year) = the year that has GONE, LAST YEAR.",
    readingMnemonic: "Just say heoi3 (去) then nin4 (年) back to back: heoi3 nin4." },
  { hanzi: "十四", level: 4, jyutping: ["sap6 sei3"], meanings: ["fourteen"], characterIds: [24, 11],
    meaningMnemonic: "十 (ten) + 四 (four) = FOURTEEN.",
    readingMnemonic: "Just say sap6 (十) then sei3 (四) back to back: sap6 sei3." },
  { hanzi: "二十", level: 4, jyutping: ["ji6 sap6"], meanings: ["twenty"], characterIds: [2, 24],
    meaningMnemonic: "二 (two) + 十 (ten) = two tens, TWENTY.",
    readingMnemonic: "Just say ji6 (二) then sap6 (十) back to back: ji6 sap6." },
  { hanzi: "三十", level: 4, jyutping: ["saam1 sap6"], meanings: ["thirty"], characterIds: [3, 24],
    meaningMnemonic: "三 (three) + 十 (ten) = three tens, THIRTY.",
    readingMnemonic: "Just say saam1 (三) then sap6 (十) back to back: saam1 sap6." },
  { hanzi: "六十", level: 4, jyutping: ["luk6 sap6"], meanings: ["sixty"], characterIds: [13, 24],
    meaningMnemonic: "六 (six) + 十 (ten) = six tens, SIXTY.",
    readingMnemonic: "Just say luk6 (六) then sap6 (十) back to back: luk6 sap6." },

  // ===== Level 5 =====
  { hanzi: "屋企", level: 5, jyutping: ["uk1 kei5"], meanings: ["home"], characterIds: [41, 42],
    meaningMnemonic: "屋 (house) + 企 (stand) = the house where you stand and stay, HOME.",
    readingMnemonic: "Just say uk1 (屋) then kei5 (企) back to back: uk1 kei5." },
  { hanzi: "學校", level: 5, jyutping: ["hok6 haau6"], meanings: ["school"], characterIds: [43, 44],
    meaningMnemonic: "學 (study) + 校 (school building) = the SCHOOL.",
    readingMnemonic: "Just say hok6 (學) then haau6 (校) back to back: hok6 haau6." },
  { hanzi: "街市", level: 5, jyutping: ["gaai1 si5"], meanings: ["wet market"], characterIds: [45, 46],
    meaningMnemonic: "街 (street) + 市 (market) = the street MARKET, a WET MARKET.",
    readingMnemonic: "Just say gaai1 (街) then si5 (市) back to back: gaai1 si5." },
  { hanzi: "左右", level: 5, jyutping: ["zo2 jau6"], meanings: ["left and right", "approximately"], characterIds: [49, 50],
    meaningMnemonic: "左 (left) + 右 (right) = LEFT AND RIGHT; also used loosely to mean 'give or take, APPROXIMATELY.'",
    readingMnemonic: "Just say zo2 (左) then jau6 (右) back to back: zo2 jau6." },
  { hanzi: "上下", level: 5, jyutping: ["soeng6 haa6"], meanings: ["up and down", "approximately"], characterIds: [47, 48],
    meaningMnemonic: "上 (up) + 下 (down) = UP AND DOWN; like 左右, also used to mean 'more or less, APPROXIMATELY.'",
    readingMnemonic: "Here 上 flattens to soeng6 (not the rising soeng5) since it's paired as a set phrase — say soeng6 haa6." },
  { hanzi: "上嚟", level: 5, jyutping: ["soeng5 lai4"], meanings: ["come up"], characterIds: [47, 34],
    meaningMnemonic: "上 (up) + 嚟 (come) = COME UP (towards the speaker).",
    readingMnemonic: "Just say soeng5 (上, rising) then lai4 (嚟) back to back: soeng5 lai4." },
  { hanzi: "大學", level: 5, jyutping: ["daai6 hok6"], meanings: ["university"], characterIds: [5, 43],
    meaningMnemonic: "大 (big) + 學 (study) = 'big study' — UNIVERSITY.",
    readingMnemonic: "Just say daai6 (大) then hok6 (學) back to back: daai6 hok6." },
  { hanzi: "中學", level: 5, jyutping: ["zung1 hok6"], meanings: ["secondary school", "middle school"], characterIds: [7, 43],
    meaningMnemonic: "中 (middle) + 學 (study) = 'middle study' — SECONDARY SCHOOL.",
    readingMnemonic: "Just say zung1 (中) then hok6 (學) back to back: zung1 hok6." },
  { hanzi: "小學", level: 5, jyutping: ["siu2 hok6"], meanings: ["primary school", "elementary school"], characterIds: [6, 43],
    meaningMnemonic: "小 (small) + 學 (study) = 'small study' — PRIMARY SCHOOL.",
    readingMnemonic: "Just say siu2 (小) then hok6 (學) back to back: siu2 hok6." },
  { hanzi: "上街", level: 5, jyutping: ["soeng5 gaai1"], meanings: ["go out", "go out onto the street"], characterIds: [47, 45],
    meaningMnemonic: "上 (go up/onto) + 街 (street) = heading out onto the STREET, i.e. to GO OUT.",
    readingMnemonic: "Just say soeng5 (上, rising) then gaai1 (街) back to back: soeng5 gaai1." },

  // ===== Level 6 =====
  { hanzi: "邊個", level: 6, jyutping: ["bin1 go3"], meanings: ["who"], characterIds: [51, 52],
    meaningMnemonic: "邊 (which) + 個 (individual) = 'which one' — WHO.",
    readingMnemonic: "Just say bin1 (邊) then go3 (個) back to back: bin1 go3." },
  { hanzi: "乜嘢", level: 6, jyutping: ["mat1 je5"], meanings: ["what"], characterIds: [53, 59],
    meaningMnemonic: "乜 (what) + 嘢 (thing) = 'what thing' — WHAT.",
    readingMnemonic: "Just say mat1 (乜) then je5 (嘢) back to back: mat1 je5." },
  { hanzi: "點解", level: 6, jyutping: ["dim2 gaai2"], meanings: ["why"], characterIds: [54, 55],
    meaningMnemonic: "點 (how) + 解 (explain) = 'how to explain it' — WHY.",
    readingMnemonic: "Just say dim2 (點) then gaai2 (解) back to back: dim2 gaai2." },
  { hanzi: "點樣", level: 6, jyutping: ["dim2 joeng6"], meanings: ["how", "what way"], characterIds: [54, 57],
    meaningMnemonic: "點 (how) + 樣 (manner) = 'what manner' — HOW, WHAT WAY.",
    readingMnemonic: "Just say dim2 (點) then joeng6 (樣) back to back: dim2 joeng6." },
  { hanzi: "幾多", level: 6, jyutping: ["gei2 do1"], meanings: ["how much", "how many"], characterIds: [56, 19],
    meaningMnemonic: "幾 (how many) + 多 (much) = HOW MUCH, HOW MANY.",
    readingMnemonic: "Just say gei2 (幾) then do1 (多) back to back: gei2 do1." },
  { hanzi: "咁樣", level: 6, jyutping: ["gam2 joeng6"], meanings: ["like that", "in that way"], characterIds: [58, 57],
    meaningMnemonic: "咁 (so/like this) + 樣 (manner) = 'in this/that manner' — LIKE THAT.",
    readingMnemonic: "Just say gam2 (咁) then joeng6 (樣) back to back: gam2 joeng6." },
  { hanzi: "呢個", level: 6, jyutping: ["nei1 go3"], meanings: ["this one"], characterIds: [60, 52],
    meaningMnemonic: "呢 (this) + 個 (individual) = THIS ONE.",
    readingMnemonic: "Just say nei1 (呢) then go3 (個) back to back: nei1 go3." },
  { hanzi: "個個", level: 6, jyutping: ["go3 go3"], meanings: ["everyone", "every one"], characterIds: [52, 52],
    meaningMnemonic: "個 doubled up means every single individual — EVERYONE.",
    readingMnemonic: "Just say go3 (個) twice: go3 go3." },
  { hanzi: "幾個", level: 6, jyutping: ["gei2 go3"], meanings: ["a few", "several"], characterIds: [56, 52],
    meaningMnemonic: "幾 (several) + 個 (individual) = A FEW, SEVERAL.",
    readingMnemonic: "Just say gei2 (幾) then go3 (個) back to back: gei2 go3." },
  { hanzi: "幾時", level: 6, jyutping: ["gei2 si4"], meanings: ["when"], characterIds: [56, 28],
    meaningMnemonic: "幾 (how many/what) + 時 (time) = 'what time' — WHEN.",
    readingMnemonic: "Just say gei2 (幾) then si4 (時) back to back: gei2 si4." },

  // ===== Level 7 =====
  { hanzi: "食飯", level: 7, jyutping: ["sik6 faan6"], meanings: ["to eat", "to have a meal"], characterIds: [31, 62],
    meaningMnemonic: "食 (eat) + 飯 (rice/meal) = TO EAT / HAVE A MEAL — the most common way to say 'eat' in Cantonese.",
    readingMnemonic: "Just say sik6 (食) then faan6 (飯) back to back: sik6 faan6." },
  { hanzi: "飲茶", level: 7, jyutping: ["jam2 caa4"], meanings: ["to drink tea", "yum cha"], characterIds: [32, 61],
    meaningMnemonic: "飲 (drink) + 茶 (tea) = TO DRINK TEA — also the name for the whole dim sum outing, YUM CHA.",
    readingMnemonic: "Just say jam2 (飲) then caa4 (茶) back to back: jam2 caa4." },
  { hanzi: "牛肉", level: 7, jyutping: ["ngau4 juk6"], meanings: ["beef"], characterIds: [66, 70],
    meaningMnemonic: "牛 (cow) + 肉 (meat) = BEEF.",
    readingMnemonic: "Just say ngau4 (牛) then juk6 (肉) back to back: ngau4 juk6." },
  { hanzi: "豬肉", level: 7, jyutping: ["zyu1 juk6"], meanings: ["pork"], characterIds: [67, 70],
    meaningMnemonic: "豬 (pig) + 肉 (meat) = PORK.",
    readingMnemonic: "Just say zyu1 (豬) then juk6 (肉) back to back: zyu1 juk6." },
  { hanzi: "雞肉", level: 7, jyutping: ["gai1 juk6"], meanings: ["chicken meat"], characterIds: [68, 70],
    meaningMnemonic: "雞 (chicken) + 肉 (meat) = CHICKEN MEAT.",
    readingMnemonic: "Just say gai1 (雞) then juk6 (肉) back to back: gai1 juk6." },
  { hanzi: "魚肉", level: 7, jyutping: ["jyu4 juk6"], meanings: ["fish meat", "fillet"], characterIds: [69, 70],
    meaningMnemonic: "魚 (fish) + 肉 (meat) = FISH MEAT, FILLET.",
    readingMnemonic: "Just say jyu4 (魚) then juk6 (肉) back to back: jyu4 juk6." },
  { hanzi: "麵包", level: 7, jyutping: ["min6 baau1"], meanings: ["bread"], characterIds: [63, 64],
    meaningMnemonic: "麵 (wheat/noodles) + 包 (bun) = BREAD.",
    readingMnemonic: "Just say min6 (麵) then baau1 (包) back to back: min6 baau1." },
  { hanzi: "蛋", level: 7, jyutping: ["daan2"], meanings: ["egg"], characterIds: [65],
    meaningMnemonic: "Standing alone, 蛋 is simply the word EGG.",
    readingMnemonic: "Read exactly like the character 蛋 (daan2)." },
  { hanzi: "牛", level: 7, jyutping: ["ngau4"], meanings: ["cow", "beef"], characterIds: [66],
    meaningMnemonic: "Standing alone, 牛 is simply the word COW/BEEF.",
    readingMnemonic: "Read exactly like the character 牛 (ngau4)." },
  { hanzi: "雞", level: 7, jyutping: ["gai1"], meanings: ["chicken"], characterIds: [68],
    meaningMnemonic: "Standing alone, 雞 is simply the word CHICKEN.",
    readingMnemonic: "Read exactly like the character 雞 (gai1)." },

  // ===== Level 8 =====
  { hanzi: "因為", level: 8, jyutping: ["jan1 wai6"], meanings: ["because"], characterIds: [73, 74],
    meaningMnemonic: "因 (because/cause) + 為 (for/because of) = BECAUSE.",
    readingMnemonic: "Just say jan1 (因) then wai6 (為) back to back: jan1 wai6." },
  { hanzi: "所以", level: 8, jyutping: ["so2 ji5"], meanings: ["therefore", "so"], characterIds: [75, 76],
    meaningMnemonic: "所 (that which) + 以 (by means of) = 'that being the means' — THEREFORE, SO.",
    readingMnemonic: "Just say so2 (所) then ji5 (以) back to back: so2 ji5." },
  { hanzi: "但係", level: 8, jyutping: ["daan6 hai6"], meanings: ["but"], characterIds: [72, 81],
    meaningMnemonic: "但 (but) + 係 (to be) = BUT.",
    readingMnemonic: "Just say daan6 (但) then hai6 (係) back to back: daan6 hai6." },
  { hanzi: "新年", level: 8, jyutping: ["san1 nin4"], meanings: ["New Year"], characterIds: [77, 27],
    meaningMnemonic: "新 (new) + 年 (year) = NEW YEAR.",
    readingMnemonic: "Just say san1 (新) then nin4 (年) back to back: san1 nin4." },
  { hanzi: "舊年", level: 8, jyutping: ["gau6 nin4"], meanings: ["last year"], characterIds: [78, 27],
    meaningMnemonic: "舊 (old) + 年 (year) = the old year, LAST YEAR (the everyday colloquial word, alongside 去年).",
    readingMnemonic: "Just say gau6 (舊) then nin4 (年) back to back: gau6 nin4." },
  { hanzi: "快慢", level: 8, jyutping: ["faai3 maan6"], meanings: ["speed", "pace"], characterIds: [79, 80],
    meaningMnemonic: "快 (fast) + 慢 (slow) = 'fast-slow' — SPEED, PACE.",
    readingMnemonic: "Just say faai3 (快) then maan6 (慢) back to back: faai3 maan6." },
  { hanzi: "新屋", level: 8, jyutping: ["san1 uk1"], meanings: ["new house"], characterIds: [77, 41],
    meaningMnemonic: "新 (new) + 屋 (house) = NEW HOUSE.",
    readingMnemonic: "Just say san1 (新) then uk1 (屋) back to back: san1 uk1." },
  { hanzi: "舊屋", level: 8, jyutping: ["gau6 uk1"], meanings: ["old house"], characterIds: [78, 41],
    meaningMnemonic: "舊 (old) + 屋 (house) = OLD HOUSE.",
    readingMnemonic: "Just say gau6 (舊) then uk1 (屋) back to back: gau6 uk1." },
  { hanzi: "同學", level: 8, jyutping: ["tung4 hok6"], meanings: ["classmate"], characterIds: [71, 43],
    meaningMnemonic: "同 (same/with) + 學 (study) = someone who studies WITH you, a CLASSMATE.",
    readingMnemonic: "Just say tung4 (同) then hok6 (學) back to back: tung4 hok6." },
  { hanzi: "以為", level: 8, jyutping: ["ji5 wai4"], meanings: ["to think (mistakenly)", "to assume"], characterIds: [76, 74],
    meaningMnemonic: "以 (by means of) + 為 — here 為 shifts to its wai4 reading meaning 'to regard as' — together, TO ASSUME (often wrongly).",
    readingMnemonic: "Note 為 changes reading here: not wai6 but wai4. Say ji5 (以) then wai4: ji5 wai4." },
];

module.exports = vocabulary;
